import type { GlossaryTerm } from '../../types';

const G = 'CONFORMED_GOLD';
const term = (t: Omit<GlossaryTerm, 'related' | 'synonyms'> & Partial<Pick<GlossaryTerm, 'related' | 'synonyms'>>): GlossaryTerm => ({ related: [], synonyms: [], ...t });

const OPS = 'Manufacturing Excellence (D. Kowalczyk)';
const QUAL = 'Quality (S. Haddad)';
const MAINT = 'Reliability Engineering (B. Osei)';
const SCM = 'Supply Chain (T. Brandt)';

export const GLOSSARY: GlossaryTerm[] = [
  term({ id: 'T-001', term: 'Operator', domain: 'Workforce', owner: 'HR Operations (N. Duarte)', steward: 'L. Ferreira', status: 'Approved', isCde: true,
    definition: 'A person badged to run, lead or support a production line at a Forgepoint plant.', formula: 'One record per OPERATOR_ID (MES badge); the current SCD2 version holds today’s role and line.',
    synonyms: ['crew member', 'associate', 'badge'], related: ['T-003'],
    mappings: [{ fqn: `${G}.DIM_OPERATOR`, column: 'OPERATOR_ID', kind: 'defines' }, { fqn: 'CURATED_SILVER.OPERATOR', column: 'OPERATOR_ID', kind: 'defines' }],
    metricRefs: [], dqRules: ['OPERATOR_ID not null', 'OPERATOR_ID unique where IS_CURRENT'], dqScore: 99.7 }),
  term({ id: 'T-002', term: 'Active Production Line', domain: 'Operations', owner: OPS, steward: 'M. Lindgren', status: 'Approved', isCde: true,
    definition: 'A line whose status is Active and that had scheduled production time in the last 30 days. Idle and decommissioned lines are excluded.', formula: "LINE_STATUS = 'Active' AND max(shift date) > as-of date − 30 days",
    synonyms: ['active line', 'running line', 'live line'], related: ['T-004', 'T-003'],
    mappings: [{ fqn: `${G}.DIM_LINE`, column: 'LINE_STATUS', kind: 'filters' }, { fqn: `${G}.FCT_LINE_PRODUCTION`, column: 'DATE_KEY', kind: 'filters' }, { fqn: 'DATA_PRODUCTS.DP_PRODUCTION_OEE', column: 'LINE_ID', kind: 'derives' }],
    metricRefs: ['SV_PLANT_PERFORMANCE.active_lines'], dqRules: ['LINE_STATUS in (Active, Decommissioned)', 'Production recency computed daily'], dqScore: 99.2 }),
  term({ id: 'T-003', term: 'Business Unit', domain: 'Enterprise', owner: 'Corporate FP&A (R. Adeyemi)', steward: 'M. Lindgren', status: 'Approved', isCde: true,
    definition: 'One of Forgepoint’s four business units: Motion Systems, Fluid Power, Industrial Controls and Aerospace Components. Every plant belongs to exactly one.', formula: 'Derived from plant: MS → Motion Systems, FP → Fluid Power, IC → Industrial Controls, AC → Aerospace Components',
    synonyms: ['bu', 'division', 'segment'], related: ['T-002'],
    mappings: [{ fqn: `${G}.DIM_LINE`, column: 'BUSINESS_UNIT', kind: 'defines' }, { fqn: `${G}.DIM_OPERATOR`, column: 'BUSINESS_UNIT', kind: 'defines' }, { fqn: `${G}.FCT_ORDER`, column: 'BUSINESS_UNIT', kind: 'derives' }],
    metricRefs: [], dqRules: ['BUSINESS_UNIT in reference list'], dqScore: 100 }),
  term({ id: 'T-004', term: 'OEE', domain: 'Operations', owner: OPS, steward: 'M. Lindgren', status: 'Approved', isCde: true,
    definition: 'Overall Equipment Effectiveness: the share of planned production time that produced good units at ideal speed. OEE = availability × performance × quality; planned downtime is excluded from the time base.', formula: 'Availability × Performance × Quality = (good units × ideal cycle time) ÷ planned production time',
    synonyms: ['overall equipment effectiveness', 'line efficiency'], related: ['T-005', 'T-006', 'T-007', 'T-008', 'T-009'],
    mappings: [{ fqn: `${G}.FCT_LINE_PRODUCTION`, column: 'PLANNED_PRODUCTION_MIN', kind: 'derives' }, { fqn: `${G}.FCT_LINE_PRODUCTION`, column: 'GOOD_UNITS', kind: 'derives' }, { fqn: `${G}.FCT_LINE_PRODUCTION`, column: 'IDEAL_CYCLE_SEC', kind: 'derives' }, { fqn: `${G}.FCT_LINE_PRODUCTION`, column: 'PLANNED_DOWNTIME_MIN', kind: 'filters' }, { fqn: 'DATA_PRODUCTS.DP_PRODUCTION_OEE', column: 'OEE_PCT', kind: 'defines' }],
    metricRefs: ['SV_PLANT_PERFORMANCE.oee_pct'], dqRules: ['0 ≤ OEE ≤ 100', 'Planned production time > 0', 'Ideal cycle time present for every line'], dqScore: 99.3 }),
  term({ id: 'T-005', term: 'Availability', domain: 'Operations', owner: OPS, steward: 'M. Lindgren', status: 'Approved', isCde: true,
    definition: 'The share of planned production time the line actually ran; lost to breakdowns, material shortages, changeover overruns and quality holds.', formula: 'Run time ÷ planned production time',
    synonyms: ['uptime', 'availability rate'], related: ['T-004', 'T-009'],
    mappings: [{ fqn: `${G}.FCT_LINE_PRODUCTION`, column: 'RUN_MIN', kind: 'derives' }, { fqn: `${G}.FCT_LINE_PRODUCTION`, column: 'PLANNED_PRODUCTION_MIN', kind: 'derives' }],
    metricRefs: ['SV_PLANT_PERFORMANCE.availability_pct'], dqRules: ['RUN_MIN ≤ PLANNED_PRODUCTION_MIN'], dqScore: 99.5 }),
  term({ id: 'T-006', term: 'Performance', domain: 'Operations', owner: OPS, steward: 'M. Lindgren', status: 'Approved', isCde: true,
    definition: 'How close the line ran to its ideal (nameplate) cycle time while running; lost to minor stops and reduced speed.', formula: 'Ideal cycle time × total units ÷ run time',
    synonyms: ['speed', 'rate efficiency', 'performance rate'], related: ['T-004', 'T-029'],
    mappings: [{ fqn: `${G}.FCT_LINE_PRODUCTION`, column: 'IDEAL_CYCLE_SEC', kind: 'derives' }, { fqn: `${G}.FCT_LINE_PRODUCTION`, column: 'TOTAL_UNITS', kind: 'derives' }, { fqn: `${G}.DIM_LINE`, column: 'IDEAL_CYCLE_SEC', kind: 'defines' }],
    metricRefs: ['SV_PLANT_PERFORMANCE.performance_pct'], dqRules: ['Performance ≤ 100% (ideal cycle time not understated)'], dqScore: 98.8 }),
  term({ id: 'T-007', term: 'Quality Rate', domain: 'Operations', owner: OPS, steward: 'M. Lindgren', status: 'Approved', isCde: true,
    definition: 'The share of units started that were good first time — not scrapped and not reworked.', formula: 'Good units ÷ total units',
    synonyms: ['yield', 'good rate'], related: ['T-004', 'T-012', 'T-013'],
    mappings: [{ fqn: `${G}.FCT_LINE_PRODUCTION`, column: 'GOOD_UNITS', kind: 'defines' }, { fqn: `${G}.FCT_LINE_PRODUCTION`, column: 'TOTAL_UNITS', kind: 'derives' }],
    metricRefs: ['SV_PLANT_PERFORMANCE.quality_rate_pct'], dqRules: ['GOOD + SCRAP + REWORK = TOTAL'], dqScore: 99.6 }),
  term({ id: 'T-008', term: 'Planned Downtime', domain: 'Operations', owner: OPS, steward: 'M. Lindgren', status: 'Approved', isCde: true,
    definition: 'Time a line is scheduled not to run: breaks, planned maintenance and planned changeovers. It is removed from the OEE time base, so it never counts as a loss.', formula: 'PLANNED_DOWNTIME_MIN; planned production time = shift time − planned downtime',
    synonyms: ['scheduled downtime', 'planned stops'], related: ['T-004', 'T-009'],
    mappings: [{ fqn: `${G}.FCT_LINE_PRODUCTION`, column: 'PLANNED_DOWNTIME_MIN', kind: 'defines' }, { fqn: 'CURATED_SILVER.LINE_SHIFT_PRODUCTION', column: 'PLANNED_DOWNTIME_MIN', kind: 'defines' }],
    metricRefs: [], dqRules: ['Reason code on the planned list', 'PLANNED_DOWNTIME_MIN < shift minutes'], dqScore: 98.9 }),
  term({ id: 'T-009', term: 'Unplanned Downtime', domain: 'Operations', owner: OPS, steward: 'M. Lindgren', status: 'Approved', isCde: true,
    definition: 'Stoppages during planned production time: breakdowns, material shortages, changeover overruns, quality holds and operator unavailability.', formula: 'Σ UNPLANNED_DOWNTIME_MIN',
    synonyms: ['downtime', 'stoppages', 'lost time'], related: ['T-005', 'T-017'],
    mappings: [{ fqn: `${G}.FCT_LINE_PRODUCTION`, column: 'UNPLANNED_DOWNTIME_MIN', kind: 'defines' }, { fqn: 'DATA_PRODUCTS.DP_PRODUCTION_OEE', column: 'UNPLANNED_DOWNTIME_MIN', kind: 'derives' }],
    metricRefs: ['SV_PLANT_PERFORMANCE.unplanned_downtime_hours'], dqRules: ['Every stop ≥ 5 min carries a reason code'], dqScore: 97.8 }),
  term({ id: 'T-010', term: 'Units Produced', domain: 'Operations', owner: OPS, steward: 'M. Lindgren', status: 'Approved', isCde: false,
    definition: 'Good units completed in the period (excludes scrap and units still in rework).', formula: 'Σ GOOD_UNITS',
    synonyms: ['output', 'throughput', 'production volume'], related: ['T-007'],
    mappings: [{ fqn: `${G}.FCT_LINE_PRODUCTION`, column: 'GOOD_UNITS', kind: 'derives' }, { fqn: 'DATA_PRODUCTS.DP_PRODUCTION_OEE', column: 'GOOD_UNITS', kind: 'defines' }],
    metricRefs: ['SV_PLANT_PERFORMANCE.units_produced'] }),
  term({ id: 'T-011', term: 'First-Pass Yield', domain: 'Quality', owner: QUAL, steward: 'P. Nakamura', status: 'Approved', isCde: true,
    definition: 'The share of inspection lots accepted at their first inspection, without rework, scrap or concession (ISO 9001 clause 8.6 release).', formula: 'Lots with PASSED_FIRST_FLAG ÷ lots inspected × 100',
    synonyms: ['fpy', 'right first time', 'first pass yield'], related: ['T-016', 'T-007'],
    mappings: [{ fqn: `${G}.FCT_QUALITY_INSPECTION`, column: 'PASSED_FIRST_FLAG', kind: 'defines' }, { fqn: 'DATA_PRODUCTS.DP_QUALITY_DEFECTS', column: 'PASSED_FIRST_FLAG', kind: 'defines' }],
    metricRefs: ['SV_PLANT_PERFORMANCE.first_pass_yield_pct'], dqRules: ['Usage decision recorded within 24 h', 'One first inspection per lot'], dqScore: 98.6 }),
  term({ id: 'T-012', term: 'Scrap Rate', domain: 'Quality', owner: QUAL, steward: 'P. Nakamura', status: 'Approved', isCde: true,
    definition: 'Units scrapped as a share of units started.', formula: 'Σ SCRAP_UNITS ÷ Σ TOTAL_UNITS × 100',
    synonyms: ['scrap', 'scrap percentage'], related: ['T-007', 'T-015'],
    mappings: [{ fqn: `${G}.FCT_LINE_PRODUCTION`, column: 'SCRAP_UNITS', kind: 'defines' }, { fqn: 'CURATED_SILVER.LINE_SHIFT_PRODUCTION', column: 'SCRAP_UNITS', kind: 'derives' }],
    metricRefs: ['SV_PLANT_PERFORMANCE.scrap_rate_pct'], dqRules: ['SCRAP_UNITS ≤ TOTAL_UNITS'], dqScore: 99.1 }),
  term({ id: 'T-013', term: 'Rework Rate', domain: 'Quality', owner: QUAL, steward: 'P. Nakamura', status: 'Approved', isCde: false,
    definition: 'Units sent back for rework as a share of units started.', formula: 'Σ REWORK_UNITS ÷ Σ TOTAL_UNITS × 100',
    synonyms: ['rework'], related: ['T-007'],
    mappings: [{ fqn: `${G}.FCT_LINE_PRODUCTION`, column: 'REWORK_UNITS', kind: 'defines' }],
    metricRefs: ['SV_PLANT_PERFORMANCE.rework_rate_pct'] }),
  term({ id: 'T-014', term: 'Defects per Million', domain: 'Quality', owner: QUAL, steward: 'P. Nakamura', status: 'Approved', isCde: false,
    definition: 'Defects found per million units inspected.', formula: 'Σ DEFECT_QTY ÷ Σ INSPECTED_QTY × 1,000,000',
    synonyms: ['ppm', 'dpm', 'defect rate'], related: ['T-011'],
    mappings: [{ fqn: `${G}.FCT_QUALITY_INSPECTION`, column: 'DEFECT_QTY', kind: 'derives' }, { fqn: `${G}.FCT_QUALITY_INSPECTION`, column: 'INSPECTED_QTY', kind: 'derives' }],
    metricRefs: ['SV_PLANT_PERFORMANCE.defects_ppm'] }),
  term({ id: 'T-015', term: 'Cost of Poor Quality', domain: 'Quality', owner: QUAL, steward: 'P. Nakamura', status: 'Approved', isCde: true,
    definition: 'Internal failure cost of nonconforming lots: scrapped material and labour, rework labour and investigation effort.', formula: 'Σ COPQ_USD on lots with an NCR',
    synonyms: ['copq', 'quality cost', 'failure cost'], related: ['T-016', 'T-012'],
    mappings: [{ fqn: `${G}.FCT_QUALITY_INSPECTION`, column: 'COPQ_USD', kind: 'defines' }, { fqn: 'DATA_PRODUCTS.DP_QUALITY_DEFECTS', column: 'COPQ_USD', kind: 'defines' }],
    metricRefs: ['SV_PLANT_PERFORMANCE.copq_usd'], dqRules: ['COPQ_USD ≥ 0', 'COPQ only on lots with an NCR'], dqScore: 96.9 }),
  term({ id: 'T-016', term: 'Nonconformance', domain: 'Quality', owner: QUAL, steward: 'P. Nakamura', status: 'Approved', isCde: false,
    definition: 'A lot that failed its first inspection and was raised on a nonconformance report (NCR) for disposition.', formula: 'NCR_NUMBER is not null',
    synonyms: ['ncr', 'nonconforming lot'], related: ['T-011', 'T-015'],
    mappings: [{ fqn: `${G}.FCT_QUALITY_INSPECTION`, column: 'NCR_NUMBER', kind: 'defines' }, { fqn: 'CURATED_SILVER.QUALITY_INSPECTION_LOT', column: 'NCR_NUMBER', kind: 'defines' }],
    metricRefs: ['SV_PLANT_PERFORMANCE.ncr_count'] }),
  term({ id: 'T-017', term: 'MTBF', domain: 'Maintenance', owner: MAINT, steward: 'K. Mensah', status: 'Approved', isCde: true,
    definition: 'Mean Time Between Failures: average operating hours an asset runs between unplanned failures.', formula: 'Asset operating hours ÷ corrective (failure) work orders',
    synonyms: ['mean time between failures', 'reliability'], related: ['T-018', 'T-020'],
    mappings: [{ fqn: `${G}.FCT_MAINTENANCE_EVENT`, column: 'WO_TYPE', kind: 'filters' }, { fqn: `${G}.FCT_LINE_PRODUCTION`, column: 'RUN_MIN', kind: 'derives' }],
    metricRefs: ['SV_ASSET_MAINTENANCE.mtbf_hours', 'SV_ASSET_MAINTENANCE.failures'], dqRules: ['Every breakdown stop has a corrective work order', 'Asset id valid'], dqScore: 97.6 }),
  term({ id: 'T-018', term: 'MTTR', domain: 'Maintenance', owner: MAINT, steward: 'K. Mensah', status: 'Approved', isCde: true,
    definition: 'Mean Time To Repair: average hours from failure to the asset being returned to production.', formula: 'Σ repair hours ÷ failures',
    synonyms: ['mean time to repair', 'repair time'], related: ['T-017'],
    mappings: [{ fqn: `${G}.FCT_MAINTENANCE_EVENT`, column: 'REPAIR_HOURS', kind: 'defines' }, { fqn: 'DATA_PRODUCTS.DP_ASSET_MAINTENANCE', column: 'REPAIR_HOURS', kind: 'derives' }],
    metricRefs: ['SV_ASSET_MAINTENANCE.mttr_hours', 'SV_ASSET_MAINTENANCE.repair_hours'], dqRules: ['REPAIR_HOURS > 0 on corrective work orders'], dqScore: 98.1 }),
  term({ id: 'T-019', term: 'Planned Maintenance', domain: 'Maintenance', owner: MAINT, steward: 'K. Mensah', status: 'Approved', isCde: true,
    definition: 'Maintenance work raised from a schedule or a condition trigger (calendar PM, condition-based PM from IoT alarms) rather than from a failure.', formula: "WO_TYPE = 'Preventive'; planned maintenance % = preventive work orders ÷ all work orders",
    synonyms: ['pm', 'preventive maintenance', 'planned work'], related: ['T-017'],
    mappings: [{ fqn: `${G}.FCT_MAINTENANCE_EVENT`, column: 'WO_TYPE', kind: 'defines' }, { fqn: 'CURATED_SILVER.ASSET_WORK_ORDER', column: 'WO_TYPE', kind: 'defines' }],
    metricRefs: ['SV_ASSET_MAINTENANCE.planned_maintenance_pct'], dqRules: ['WO_TYPE in (Corrective, Preventive)'], dqScore: 99.0 }),
  term({ id: 'T-020', term: 'Critical Asset', domain: 'Maintenance', owner: MAINT, steward: 'K. Mensah', status: 'Approved', isCde: false,
    definition: 'An asset ranked criticality A: its failure stops the line and has no redundancy.', formula: "CRITICALITY = 'A'",
    synonyms: ['criticality a', 'bottleneck asset'], related: ['T-017'],
    mappings: [{ fqn: `${G}.DIM_ASSET`, column: 'CRITICALITY', kind: 'defines' }],
    metricRefs: [] }),
  term({ id: 'T-021', term: 'Supplier OTIF', domain: 'Supply chain', owner: SCM, steward: 'J. Okonkwo', status: 'Approved', isCde: true,
    definition: 'The share of inbound receipts a supplier delivered on or before the promised date and in full quantity.', formula: 'Receipts on time and in full ÷ receipts × 100',
    synonyms: ['otif', 'on time in full', 'supplier delivery performance'], related: ['T-022', 'T-023'],
    mappings: [{ fqn: `${G}.FCT_SUPPLIER_DELIVERY`, column: 'OTIF_FLAG', kind: 'defines' }, { fqn: 'CURATED_SILVER.SUPPLIER_RECEIPT', column: 'OTIF_FLAG', kind: 'defines' }],
    metricRefs: ['SV_SUPPLIER_PERFORMANCE.otif_pct', 'SV_SUPPLIER_PERFORMANCE.receipts'], dqRules: ['Promised date present', 'Receipt date ≥ PO date'], dqScore: 98.2 }),
  term({ id: 'T-022', term: 'Supplier PPM', domain: 'Supply chain', owner: SCM, steward: 'J. Okonkwo', status: 'Approved', isCde: true,
    definition: 'Parts rejected at incoming inspection per million parts received from a supplier.', formula: 'Σ QTY_REJECTED ÷ Σ QTY_RECEIVED × 1,000,000',
    synonyms: ['incoming ppm', 'supplier quality', 'supplier defect rate'], related: ['T-021'],
    mappings: [{ fqn: `${G}.FCT_SUPPLIER_DELIVERY`, column: 'QTY_REJECTED', kind: 'derives' }, { fqn: `${G}.FCT_SUPPLIER_DELIVERY`, column: 'QTY_RECEIVED', kind: 'derives' }],
    metricRefs: ['SV_SUPPLIER_PERFORMANCE.supplier_ppm'], dqRules: ['QTY_REJECTED ≤ QTY_RECEIVED'], dqScore: 97.4 }),
  term({ id: 'T-023', term: 'Supplier Lead Time', domain: 'Supply chain', owner: SCM, steward: 'J. Okonkwo', status: 'Approved', isCde: false,
    definition: 'Days from purchase order to goods receipt.', formula: 'RECEIVED_DATE − PO date',
    synonyms: ['lead time', 'replenishment time'], related: ['T-021'],
    mappings: [{ fqn: `${G}.FCT_SUPPLIER_DELIVERY`, column: 'LEAD_TIME_DAYS', kind: 'defines' }],
    metricRefs: ['SV_SUPPLIER_PERFORMANCE.lead_time_days'] }),
  term({ id: 'T-024', term: 'On-Time Delivery', domain: 'Order fulfilment', owner: 'Customer Operations (A. Varga)', steward: 'J. Okonkwo', status: 'Approved', isCde: true,
    definition: 'The share of customer order lines delivered on or before the promised delivery date (proof of delivery), measured in the month of delivery.', formula: 'Order lines with DELIVERED_DATE ≤ PROMISED_DATE ÷ order lines delivered × 100',
    synonyms: ['otd', 'on time delivery', 'customer delivery performance'], related: ['T-025', 'T-026'],
    mappings: [{ fqn: `${G}.FCT_ORDER`, column: 'ON_TIME_FLAG', kind: 'defines' }, { fqn: 'DATA_PRODUCTS.DP_ORDER_TO_DELIVERY', column: 'ON_TIME_FLAG', kind: 'defines' }],
    metricRefs: ['SV_ORDER_DELIVERY.on_time_delivery_pct'], dqRules: ['Promised date set at order confirmation', 'Proof-of-delivery date present'], dqScore: 96.4 }),
  term({ id: 'T-025', term: 'Order Fill Rate', domain: 'Order fulfilment', owner: 'Customer Operations (A. Varga)', steward: 'J. Okonkwo', status: 'Approved', isCde: false,
    definition: 'The share of delivered order lines shipped complete (in full).', formula: 'Lines with IN_FULL_FLAG ÷ lines delivered × 100',
    synonyms: ['fill rate', 'in full'], related: ['T-024'],
    mappings: [{ fqn: `${G}.FCT_ORDER`, column: 'IN_FULL_FLAG', kind: 'defines' }, { fqn: `${G}.FCT_ORDER`, column: 'QTY_SHIPPED', kind: 'derives' }],
    metricRefs: ['SV_ORDER_DELIVERY.fill_rate_pct'] }),
  term({ id: 'T-026', term: 'Order Lead Time', domain: 'Order fulfilment', owner: 'Customer Operations (A. Varga)', steward: 'J. Okonkwo', status: 'Approved', isCde: false,
    definition: 'Days from customer order to proof of delivery.', formula: 'DELIVERED_DATE − ORDER_DATE',
    synonyms: ['order cycle time', 'customer lead time'], related: ['T-024'],
    mappings: [{ fqn: `${G}.FCT_ORDER`, column: 'LEAD_TIME_DAYS', kind: 'defines' }],
    metricRefs: ['SV_ORDER_DELIVERY.order_lead_time_days'] }),
  term({ id: 'T-027', term: 'Energy per Unit', domain: 'Sustainability', owner: 'EHS & Sustainability (C. Brennan)', steward: 'R. Iqbal', status: 'Approved', isCde: true,
    definition: 'Metered electricity used by a line per good unit produced.', formula: 'Σ ENERGY_KWH ÷ Σ GOOD_UNITS',
    synonyms: ['energy intensity', 'kwh per unit'], related: ['T-028', 'T-010'],
    mappings: [{ fqn: `${G}.FCT_LINE_PRODUCTION`, column: 'ENERGY_KWH', kind: 'derives' }, { fqn: 'DATA_PRODUCTS.DP_ENERGY_EMISSIONS', column: 'KWH_PER_UNIT', kind: 'defines' }],
    metricRefs: ['DP_ENERGY_EMISSIONS.kwh_per_unit'], dqRules: ['Meter reading present for every running shift'], dqScore: 93.5 }),
  term({ id: 'T-028', term: 'Scope 2 Emissions', domain: 'Sustainability', owner: 'EHS & Sustainability (C. Brennan)', steward: null, status: 'Approved', isCde: true,
    definition: 'Indirect greenhouse-gas emissions from purchased electricity, location-based method, in tonnes CO2e.', formula: 'Σ ENERGY_KWH × plant grid emission factor ÷ 1,000',
    synonyms: ['scope 2', 'carbon emissions', 'co2e'], related: ['T-027'],
    mappings: [{ fqn: 'DATA_PRODUCTS.DP_ENERGY_EMISSIONS', column: 'CO2E_KG', kind: 'defines' }, { fqn: 'DATA_PRODUCTS.DP_ENERGY_EMISSIONS', column: 'EMISSION_FACTOR', kind: 'derives' }],
    metricRefs: ['DP_ENERGY_EMISSIONS.scope2_tco2e'], dqRules: ['Emission factor version recorded per plant'], dqScore: 89.6 }),
  term({ id: 'T-029', term: 'Minor Stop', domain: 'Operations', owner: OPS, steward: 'M. Lindgren', status: 'Draft', isCde: false,
    definition: 'A short stoppage, typically under five minutes, that is not logged with a reason code and shows up as performance loss. Draft: the threshold (3 or 5 minutes) is under review by the OEE working group.', formula: 'Stops < 5 min inside run time, estimated from PLC cycle gaps',
    synonyms: ['micro-stop', 'small stop'], related: ['T-006'],
    mappings: [{ fqn: `${G}.FCT_LINE_PRODUCTION`, column: 'MINOR_STOP_MIN', kind: 'defines' }],
    metricRefs: [] }),
  term({ id: 'T-030', term: 'Customer Order Line', domain: 'Order fulfilment', owner: 'Customer Operations (A. Varga)', steward: 'J. Okonkwo', status: 'Approved', isCde: false,
    definition: 'One product line on a customer sales order, with its own promised date and quantity.', formula: 'ORDER_NO + line number',
    synonyms: ['order line', 'sales order line', 'shipment'], related: ['T-024'],
    mappings: [{ fqn: `${G}.FCT_ORDER`, column: 'ORDER_NO', kind: 'defines' }, { fqn: 'DATA_PRODUCTS.DP_ORDER_TO_DELIVERY', column: 'ORDER_NO', kind: 'defines' }],
    metricRefs: ['SV_ORDER_DELIVERY.order_lines_shipped'] }),
];
