import type { Agent } from '../../types';

export const AGENTS: Agent[] = [
  { id: 'AG-01', name: 'Revenue Cycle Copilot', objectName: 'AGT_REVENUE_CYCLE_COPILOT', domain: 'Revenue cycle', status: 'Production',
    description: 'Answers questions about patient accounts, claims, denials, receivables and supply cost per case.',
    productIds: ['DP-01', 'DP-03', 'DP-05'],
    tools: [{ kind: 'cortex_analyst', target: 'SV_PATIENT_REVENUE' }, { kind: 'cortex_analyst', target: 'SV_SUPPLY_CHAIN' }, { kind: 'cortex_search', target: 'CS_CVH_DOCS' }],
    instructionIds: ['AI-01', 'AI-02', 'AI-03', 'AI-04'], evalAccuracy: 94, evalQuestions: 50,
    scenarioIds: ['S-01', 'S-02', 'S-03', 'S-04', 'S-05'], kpiIds: ['K-01', 'K-02', 'K-03', 'K-04', 'K-05', 'K-06', 'K-07', 'K-08', 'K-09', 'K-10', 'K-22', 'K-23', 'K-24'] },
  { id: 'AG-02', name: 'Clinical Quality Analyst', objectName: 'AGT_CLINICAL_QUALITY_ANALYST', domain: 'Quality & operations', status: 'Production',
    description: 'Answers questions about readmissions (CMS method), length of stay, bed occupancy and care gaps.',
    productIds: ['DP-04', 'DP-02', 'DP-06'],
    tools: [{ kind: 'cortex_analyst', target: 'SV_QUALITY' }, { kind: 'cortex_analyst', target: 'SV_THROUGHPUT' }, { kind: 'cortex_search', target: 'CS_CVH_DOCS' }],
    instructionIds: ['AI-05', 'AI-06', 'AI-07', 'AI-08'], evalAccuracy: 96, evalQuestions: 45,
    scenarioIds: ['S-06', 'S-07', 'S-08', 'S-09'], kpiIds: ['K-11', 'K-12', 'K-15', 'K-18', 'K-20', 'K-21', 'K-25', 'K-26'] },
  { id: 'AG-03', name: 'Patient Access Assistant', objectName: 'AGT_PATIENT_ACCESS_ASSISTANT', domain: 'Patient access', status: 'Production',
    description: 'Answers questions about ED waits, clinic no-shows, appointment lag and follow-up after discharge.',
    productIds: ['DP-02', 'DP-04'],
    tools: [{ kind: 'cortex_analyst', target: 'SV_THROUGHPUT' }, { kind: 'cortex_analyst', target: 'SV_QUALITY' }, { kind: 'cortex_search', target: 'CS_CVH_DOCS' }],
    instructionIds: ['AI-09', 'AI-10', 'AI-11', 'AI-12'], evalAccuracy: 93, evalQuestions: 35,
    scenarioIds: ['S-10', 'S-11', 'S-12'], kpiIds: ['K-13', 'K-14', 'K-16', 'K-17', 'K-19'] },
  { id: 'AG-04', name: 'Data Steward Assistant', objectName: 'AGT_DATA_STEWARD', domain: 'Governance', status: 'Pilot',
    description: 'Finds governance gaps: CDEs without stewards, term usage and certification blockers.',
    productIds: [],
    tools: [{ kind: 'sql', target: 'GLOSSARY_GOVERNANCE_DP_REGISTRY' }],
    instructionIds: ['AI-13', 'AI-14', 'AI-15', 'AI-16'], evalAccuracy: 90, evalQuestions: 25,
    scenarioIds: ['S-13', 'S-14', 'S-15'], kpiIds: [] },
];
