import type { GlossaryTerm } from '../../types';

const G = 'CONFORMED_GOLD';
const S = 'CURATED_SILVER';
const P = 'DATA_PRODUCTS';
const term = (t: Omit<GlossaryTerm, 'related' | 'synonyms'> & Partial<Pick<GlossaryTerm, 'related' | 'synonyms'>>): GlossaryTerm => ({ related: [], synonyms: [], ...t });

export const GLOSSARY: GlossaryTerm[] = [
  term({ id: 'T-001', term: 'Patient', domain: 'Patient access', owner: 'L. Fontaine', steward: 'O. Pritchard', status: 'Approved', isCde: true,
    definition: 'A person registered in the Crestview enterprise master patient index, identified by one medical record number (MRN) across all hospitals and clinics.', formula: 'One record per MRN; the current SCD2 version represents the patient today.',
    synonyms: ['MRN', 'beneficiary'], related: ['T-002', 'T-020'],
    mappings: [{ fqn: `${G}.DIM_PATIENT`, column: 'MRN', kind: 'defines' }, { fqn: `${S}.PATIENT`, column: 'MRN', kind: 'defines' }, { fqn: `${P}.DP_PATIENT_360`, column: 'MRN', kind: 'defines' }],
    metricRefs: [], dqRules: ['MRN not null', 'MRN unique where IS_CURRENT', 'EMPI duplicate score < 0.9'], dqScore: 99.7 }),
  term({ id: 'T-002', term: 'Active Patient', domain: 'Patient access', owner: 'L. Fontaine', steward: 'O. Pritchard', status: 'Approved', isCde: true,
    definition: 'A living patient with at least one completed encounter — inpatient discharge, ED visit or completed clinic appointment — in the last 12 months.', formula: 'PATIENT_STATUS = Active AND latest completed encounter ≥ as-of date − 12 months',
    synonyms: ['active panel', 'current patient'], related: ['T-001', 'T-004'],
    mappings: [{ fqn: `${S}.PATIENT`, column: 'PATIENT_STATUS', kind: 'filters' }, { fqn: `${G}.DIM_PATIENT`, column: 'PATIENT_STATUS', kind: 'filters' }, { fqn: `${P}.DP_PATIENT_360`, column: 'IS_ACTIVE', kind: 'derives' }],
    metricRefs: ['SV_PATIENT_REVENUE.active_patients'], dqRules: ['Status in (Active, Deceased)', 'Encounter recency computed daily'], dqScore: 98.8 }),
  term({ id: 'T-003', term: 'Hospital Market', domain: 'Enterprise', owner: 'Strategy & Planning (C. Moreno)', steward: 'O. Pritchard', status: 'Approved', isCde: true,
    definition: 'One of Crestview’s four hospital markets — North, Central, Coastal and Valley — each a group of hospitals and affiliated clinics with its own leadership.', formula: 'Derived from the facility: hospital code → market (e.g. RMC → Central); patients take the market of their home hospital',
    synonyms: ['market', 'region', 'service area'], related: ['T-001'],
    mappings: [{ fqn: `${G}.DIM_FACILITY`, column: 'MARKET', kind: 'defines' }, { fqn: `${G}.DIM_PATIENT`, column: 'MARKET', kind: 'defines' }, { fqn: `${S}.PATIENT`, column: 'MARKET_CODE', kind: 'derives' }, { fqn: `${G}.FCT_CLAIM`, column: 'MARKET', kind: 'derives' }],
    metricRefs: [], dqRules: ['MARKET in reference list'], dqScore: 100 }),
  term({ id: 'T-004', term: 'Encounter', domain: 'Hospital operations', owner: 'M. Arriaga', steward: 'O. Pritchard', status: 'Approved', isCde: true,
    definition: 'A single interaction between a patient and Crestview: an inpatient stay, an emergency department visit or a clinic appointment.', formula: 'One row per ENCOUNTER_ID from ADT (inpatient, ED) or scheduling (clinic)',
    synonyms: ['visit', 'stay'], related: ['T-005', 'T-030'],
    mappings: [{ fqn: `${G}.FCT_ENCOUNTER`, column: 'ENCOUNTER_ID', kind: 'defines' }, { fqn: `${S}.ENCOUNTER`, column: 'ENCOUNTER_ID', kind: 'defines' }, { fqn: `${P}.DP_ENCOUNTERS_THROUGHPUT`, column: 'ENCOUNTER_ID', kind: 'defines' }],
    metricRefs: [], dqRules: ['ENCOUNTER_ID unique', 'Discharge ≥ admission'], dqScore: 99.6 }),
  term({ id: 'T-005', term: 'Length of Stay', domain: 'Hospital operations', owner: 'M. Arriaga', steward: 'O. Pritchard', status: 'Approved', isCde: true,
    definition: 'The number of midnights an inpatient spends in hospital, from admission to discharge (minimum one day). Average length of stay is reported by discharge date.', formula: 'DISCHARGE_DATE − ADMIT_DATE (days, min 1); ALOS = Σ LOS ÷ discharges',
    synonyms: ['LOS', 'ALOS', 'average length of stay'], related: ['T-004', 'T-010'],
    mappings: [{ fqn: `${G}.FCT_ENCOUNTER`, column: 'LOS_DAYS', kind: 'defines' }, { fqn: `${S}.ENCOUNTER`, column: 'LOS_DAYS', kind: 'defines' }],
    metricRefs: ['SV_THROUGHPUT.avg_length_of_stay'], dqRules: ['LOS_DAYS ≥ 1 for inpatients', 'Observation stays excluded'], dqScore: 99.4 }),
  term({ id: 'T-006', term: '30-Day Readmission', domain: 'Quality & safety', owner: 'Dr. R. Valcourt', steward: 'J. Holloway', status: 'Approved', isCde: true,
    definition: 'An unplanned inpatient admission to any Crestview hospital within 30 days of discharge from an eligible index stay, for any cause. Planned readmissions are not counted (CMS method).', formula: 'Readmission rate = eligible index stays with an unplanned admission 1–30 days after discharge ÷ eligible index stays',
    synonyms: ['readmission', 'readmit', 'bounce back', 'all-cause readmission'], related: ['T-007', 'T-008', 'T-009'],
    mappings: [{ fqn: `${G}.FCT_READMISSION`, column: 'READMIT_30D_FLAG', kind: 'defines' }, { fqn: `${G}.FCT_READMISSION`, column: 'IS_ELIGIBLE_INDEX', kind: 'filters' }, { fqn: `${P}.DP_QUALITY_READMISSIONS`, column: 'READMIT_30D_FLAG', kind: 'defines' }],
    metricRefs: ['SV_QUALITY.readmission_rate_30d', 'SV_QUALITY.readmissions_30d'], dqRules: ['Only reported once the 30-day window has closed', 'Planned flag present on every admission'], dqScore: 99.2 }),
  term({ id: 'T-007', term: 'Index Admission', domain: 'Quality & safety', owner: 'Dr. R. Valcourt', steward: 'J. Holloway', status: 'Approved', isCde: true,
    definition: 'An inpatient discharge that starts a 30-day readmission or follow-up window. Stays ending in transfer to another acute hospital, death or discharge against medical advice are not eligible.', formula: 'IS_ELIGIBLE_INDEX = disposition NOT IN (Transfer to acute, Expired, Left AMA)',
    synonyms: ['index stay', 'index discharge'], related: ['T-006', 'T-022'],
    mappings: [{ fqn: `${G}.FCT_READMISSION`, column: 'IS_ELIGIBLE_INDEX', kind: 'defines' }, { fqn: `${P}.DP_QUALITY_READMISSIONS`, column: 'IS_ELIGIBLE_INDEX', kind: 'defines' }],
    metricRefs: ['SV_QUALITY.index_discharges'], dqRules: ['Disposition coded on every discharge'], dqScore: 99.0 }),
  term({ id: 'T-008', term: 'Planned Readmission', domain: 'Quality & safety', owner: 'Dr. R. Valcourt', steward: 'J. Holloway', status: 'Approved', isCde: true,
    definition: 'A scheduled admission identified by the CMS planned readmission algorithm (for example maintenance chemotherapy or a staged procedure). It is never counted as a readmission.', formula: 'IS_PLANNED = TRUE on the following admission',
    synonyms: ['planned admission', 'staged procedure'], related: ['T-006'],
    mappings: [{ fqn: `${S}.ENCOUNTER`, column: 'IS_PLANNED', kind: 'defines' }, { fqn: `${G}.FCT_READMISSION`, column: 'PLANNED_READMIT_EXCLUDED', kind: 'filters' }],
    metricRefs: [], dqRules: ['Algorithm version recorded', 'Recomputed on coding updates'], dqScore: 98.6 }),
  term({ id: 'T-009', term: 'Service Line', domain: 'Hospital operations', owner: 'M. Arriaga', steward: 'O. Pritchard', status: 'Approved', isCde: true,
    definition: 'The clinical grouping an inpatient stay belongs to, derived from the MS-DRG of the stay: Cardiology, Pulmonology, General Medicine, Orthopedics, General Surgery, Oncology, Neurosciences, and Women’s & Infants.', formula: 'MS-DRG → service line crosswalk',
    synonyms: ['clinical service', 'product line'], related: ['T-006', 'T-005'],
    mappings: [{ fqn: `${G}.FCT_ENCOUNTER`, column: 'SERVICE_LINE', kind: 'defines' }, { fqn: `${G}.FCT_READMISSION`, column: 'SERVICE_LINE', kind: 'defines' }, { fqn: `${S}.ENCOUNTER`, column: 'SERVICE_LINE', kind: 'derives' }],
    metricRefs: [], dqRules: ['SERVICE_LINE in crosswalk'], dqScore: 99.8 }),
  term({ id: 'T-010', term: 'Bed Occupancy', domain: 'Hospital operations', owner: 'M. Arriaga', steward: 'O. Pritchard', status: 'Approved', isCde: false,
    definition: 'The share of staffed inpatient beds filled at the midnight census, averaged over a period.', formula: 'Inpatient nights ÷ (staffed beds × days in period) × 100',
    synonyms: ['occupancy', 'census'], related: ['T-005'],
    mappings: [{ fqn: `${G}.DIM_FACILITY`, column: 'STAFFED_BEDS', kind: 'derives' }, { fqn: `${G}.FCT_ENCOUNTER`, column: 'LOS_DAYS', kind: 'derives' }],
    metricRefs: ['SV_THROUGHPUT.bed_occupancy_pct'] }),
  term({ id: 'T-011', term: 'ED Wait Time', domain: 'Hospital operations', owner: 'M. Arriaga', steward: 'O. Pritchard', status: 'Approved', isCde: true,
    definition: 'Minutes from an emergency department patient’s arrival to first contact with a provider (door-to-provider). Patients who leave without being seen are excluded.', formula: 'PROVIDER_SEEN_TS − ARRIVAL_TS in minutes, averaged over ED visits seen',
    synonyms: ['door to provider', 'ED wait', 'ER wait time'], related: ['T-012'],
    mappings: [{ fqn: `${G}.FCT_ENCOUNTER`, column: 'ED_WAIT_MIN', kind: 'defines' }, { fqn: `${S}.ENCOUNTER`, column: 'ED_WAIT_MIN', kind: 'defines' }],
    metricRefs: ['SV_THROUGHPUT.ed_wait_minutes'], dqRules: ['0 < ED_WAIT_MIN < 720', 'Provider timestamp after arrival'], dqScore: 98.9 }),
  term({ id: 'T-012', term: 'Left Without Being Seen', domain: 'Hospital operations', owner: 'M. Arriaga', steward: 'O. Pritchard', status: 'Approved', isCde: false,
    definition: 'An ED visit where the patient left after triage and before seeing a provider.', formula: 'LWBS visits ÷ ED visits × 100',
    synonyms: ['LWBS', 'walkout'], related: ['T-011'],
    mappings: [{ fqn: `${G}.FCT_ENCOUNTER`, column: 'LWBS_FLAG', kind: 'defines' }],
    metricRefs: ['SV_THROUGHPUT.lwbs_rate'] }),
  term({ id: 'T-013', term: 'No-Show', domain: 'Patient access', owner: 'L. Fontaine', steward: 'O. Pritchard', status: 'Approved', isCde: false,
    definition: 'A scheduled clinic appointment the patient did not attend and did not cancel at least 24 hours ahead. The no-show rate excludes cancellations from the denominator.', formula: 'No-shows ÷ (completed + no-show appointments) × 100',
    synonyms: ['missed appointment', 'DNA'], related: ['T-014'],
    mappings: [{ fqn: `${G}.FCT_APPOINTMENT`, column: 'APPT_STATUS', kind: 'defines' }, { fqn: `${S}.APPOINTMENT`, column: 'APPT_STATUS', kind: 'defines' }],
    metricRefs: ['SV_THROUGHPUT.no_show_rate'] }),
  term({ id: 'T-014', term: 'Appointment Lag', domain: 'Patient access', owner: 'L. Fontaine', steward: 'O. Pritchard', status: 'Approved', isCde: false,
    definition: 'Days between the date an appointment is booked and the date it takes place; reported for new-patient appointments as the access measure.', formula: 'APPT_DATE − BOOKED_DATE',
    synonyms: ['access lag', 'lead time', 'wait for appointment'], related: ['T-013'],
    mappings: [{ fqn: `${G}.FCT_APPOINTMENT`, column: 'LEAD_DAYS', kind: 'defines' }, { fqn: `${S}.APPOINTMENT`, column: 'LEAD_DAYS', kind: 'defines' }],
    metricRefs: ['SV_THROUGHPUT.new_patient_lag_days'] }),
  term({ id: 'T-015', term: 'Claim', domain: 'Revenue cycle', owner: 'K. Kilbride', steward: 'S. Farouk', status: 'Approved', isCde: true,
    definition: 'A bill sent to a payer for an encounter (837I for hospital, 837P for professional services), tracked through remittance (835).', formula: 'One row per patient control number',
    synonyms: ['bill', '837'], related: ['T-016', 'T-017'],
    mappings: [{ fqn: `${G}.FCT_CLAIM`, column: 'CLAIM_ID', kind: 'defines' }, { fqn: `${S}.CLAIM`, column: 'CLAIM_ID', kind: 'defines' }],
    metricRefs: ['SV_PATIENT_REVENUE.claims_submitted'], dqRules: ['CLAIM_ID unique', 'Payer present'], dqScore: 99.5 }),
  term({ id: 'T-016', term: 'Clean Claim', domain: 'Revenue cycle', owner: 'K. Kilbride', steward: 'S. Farouk', status: 'Approved', isCde: true,
    definition: 'A claim that passes every front-end edit and is accepted by the payer on first submission without manual intervention.', formula: 'Clean claim rate = clean claims ÷ claims submitted × 100',
    synonyms: ['first pass yield', 'FPY', 'clean claims'], related: ['T-015', 'T-017'],
    mappings: [{ fqn: `${G}.FCT_CLAIM`, column: 'IS_CLEAN', kind: 'defines' }, { fqn: `${S}.CLAIM`, column: 'IS_CLEAN', kind: 'defines' }],
    metricRefs: ['SV_PATIENT_REVENUE.clean_claim_rate'], dqRules: ['Edit result present for every claim'], dqScore: 98.7 }),
  term({ id: 'T-017', term: 'Claim Denial', domain: 'Revenue cycle', owner: 'K. Kilbride', steward: 'S. Farouk', status: 'Approved', isCde: true,
    definition: 'An initial denial of a submitted claim by the payer, coded with a claim adjustment reason code (CARC). Later appeals do not change the initial denial rate.', formula: 'Denial rate = initially denied claims ÷ claims submitted in the period × 100',
    synonyms: ['denial', 'denied claim', 'denials'], related: ['T-015', 'T-016'],
    mappings: [{ fqn: `${G}.FCT_CLAIM`, column: 'IS_DENIED', kind: 'defines' }, { fqn: `${G}.FCT_CLAIM`, column: 'DENIAL_REASON', kind: 'derives' }, { fqn: `${S}.CLAIM`, column: 'IS_DENIED', kind: 'defines' }],
    metricRefs: ['SV_PATIENT_REVENUE.denial_rate'], dqRules: ['CARC present when denied'], dqScore: 98.4 }),
  term({ id: 'T-018', term: 'Days in A/R', domain: 'Revenue cycle', owner: 'K. Kilbride', steward: 'S. Farouk', status: 'Approved', isCde: true,
    definition: 'How many days of net patient revenue are tied up in open accounts receivable.', formula: 'Open A/R at period end ÷ (expected net revenue for the last 90 days ÷ 90)',
    synonyms: ['DAR', 'AR days', 'days in accounts receivable'], related: ['T-028', 'T-019'],
    mappings: [{ fqn: `${G}.FCT_CLAIM`, column: 'OPEN_AR_USD', kind: 'defines' }, { fqn: `${G}.FCT_CLAIM`, column: 'EXPECTED_NET_USD', kind: 'derives' }, { fqn: `${P}.DP_PATIENT_360`, column: 'OPEN_AR_BALANCE', kind: 'derives' }],
    metricRefs: ['SV_PATIENT_REVENUE.days_in_ar', 'SV_PATIENT_REVENUE.open_ar_balance'], dqRules: ['Revenue > 0 in the 90-day window'], dqScore: 97.6 }),
  term({ id: 'T-019', term: 'Net Collection Rate', domain: 'Revenue cycle', owner: 'K. Kilbride', steward: 'S. Farouk', status: 'Approved', isCde: false,
    definition: 'The share of expected net reimbursement actually collected on resolved claims, after contractual adjustments.', formula: 'Payments ÷ expected net reimbursement × 100 (resolved claims)',
    synonyms: ['NCR', 'collection rate'], related: ['T-018'],
    mappings: [{ fqn: `${G}.FCT_CLAIM`, column: 'PAID_USD', kind: 'derives' }, { fqn: `${G}.FCT_CLAIM`, column: 'EXPECTED_NET_USD', kind: 'derives' }],
    metricRefs: ['SV_PATIENT_REVENUE.net_collection_rate'] }),
  term({ id: 'T-020', term: 'Payer Class', domain: 'Revenue cycle', owner: 'K. Kilbride', steward: 'S. Farouk', status: 'Approved', isCde: true,
    definition: 'The financial class of a patient’s primary coverage: Medicare (including Medicare Advantage), Medicaid (including managed Medicaid), Commercial, or Self-pay when no coverage is active.', formula: 'Mapped from the primary payer id on the current registration',
    synonyms: ['financial class', 'self-pay', 'uninsured', 'coverage'], related: ['T-001', 'T-015'],
    mappings: [{ fqn: `${G}.DIM_PAYER`, column: 'PAYER_CLASS', kind: 'defines' }, { fqn: `${G}.DIM_PATIENT`, column: 'PAYER_CLASS', kind: 'derives' }, { fqn: `${S}.PATIENT`, column: 'PRIMARY_PAYER_ID', kind: 'derives' }],
    metricRefs: ['SV_PATIENT_REVENUE.self_pay_share'], dqRules: ['PAYER_CLASS in reference list'], dqScore: 99.9 }),
  term({ id: 'T-021', term: 'Patient Risk Score', domain: 'Population health', owner: 'Dr. A. Sabbagh', steward: 'O. Pritchard', status: 'Draft', isCde: false,
    definition: 'Model score estimating a patient’s expected cost and utilisation relative to average (1.0 = average), built from diagnoses (HCC-style) and prior use. Draft: model card and bias review pending.', formula: 'Hierarchical condition category weights + demographic factors, normalised to 1.0',
    synonyms: ['risk score', 'acuity score', 'HCC score'], related: ['T-026'],
    mappings: [{ fqn: `${G}.DIM_PATIENT`, column: 'RISK_SCORE', kind: 'defines' }],
    metricRefs: ['SV_PATIENT_REVENUE.avg_risk_score'] }),
  term({ id: 'T-022', term: 'Post-Discharge Follow-Up', domain: 'Quality & safety', owner: 'Dr. R. Valcourt', steward: 'J. Holloway', status: 'Approved', isCde: false,
    definition: 'A completed clinic visit 1 to 7 days after an inpatient discharge to home or home health. The 7-day follow-up rate is reported once the 7-day window has closed.', formula: 'Index discharges home / home health with a completed visit on day 1–7 ÷ those discharges × 100',
    synonyms: ['7-day follow-up', 'follow-up visit', 'transition of care visit'], related: ['T-007', 'T-006'],
    mappings: [{ fqn: `${G}.FCT_READMISSION`, column: 'FOLLOWUP_7D_FLAG', kind: 'defines' }, { fqn: `${G}.FCT_APPOINTMENT`, column: 'IS_POST_DISCHARGE', kind: 'derives' }],
    metricRefs: ['SV_QUALITY.followup_7d_rate'] }),
  term({ id: 'T-023', term: 'Inpatient Mortality', domain: 'Quality & safety', owner: 'Dr. R. Valcourt', steward: 'J. Holloway', status: 'Approved', isCde: false,
    definition: 'Deaths in hospital as a share of inpatient discharges (unadjusted).', formula: 'Discharges with disposition Expired ÷ discharges × 100',
    synonyms: ['mortality rate', 'in-hospital mortality'], related: ['T-007'],
    mappings: [{ fqn: `${G}.FCT_READMISSION`, column: 'EXPIRED_FLAG', kind: 'defines' }],
    metricRefs: ['SV_QUALITY.inpatient_mortality_rate'] }),
  term({ id: 'T-024', term: 'Supply Cost per Case', domain: 'Supply chain', owner: 'P. Tanabe', steward: 'T. Quarshie', status: 'Approved', isCde: true,
    definition: 'Medical-surgical supply and implant cost captured at point of use on surgical cases, divided by the number of surgical cases. Pharmacy is excluded.', formula: 'Σ supply + implant cost on surgical cases ÷ surgical cases discharged in the period',
    synonyms: ['cost per case', 'CPC', 'supply cost per surgical case'], related: ['T-025', 'T-029'],
    mappings: [{ fqn: `${G}.FCT_SUPPLY_USAGE`, column: 'IS_SURGICAL_CASE', kind: 'filters' }, { fqn: `${G}.FCT_SUPPLY_USAGE`, column: 'COST_USD', kind: 'derives' }],
    metricRefs: ['SV_SUPPLY_CHAIN.supply_cost_per_case', 'SV_SUPPLY_CHAIN.surgical_cases'], dqRules: ['Every surgical case has supply capture', 'COST_USD ≥ 0'], dqScore: 96.9 }),
  term({ id: 'T-025', term: 'On-Contract Supply Spend', domain: 'Supply chain', owner: 'P. Tanabe', steward: 'T. Quarshie', status: 'Approved', isCde: false,
    definition: 'The share of supply and pharmacy spend bought under an active GPO or local contract on the usage date.', formula: 'On-contract spend ÷ total spend × 100',
    synonyms: ['contract compliance', 'GPO compliance'], related: ['T-024'],
    mappings: [{ fqn: `${G}.FCT_SUPPLY_USAGE`, column: 'ON_CONTRACT', kind: 'defines' }, { fqn: `${S}.SUPPLY_USAGE`, column: 'ON_CONTRACT', kind: 'defines' }],
    metricRefs: ['SV_SUPPLY_CHAIN.on_contract_pct'] }),
  term({ id: 'T-026', term: 'Care Gap', domain: 'Population health', owner: 'Dr. A. Sabbagh', steward: null, status: 'Approved', isCde: true,
    definition: 'A recommended preventive or chronic-care service (for example a cancer screening or HbA1c control) that an attributed patient is due for and has not completed in the measurement year.', formula: 'Eligible for the measure AND numerator not met by the as-of date → Open; closure rate = closed ÷ eligible',
    synonyms: ['open gap', 'gap in care', 'care gaps'], related: ['T-021', 'T-002'],
    mappings: [{ fqn: `${P}.DP_CARE_GAPS`, column: 'GAP_STATUS', kind: 'defines' }, { fqn: `${P}.DP_CARE_GAPS`, column: 'MEASURE', kind: 'derives' }],
    metricRefs: ['DP_CARE_GAPS.care_gap_closure_rate', 'DP_CARE_GAPS.open_gap_patient_pct'], dqRules: ['Measure eligibility recomputed monthly'], dqScore: 88.4 }),
  term({ id: 'T-027', term: 'Portal Enrollment', domain: 'Patient access', owner: 'L. Fontaine', steward: 'O. Pritchard', status: 'Approved', isCde: false,
    definition: 'A patient (or proxy for a minor) with an activated patient portal account.', formula: 'PORTAL_ENROLLED = TRUE',
    synonyms: ['patient portal', 'portal adoption'], related: ['T-002'],
    mappings: [{ fqn: `${G}.DIM_PATIENT`, column: 'PORTAL_ENROLLED', kind: 'defines' }, { fqn: `${S}.PATIENT`, column: 'PORTAL_ENROLLED', kind: 'defines' }],
    metricRefs: ['SV_PATIENT_REVENUE.portal_adoption_rate'] }),
  term({ id: 'T-028', term: 'A/R Aging', domain: 'Revenue cycle', owner: 'K. Kilbride', steward: 'S. Farouk', status: 'Approved', isCde: false,
    definition: 'Open receivables bucketed by days since the service (discharge) date; balances over 90 days are the main collection risk.', formula: 'DAYS_OUTSTANDING = as-of date − service date for open claims',
    synonyms: ['aged AR', 'AR over 90', 'aging bucket'], related: ['T-018'],
    mappings: [{ fqn: `${G}.FCT_CLAIM`, column: 'DAYS_OUTSTANDING', kind: 'defines' }, { fqn: `${P}.DP_PATIENT_360`, column: 'AGED_90_BALANCE', kind: 'derives' }],
    metricRefs: ['SV_PATIENT_REVENUE.ar_over_90_pct'] }),
  term({ id: 'T-029', term: 'Clinical Supply Spend', domain: 'Supply chain', owner: 'P. Tanabe', steward: 'T. Quarshie', status: 'Approved', isCde: true,
    definition: 'Cost of medical-surgical supplies, implants and pharmacy dispenses consumed on patient encounters.', formula: 'Σ COST_USD (supply + pharmacy)',
    synonyms: ['supply spend', 'supply expense'], related: ['T-024', 'T-025'],
    mappings: [{ fqn: `${G}.FCT_SUPPLY_USAGE`, column: 'COST_USD', kind: 'defines' }, { fqn: `${S}.SUPPLY_USAGE`, column: 'COST_USD', kind: 'derives' }, { fqn: `${S}.PHARMACY_DISPENSE`, column: 'COST_USD', kind: 'derives' }],
    metricRefs: ['SV_SUPPLY_CHAIN.supply_spend', 'SV_SUPPLY_CHAIN.pharmacy_spend'], dqRules: ['COST_USD ≥ 0', 'Item master match'], dqScore: 97.2 }),
  term({ id: 'T-030', term: 'Inpatient Discharge', domain: 'Hospital operations', owner: 'M. Arriaga', steward: 'O. Pritchard', status: 'Approved', isCde: false,
    definition: 'The end of an inpatient stay, counted on the discharge date. Patients still in house at the as-of date are not discharges.', formula: 'COUNT of inpatient encounters with DISCHARGE_DATE in the period',
    synonyms: ['discharges'], related: ['T-005', 'T-007'],
    mappings: [{ fqn: `${G}.FCT_ENCOUNTER`, column: 'DISCHARGE_DATE', kind: 'defines' }],
    metricRefs: ['SV_THROUGHPUT.inpatient_discharges'] }),
];
