import type { GlossaryTerm } from '../../types';

const G = 'CONFORMED_GOLD';
const P = 'DATA_PRODUCTS';
const term = (t: Omit<GlossaryTerm, 'related' | 'synonyms'> & Partial<Pick<GlossaryTerm, 'related' | 'synonyms'>>): GlossaryTerm => ({ related: [], synonyms: [], ...t });

export const GLOSSARY: GlossaryTerm[] = [
  term({ id: 'T-001', term: 'Customer', domain: 'Customer', owner: 'Retail Banking (C. Vandermeer)', steward: 'N. Pereira', status: 'Approved', isCde: true,
    definition: 'A person or business with at least one deposit, loan or card relationship with Ridgeline Bank, identified by one CIF number.', formula: 'One record per CUSTOMER_ID; the current SCD2 version represents the customer today.',
    synonyms: ['client', 'account holder', 'cif'], related: ['T-002', 'T-004'],
    mappings: [{ fqn: `${G}.DIM_CUSTOMER`, column: 'CUSTOMER_ID', kind: 'defines' }, { fqn: 'CURATED_SILVER.CUSTOMER', column: 'CUSTOMER_ID', kind: 'defines' }],
    metricRefs: [], dqRules: ['CUSTOMER_ID not null', 'CUSTOMER_ID unique where IS_CURRENT'], dqScore: 99.7 }),
  term({ id: 'T-002', term: 'Active Customer', domain: 'Customer', owner: 'Retail Banking (C. Vandermeer)', steward: 'N. Pereira', status: 'Approved', isCde: true,
    definition: 'A customer with Active status, at least one open deposit or loan account at month-end and a customer-initiated transaction or digital login in the last 90 days.', formula: "status = 'Active' AND open accounts ≥ 1 AND last activity date > as-of date − 90 days",
    synonyms: ['active relationship', 'active client'], related: ['T-001', 'T-005'],
    mappings: [{ fqn: 'CURATED_SILVER.CUSTOMER', column: 'CUSTOMER_STATUS', kind: 'filters' }, { fqn: `${G}.DIM_CUSTOMER`, column: 'LAST_ACTIVITY_DATE', kind: 'filters' }, { fqn: `${P}.DP_CUSTOMER_360`, column: 'IS_ACTIVE', kind: 'derives' }],
    metricRefs: ['SV_CUSTOMER_360.active_customers'], dqRules: ['Status in (Active, Dormant, Closed)', 'Last activity date refreshed daily'], dqScore: 98.8 }),
  term({ id: 'T-003', term: 'Market Region', domain: 'Enterprise', owner: 'Corporate Strategy (D. Hollis)', steward: 'G. Ellery', status: 'Approved', isCde: true,
    definition: 'One of Ridgeline’s four markets — Mountain, Plains, Great Lakes and Southeast — assigned from the customer’s home branch.', formula: 'Branch code prefix: MTN → Mountain, PLN → Plains, GLK → Great Lakes, SE → Southeast',
    synonyms: ['market', 'region', 'footprint'], related: ['T-001'],
    mappings: [{ fqn: `${G}.DIM_CUSTOMER`, column: 'REGION', kind: 'defines' }, { fqn: `${G}.DIM_BRANCH`, column: 'REGION', kind: 'defines' }, { fqn: `${G}.FCT_LOAN_BALANCE`, column: 'REGION', kind: 'derives' }],
    metricRefs: [], dqRules: ['REGION in reference list'], dqScore: 100 }),
  term({ id: 'T-004', term: 'Customer Segment', domain: 'Customer', owner: 'Retail Banking (C. Vandermeer)', steward: 'N. Pereira', status: 'Approved', isCde: true,
    definition: 'The service model a customer is managed under: Mass retail, Affluent (investable balances above $100,000), Small business (revenue under $10 M) or Commercial.', formula: 'Assigned monthly from relationship balances and business revenue; history kept as SCD2',
    synonyms: ['tier', 'customer type'], related: ['T-001'],
    mappings: [{ fqn: `${G}.DIM_CUSTOMER`, column: 'SEGMENT', kind: 'defines' }, { fqn: 'CURATED_SILVER.CUSTOMER', column: 'SEGMENT', kind: 'defines' }],
    metricRefs: [], dqRules: ['SEGMENT in reference list', 'One current version per customer'], dqScore: 99.5 }),
  term({ id: 'T-005', term: 'Digital Active Customer', domain: 'Customer', owner: 'Digital Banking (F. Lund)', steward: 'N. Pereira', status: 'Approved', isCde: false,
    definition: 'An active customer who signed in to the mobile app or online banking at least once in the last 30 days.', formula: 'Active customers with ≥ 1 digital session in the last 30 days ÷ active customers',
    synonyms: ['digital adoption', 'digitally active', 'online banking user'], related: ['T-002'],
    mappings: [{ fqn: `${G}.FCT_DIGITAL_SESSION`, column: 'EVENT_TYPE', kind: 'derives' }, { fqn: `${G}.DIM_CUSTOMER`, column: 'DIGITAL_ENROLLED', kind: 'filters' }],
    metricRefs: ['SV_CUSTOMER_360.digital_active_rate'] }),
  term({ id: 'T-006', term: 'Customer Attrition', domain: 'Customer', owner: 'Retail Banking (C. Vandermeer)', steward: 'N. Pereira', status: 'Approved', isCde: false,
    definition: 'Customers whose last account closed in the trailing 12 months, as a share of customers at the start of the period.', formula: 'Customers closed Oct 2025 – Sep 2026 ÷ customers open on 1 Oct 2025',
    synonyms: ['churn', 'attrition'], related: ['T-001'],
    mappings: [{ fqn: `${G}.DIM_CUSTOMER`, column: 'CLOSED_DATE', kind: 'defines' }],
    metricRefs: ['SV_CUSTOMER_360.attrition_rate'] }),
  term({ id: 'T-007', term: 'Deposit Balance', domain: 'Treasury', owner: 'Treasury (A. Delacroix)', steward: 'S. Kowalewski', status: 'Approved', isCde: true,
    definition: 'The ledger balance of a deposit account at month-end, excluding accrued interest and brokered deposits.', formula: 'LEDGER_BALANCE on the month-end snapshot',
    synonyms: ['deposits', 'balances', 'funding'], related: ['T-008', 'T-009'],
    mappings: [{ fqn: `${G}.FCT_DEPOSIT_BALANCE`, column: 'LEDGER_BALANCE', kind: 'defines' }, { fqn: 'CURATED_SILVER.DEPOSIT_ACCOUNT', column: 'LEDGER_BALANCE', kind: 'defines' }],
    metricRefs: ['SV_DEPOSITS_LIQUIDITY.total_deposits', 'SV_CUSTOMER_360.avg_deposit_balance'], dqRules: ['LEDGER_BALANCE ≥ 0', 'Reconciles to GL 2100 within 0.1%'], dqScore: 99.6 }),
  term({ id: 'T-008', term: 'Deposit Growth', domain: 'Treasury', owner: 'Treasury (A. Delacroix)', steward: 'S. Kowalewski', status: 'Approved', isCde: false,
    definition: 'The year-to-date change in month-end total deposits versus 31 December of the prior year.', formula: '(Deposits at month-end ÷ deposits at prior 31 Dec − 1) × 100',
    synonyms: ['deposit change'], related: ['T-007'],
    mappings: [{ fqn: `${G}.FCT_DEPOSIT_BALANCE`, column: 'LEDGER_BALANCE', kind: 'derives' }],
    metricRefs: ['SV_DEPOSITS_LIQUIDITY.deposit_growth_pct'] }),
  term({ id: 'T-009', term: 'Cost of Deposits', domain: 'Treasury', owner: 'Treasury (A. Delacroix)', steward: 'S. Kowalewski', status: 'Approved', isCde: true,
    definition: 'Annualised interest expense on deposits divided by average deposit balances.', formula: 'Σ monthly interest expense × 12 ÷ Σ month-end balances × 100',
    synonyms: ['deposit cost', 'cost of funds'], related: ['T-007', 'T-011'],
    mappings: [{ fqn: `${G}.FCT_DEPOSIT_BALANCE`, column: 'INTEREST_RATE', kind: 'defines' }, { fqn: `${G}.FCT_DEPOSIT_BALANCE`, column: 'INTEREST_EXPENSE', kind: 'derives' }],
    metricRefs: ['SV_DEPOSITS_LIQUIDITY.cost_of_deposits'], dqRules: ['INTEREST_RATE between 0 and 6%'], dqScore: 99.2 }),
  term({ id: 'T-010', term: 'Loan-to-Deposit Ratio', domain: 'Treasury', owner: 'Treasury (A. Delacroix)', steward: 'S. Kowalewski', status: 'Approved', isCde: true,
    definition: 'Gross loans outstanding divided by total deposits at month-end; the board limit is 95%.', formula: 'GL 1100 loans ÷ GL 2100 deposits × 100',
    synonyms: ['LDR', 'loans to deposits'], related: ['T-007', 'T-026'],
    mappings: [{ fqn: `${G}.FCT_GL_MONTHLY`, column: 'AMOUNT_USD', kind: 'derives' }],
    metricRefs: ['SV_DEPOSITS_LIQUIDITY.loan_to_deposit_ratio'], dqRules: ['GL 1100 reconciles to FCT_LOAN_BALANCE', 'GL 2100 reconciles to FCT_DEPOSIT_BALANCE'], dqScore: 99.4 }),
  term({ id: 'T-011', term: 'Net Interest Margin', domain: 'Finance', owner: 'Finance (E. Kesselring)', steward: 'S. Kowalewski', status: 'Approved', isCde: true,
    definition: 'Annualised net interest income divided by average earning assets (loans, securities and cash at the Fed).', formula: '(Interest income − interest expense) × 12 ÷ months ÷ average earning assets × 100',
    synonyms: ['NIM', 'margin'], related: ['T-009', 'T-024'],
    mappings: [{ fqn: `${G}.FCT_GL_MONTHLY`, column: 'AMOUNT_USD', kind: 'defines' }, { fqn: `${G}.FCT_GL_MONTHLY`, column: 'GL_ACCOUNT', kind: 'filters' }],
    metricRefs: ['SV_DEPOSITS_LIQUIDITY.net_interest_margin'], dqRules: ['GL closed for the period', 'Earning assets > 0'], dqScore: 99.1 }),
  term({ id: 'T-012', term: 'Non-Performing Loan', domain: 'Credit risk', owner: 'Chief Credit Office (R. Thibodeaux)', steward: 'G. Ellery', status: 'Approved', isCde: true,
    definition: 'A loan that is 90 or more days past due or has been placed on non-accrual status, whichever comes first. It stays non-performing until it is brought current and has six consecutive payments.', formula: 'DAYS_PAST_DUE ≥ 90 OR NON_ACCRUAL_FLAG = TRUE',
    synonyms: ['NPL', 'bad loan', 'non-accrual loan', 'impaired loan'], related: ['T-013', 'T-014'],
    mappings: [{ fqn: `${G}.FCT_LOAN_BALANCE`, column: 'IS_NON_PERFORMING', kind: 'defines' }, { fqn: `${G}.FCT_LOAN_BALANCE`, column: 'DAYS_PAST_DUE', kind: 'filters' }, { fqn: `${G}.FCT_LOAN_BALANCE`, column: 'NON_ACCRUAL_FLAG', kind: 'filters' }, { fqn: `${P}.DP_LOAN_PORTFOLIO`, column: 'IS_NON_PERFORMING', kind: 'derives' }],
    metricRefs: ['SV_LOAN_PORTFOLIO.npl_balance'], dqRules: ['DAYS_PAST_DUE ≥ 0', 'NON_ACCRUAL_FLAG not null', 'IS_NON_PERFORMING consistent with BR-007'], dqScore: 99.3 }),
  term({ id: 'T-013', term: 'NPL Ratio', domain: 'Credit risk', owner: 'Chief Credit Office (R. Thibodeaux)', steward: 'G. Ellery', status: 'Approved', isCde: true,
    definition: 'Non-performing loan principal divided by total loans outstanding at month-end, before the allowance.', formula: 'Σ principal where non-performing ÷ Σ principal × 100',
    synonyms: ['non-performing loan ratio', 'npl rate', 'non-performing ratio'], related: ['T-012', 'T-026', 'T-030'],
    mappings: [{ fqn: `${G}.FCT_LOAN_BALANCE`, column: 'PRINCIPAL_BALANCE', kind: 'derives' }, { fqn: `${G}.FCT_LOAN_BALANCE`, column: 'IS_NON_PERFORMING', kind: 'filters' }],
    metricRefs: ['SV_LOAN_PORTFOLIO.npl_ratio'], dqRules: ['Month-end snapshot complete for all active loans', 'Principal ≥ 0'], dqScore: 99.3 }),
  term({ id: 'T-014', term: 'Days Past Due', domain: 'Credit risk', owner: 'Chief Credit Office (R. Thibodeaux)', steward: 'G. Ellery', status: 'Approved', isCde: true,
    definition: 'Calendar days since the oldest unpaid scheduled payment was due. 30+ DPD is the early-delinquency measure.', formula: 'Month-end date − oldest unpaid due date',
    synonyms: ['DPD', 'delinquency', 'past due'], related: ['T-012'],
    mappings: [{ fqn: `${G}.FCT_LOAN_BALANCE`, column: 'DAYS_PAST_DUE', kind: 'defines' }, { fqn: 'CURATED_SILVER.LOAN_ACCOUNT', column: 'DAYS_PAST_DUE', kind: 'defines' }],
    metricRefs: ['SV_LOAN_PORTFOLIO.delinquency_30_plus_rate'], dqRules: ['0 ≤ DPD ≤ 999'], dqScore: 99.0 }),
  term({ id: 'T-015', term: 'Net Charge-Off', domain: 'Credit risk', owner: 'Chief Credit Office (R. Thibodeaux)', steward: 'G. Ellery', status: 'Approved', isCde: true,
    definition: 'Loan balances written off as uncollectible, net of recoveries, in the period. The ratio is annualised over average loans.', formula: 'Σ net charge-offs × 12 ÷ months ÷ average loans × 100',
    synonyms: ['NCO', 'charge-off', 'write-off'], related: ['T-016'],
    mappings: [{ fqn: `${G}.FCT_LOAN_BALANCE`, column: 'NET_CHARGE_OFF', kind: 'defines' }],
    metricRefs: ['SV_LOAN_PORTFOLIO.net_charge_off_ratio'], dqRules: ['NET_CHARGE_OFF ≥ 0'], dqScore: 98.9 }),
  term({ id: 'T-016', term: 'Allowance for Credit Losses', domain: 'Credit risk', owner: 'Chief Credit Office (R. Thibodeaux)', steward: 'G. Ellery', status: 'Approved', isCde: true,
    definition: 'The CECL reserve held against expected lifetime credit losses. Coverage compares it with non-performing loans.', formula: 'Allowance ÷ non-performing loans × 100',
    synonyms: ['ACL', 'CECL reserve', 'loan loss reserve'], related: ['T-012', 'T-015'],
    mappings: [{ fqn: `${G}.FCT_LOAN_BALANCE`, column: 'ALLOWANCE_AMOUNT', kind: 'defines' }],
    metricRefs: ['SV_LOAN_PORTFOLIO.allowance_coverage_ratio'], dqRules: ['ALLOWANCE_AMOUNT ≥ 0', 'Ties to GL reserve account'], dqScore: 98.6 }),
  term({ id: 'T-017', term: 'Liquidity Coverage Ratio', domain: 'Treasury', owner: 'Treasury (A. Delacroix)', steward: 'S. Kowalewski', status: 'Approved', isCde: true,
    definition: 'High-quality liquid assets divided by total net cash outflows over a 30-day stress period (Basel III). Internal floor 110%.', formula: 'HQLA ÷ 30-day stressed net cash outflows × 100',
    synonyms: ['LCR', 'liquidity coverage'], related: ['T-007'],
    mappings: [{ fqn: `${G}.FCT_DEPOSIT_BALANCE`, column: 'LCR_RUNOFF_RATE', kind: 'derives' }, { fqn: `${G}.FCT_GL_MONTHLY`, column: 'AMOUNT_USD', kind: 'derives' }],
    metricRefs: ['SV_DEPOSITS_LIQUIDITY.liquidity_coverage_ratio', 'SV_DEPOSITS_LIQUIDITY.stressed_outflows'], dqRules: ['Runoff rate assigned for every deposit product'], dqScore: 98.7 }),
  term({ id: 'T-018', term: 'Loan Yield', domain: 'Credit risk', owner: 'Finance (E. Kesselring)', steward: 'S. Kowalewski', status: 'Approved', isCde: false,
    definition: 'The balance-weighted note rate on loans outstanding.', formula: 'Σ principal × note rate ÷ Σ principal',
    synonyms: ['loan rate'], related: ['T-011'],
    mappings: [{ fqn: `${G}.FCT_LOAN_BALANCE`, column: 'INTEREST_RATE', kind: 'defines' }],
    metricRefs: ['SV_LOAN_PORTFOLIO.loan_yield'] }),
  term({ id: 'T-019', term: 'Card Fraud Loss', domain: 'Cards', owner: 'Card Services (L. Ferreira-Holt)', steward: 'P. Agbaje', status: 'Approved', isCde: true,
    definition: 'Confirmed card fraud losses net of chargeback recoveries, expressed in basis points of approved purchase volume.', formula: 'Σ fraud loss ÷ Σ approved purchase volume × 10,000',
    synonyms: ['fraud bps', 'fraud loss rate', 'card fraud'], related: ['T-020', 'T-031'],
    mappings: [{ fqn: `${G}.FCT_CARD_TRANSACTION`, column: 'FRAUD_LOSS_USD', kind: 'defines' }, { fqn: `${G}.FCT_CARD_TRANSACTION`, column: 'IS_CONFIRMED_FRAUD', kind: 'filters' }],
    metricRefs: ['SV_CUSTOMER_360.card_fraud_loss_bps'], dqRules: ['FRAUD_LOSS_USD ≤ AMOUNT_USD', 'Fraud confirmed within 60 days'], dqScore: 98.2 }),
  term({ id: 'T-020', term: 'Authorization Approval Rate', domain: 'Cards', owner: 'Card Services (L. Ferreira-Holt)', steward: 'P. Agbaje', status: 'Approved', isCde: false,
    definition: 'The share of card authorisation requests approved by the issuer.', formula: 'Approved authorisations ÷ all authorisations × 100',
    synonyms: ['approval rate', 'auth rate'], related: ['T-019'],
    mappings: [{ fqn: `${G}.FCT_CARD_TRANSACTION`, column: 'IS_APPROVED', kind: 'defines' }],
    metricRefs: ['SV_CUSTOMER_360.auth_approval_rate'] }),
  term({ id: 'T-021', term: 'AML Alert', domain: 'Financial crimes', owner: 'BSA/AML Officer (M. Quint)', steward: 'J. Rahman', status: 'Approved', isCde: true,
    definition: 'A transaction-monitoring hit on a customer or account that an investigator must review and disposition.', formula: 'One row per alert in FCT_AML_ALERT; disposition date − alert date = days to disposition',
    synonyms: ['alert', 'tm alert', 'monitoring alert'], related: ['T-022', 'T-023'],
    mappings: [{ fqn: `${G}.FCT_AML_ALERT`, column: 'DISPOSITION', kind: 'defines' }, { fqn: `${G}.FCT_AML_ALERT`, column: 'DAYS_TO_DISPOSITION', kind: 'derives' }, { fqn: 'CURATED_SILVER.AML_ALERT', column: 'ALERT_DATE', kind: 'defines' }],
    metricRefs: ['SV_AML_ALERTS.alerts_raised', 'SV_AML_ALERTS.avg_days_to_disposition'], dqRules: ['Every alert has a scenario', 'Disposition date ≥ alert date'], dqScore: 96.4 }),
  term({ id: 'T-022', term: 'Alert-to-Case Rate', domain: 'Financial crimes', owner: 'BSA/AML Officer (M. Quint)', steward: 'J. Rahman', status: 'Approved', isCde: true,
    definition: 'The share of dispositioned AML alerts escalated to an investigation case. Open alerts are excluded from the denominator.', formula: 'Alerts escalated to case ÷ alerts dispositioned × 100',
    synonyms: ['escalation rate', 'productive alert rate', 'aml case', 'escalated alert'], related: ['T-021', 'T-023'],
    mappings: [{ fqn: `${G}.FCT_AML_ALERT`, column: 'IS_ESCALATED', kind: 'defines' }, { fqn: `${G}.FCT_AML_ALERT`, column: 'DISPOSITION', kind: 'filters' }],
    metricRefs: ['SV_AML_ALERTS.alert_to_case_rate'], dqRules: ['CASE_ID present when IS_ESCALATED'], dqScore: 96.9 }),
  term({ id: 'T-023', term: 'Suspicious Activity Report', domain: 'Financial crimes', owner: 'BSA/AML Officer (M. Quint)', steward: 'J. Rahman', status: 'Approved', isCde: true,
    definition: 'A report filed with FinCEN when an investigation concludes activity is suspicious; due within 30 calendar days of initial detection.', formula: 'SAR conversion = SARs filed ÷ closed cases × 100',
    synonyms: ['SAR', 'SAR filing'], related: ['T-022'],
    mappings: [{ fqn: `${G}.FCT_AML_ALERT`, column: 'SAR_FILED', kind: 'defines' }],
    metricRefs: ['SV_AML_ALERTS.sar_conversion_rate'], dqRules: ['SAR_FILED only where CASE_ID present'], dqScore: 97.8 }),
  term({ id: 'T-024', term: 'Cost-to-Income Ratio', domain: 'Finance', owner: 'Finance (E. Kesselring)', steward: 'S. Kowalewski', status: 'Approved', isCde: true,
    definition: 'Non-interest expense divided by total revenue (net interest income plus non-interest income); also called the efficiency ratio.', formula: 'GL 6000 ÷ (net interest income + GL 4500) × 100',
    synonyms: ['efficiency ratio', 'cost income ratio'], related: ['T-011'],
    mappings: [{ fqn: `${G}.FCT_GL_MONTHLY`, column: 'AMOUNT_USD', kind: 'derives' }, { fqn: `${G}.FCT_GL_MONTHLY`, column: 'LINE_TYPE', kind: 'filters' }],
    metricRefs: ['SV_DEPOSITS_LIQUIDITY.cost_to_income_ratio'], dqRules: ['Expense lines mapped to GL 6000'], dqScore: 98.8 }),
  term({ id: 'T-025', term: 'Customer Net Contribution', domain: 'Finance', owner: 'Finance (E. Kesselring)', steward: null, status: 'Approved', isCde: true,
    definition: 'Trailing 12-month revenue from a customer (deposit and loan spread after funds transfer pricing, interchange and fees) minus cost to serve and expected credit loss.', formula: 'Deposit spread + loan spread + interchange + fees − cost to serve − expected credit loss',
    synonyms: ['customer profitability', 'customer profit', 'net contribution'], related: ['T-028', 'T-016'],
    mappings: [{ fqn: `${P}.DP_CUSTOMER_PROFITABILITY`, column: 'NET_CONTRIBUTION_12M', kind: 'defines' }, { fqn: `${P}.DP_CUSTOMER_PROFITABILITY`, column: 'IS_UNPROFITABLE', kind: 'derives' }],
    metricRefs: ['DP_CUSTOMER_PROFITABILITY.avg_net_contribution', 'DP_CUSTOMER_PROFITABILITY.unprofitable_share'], dqRules: ['FTP curve loaded for the month'], dqScore: 90.6 }),
  term({ id: 'T-026', term: 'Loans Outstanding', domain: 'Credit risk', owner: 'Chief Credit Office (R. Thibodeaux)', steward: 'G. Ellery', status: 'Approved', isCde: true,
    definition: 'Unpaid principal on all funded loans at month-end, before the allowance and excluding unfunded commitments.', formula: 'Σ PRINCIPAL_BALANCE at month-end',
    synonyms: ['loan book', 'gross loans', 'total loans'], related: ['T-013', 'T-030'],
    mappings: [{ fqn: `${G}.FCT_LOAN_BALANCE`, column: 'PRINCIPAL_BALANCE', kind: 'defines' }, { fqn: 'CURATED_SILVER.LOAN_ACCOUNT', column: 'PRINCIPAL_BALANCE', kind: 'defines' }],
    metricRefs: ['SV_LOAN_PORTFOLIO.total_loans'], dqRules: ['PRINCIPAL_BALANCE ≥ 0', 'Reconciles to GL 1100 within 0.1%'], dqScore: 99.6 }),
  term({ id: 'T-027', term: 'Average Ticket', domain: 'Cards', owner: 'Card Services (L. Ferreira-Holt)', steward: 'P. Agbaje', status: 'Approved', isCde: false,
    definition: 'The average amount of an approved card purchase.', formula: 'Approved purchase volume ÷ approved transactions',
    synonyms: ['ticket size', 'average purchase'], related: ['T-031'],
    mappings: [{ fqn: `${G}.FCT_CARD_TRANSACTION`, column: 'AMOUNT_USD', kind: 'derives' }],
    metricRefs: ['SV_CUSTOMER_360.avg_ticket'] }),
  term({ id: 'T-028', term: 'Cost to Serve', domain: 'Finance', owner: 'Finance (E. Kesselring)', steward: 'S. Kowalewski', status: 'Draft', isCde: false,
    definition: 'Operating cost allocated to a customer from branch, contact-centre, digital and servicing activity. Draft: activity-based allocation keys under review with Finance.', formula: 'Segment base cost + per-product servicing cost',
    synonyms: ['servicing cost', 'allocated cost'], related: ['T-025'],
    mappings: [{ fqn: `${P}.DP_CUSTOMER_PROFITABILITY`, column: 'COST_TO_SERVE', kind: 'defines' }],
    metricRefs: ['DP_CUSTOMER_PROFITABILITY.avg_net_contribution'] }),
  term({ id: 'T-029', term: 'Products per Customer', domain: 'Customer', owner: 'Retail Banking (C. Vandermeer)', steward: 'N. Pereira', status: 'Approved', isCde: false,
    definition: 'Average number of open deposit accounts, loans and cards held by an active customer.', formula: 'Σ open products ÷ active customers',
    synonyms: ['cross-sell ratio', 'products held'], related: ['T-002'],
    mappings: [{ fqn: `${P}.DP_CUSTOMER_360`, column: 'PRODUCTS_HELD', kind: 'defines' }],
    metricRefs: ['SV_CUSTOMER_360.products_per_customer'] }),
  term({ id: 'T-030', term: 'Loan Segment', domain: 'Credit risk', owner: 'Chief Credit Office (R. Thibodeaux)', steward: 'G. Ellery', status: 'Approved', isCde: true,
    definition: 'The regulatory call-report grouping of a loan: Commercial real estate, Commercial & industrial, Residential mortgage, Home equity, or Consumer & auto.', formula: 'Mapped from the core product code (CRE, CI, RESI, HELOC, CONS)',
    synonyms: ['loan type', 'portfolio', 'asset class'], related: ['T-013', 'T-026'],
    mappings: [{ fqn: `${G}.FCT_LOAN_BALANCE`, column: 'LOAN_SEGMENT', kind: 'defines' }, { fqn: 'CURATED_SILVER.LOAN_ACCOUNT', column: 'LOAN_SEGMENT', kind: 'defines' }],
    metricRefs: [], dqRules: ['LOAN_SEGMENT in reference list'], dqScore: 100 }),
  term({ id: 'T-031', term: 'Card Purchase Volume', domain: 'Cards', owner: 'Card Services (L. Ferreira-Holt)', steward: 'P. Agbaje', status: 'Approved', isCde: false,
    definition: 'The dollar value of approved card purchases in the period, excluding cash advances and balance transfers.', formula: 'Σ AMOUNT_USD where IS_APPROVED',
    synonyms: ['card spend', 'purchase volume', 'card sales'], related: ['T-019', 'T-027'],
    mappings: [{ fqn: `${G}.FCT_CARD_TRANSACTION`, column: 'AMOUNT_USD', kind: 'defines' }],
    metricRefs: ['SV_CUSTOMER_360.card_purchase_volume'] }),
];
