import type { GlossaryTerm } from '../../types';

const G = 'CONFORMED_GOLD';
const S = 'CURATED_SILVER';
const term = (t: Omit<GlossaryTerm, 'related' | 'synonyms'> & Partial<Pick<GlossaryTerm, 'related' | 'synonyms'>>): GlossaryTerm => ({ related: [], synonyms: [], ...t });

export const GLOSSARY: GlossaryTerm[] = [
  term({ id: 'T-001', term: 'Subscriber', domain: 'Subscriber', owner: 'K. Albright', steward: 'R. Mensah', status: 'Approved', isCde: true,
    definition: 'A mobile line or broadband home with a service agreement on one billing account. One account can hold several subscribers.', formula: 'One record per SUBSCRIBER_ID; the current SCD2 version represents the subscriber today.',
    synonyms: ['line', 'customer line', 'connection'], related: ['T-002', 'T-019'],
    mappings: [{ fqn: `${G}.DIM_SUBSCRIBER`, column: 'SUBSCRIBER_ID', kind: 'defines' }, { fqn: `${S}.SUBSCRIBER`, column: 'SUBSCRIBER_ID', kind: 'defines' }],
    metricRefs: [], dqRules: ['SUBSCRIBER_ID not null', 'SUBSCRIBER_ID unique where IS_CURRENT'], dqScore: 99.7 }),
  term({ id: 'T-002', term: 'Active Subscriber', domain: 'Subscriber', owner: 'K. Albright', steward: 'R. Mensah', status: 'Approved', isCde: true,
    definition: 'A subscriber whose status is Active and who was invoiced in the latest closed month. Dormant prepaid lines without a recent top-up are excluded.', formula: "status = 'Active' AND invoice in the latest closed month",
    synonyms: ['active line', 'active subscriber base'], related: ['T-001', 'T-027'],
    mappings: [{ fqn: `${S}.SUBSCRIBER`, column: 'STATUS', kind: 'filters' }, { fqn: `${G}.FCT_BILLING`, column: 'DATE_KEY', kind: 'filters' }, { fqn: 'DATA_PRODUCTS.DP_SUBSCRIBER_360', column: 'IS_ACTIVE', kind: 'derives' }],
    metricRefs: ['SV_SUBSCRIBER_360.active_subscribers'], dqRules: ['STATUS in (Active, Disconnected)', 'Invoice recency computed daily'], dqScore: 98.8 }),
  term({ id: 'T-003', term: 'Region', domain: 'Enterprise', owner: 'Corporate Strategy (E. Navarro)', steward: 'T. Herrera', status: 'Approved', isCde: true,
    definition: 'One of Altair’s four operating regions — Northeast, Southeast, Central and West — each made up of two markets.', formula: 'Derived from market code: HBV/GRV → Northeast, PLC/MGB → Southeast, PRX/LKS → Central, SRV/PCR → West',
    synonyms: ['territory', 'operating region'], related: ['T-016'],
    mappings: [{ fqn: `${G}.DIM_MARKET`, column: 'REGION', kind: 'defines' }, { fqn: `${G}.DIM_SUBSCRIBER`, column: 'REGION', kind: 'derives' }, { fqn: `${G}.FCT_SUBSCRIBER_MONTHLY`, column: 'REGION', kind: 'derives' }],
    metricRefs: [], dqRules: ['REGION in reference list', 'Every market maps to exactly one region'], dqScore: 100 }),
  term({ id: 'T-004', term: 'Churn Rate', domain: 'Subscriber', owner: 'K. Albright', steward: 'R. Mensah', status: 'Approved', isCde: true,
    definition: 'The share of subscribers at the start of a month who left during the month. Churn counts voluntary disconnects and port-outs; plan migrations are excluded, and involuntary (non-pay) disconnects are reported separately.', formula: '(voluntary disconnects + port-outs) ÷ opening base × 100, per month',
    synonyms: ['churn', 'attrition', 'disconnect rate'], related: ['T-005', 'T-006', 'T-025', 'T-007'],
    mappings: [{ fqn: `${G}.FCT_SUBSCRIBER_MONTHLY`, column: 'VOLUNTARY_DISCONNECTS', kind: 'derives' }, { fqn: `${G}.FCT_SUBSCRIBER_MONTHLY`, column: 'PORT_OUTS', kind: 'derives' }, { fqn: `${G}.FCT_SUBSCRIBER_MONTHLY`, column: 'OPENING_BASE', kind: 'derives' }, { fqn: `${G}.FCT_SUBSCRIBER_MONTHLY`, column: 'MIGRATIONS_OUT', kind: 'filters' }],
    metricRefs: ['SV_CHURN_RETENTION.postpaid_churn_rate', 'SV_CHURN_RETENTION.prepaid_churn_rate', 'SV_CHURN_RETENTION.broadband_churn_rate'], dqRules: ['OPENING_BASE > 0', 'Disconnect reason present on every disconnect', 'Plan changes never coded as disconnects'], dqScore: 99.3 }),
  term({ id: 'T-005', term: 'Port-Out', domain: 'Subscriber', owner: 'K. Albright', steward: 'R. Mensah', status: 'Approved', isCde: true,
    definition: 'A disconnect where the subscriber moved their number to another carrier through number portability.', formula: 'Disconnect with a completed port request (IS_PORT_OUT = TRUE)',
    synonyms: ['port out', 'ported number', 'competitive loss'], related: ['T-004'],
    mappings: [{ fqn: `${G}.FCT_SUBSCRIBER_MONTHLY`, column: 'PORT_OUTS', kind: 'defines' }, { fqn: `${S}.SUBSCRIBER_EVENT`, column: 'IS_PORT_OUT', kind: 'defines' }],
    metricRefs: ['SV_CHURN_RETENTION.port_out_share'], dqRules: ['Port completion timestamp present'], dqScore: 99.1 }),
  term({ id: 'T-006', term: 'Plan Migration', domain: 'Subscriber', owner: 'K. Albright', steward: 'R. Mensah', status: 'Approved', isCde: true,
    definition: 'A subscriber moving from one rate plan to another within the same line of business. A migration is not churn: the subscriber stays with Altair.', formula: 'PLAN_CHANGE event; counted as MIGRATIONS_OUT on the old plan and MIGRATIONS_IN on the new plan',
    synonyms: ['plan change', 'migration', 'upgrade', 'downgrade'], related: ['T-004', 'T-012'],
    mappings: [{ fqn: `${G}.FCT_SUBSCRIBER_MONTHLY`, column: 'MIGRATIONS_OUT', kind: 'defines' }, { fqn: `${G}.FCT_SUBSCRIBER_MONTHLY`, column: 'MIGRATIONS_IN', kind: 'defines' }, { fqn: `${S}.SUBSCRIBER_EVENT`, column: 'IS_PLAN_MIGRATION', kind: 'defines' }],
    metricRefs: ['SV_CHURN_RETENTION.plan_migrations'], dqRules: ['Migrations in = migrations out per segment and month'], dqScore: 100 }),
  term({ id: 'T-007', term: 'Net Adds', domain: 'Subscriber', owner: 'K. Albright', steward: 'R. Mensah', status: 'Approved', isCde: true,
    definition: 'Net change in the subscriber base: gross adds minus all disconnects (voluntary, port-out and involuntary). Plan migrations net to zero.', formula: 'gross adds − (voluntary + port-outs + involuntary disconnects)',
    synonyms: ['net additions', 'net growth'], related: ['T-008', 'T-004'],
    mappings: [{ fqn: `${G}.FCT_SUBSCRIBER_MONTHLY`, column: 'GROSS_ADDS', kind: 'derives' }, { fqn: `${G}.FCT_SUBSCRIBER_MONTHLY`, column: 'INVOLUNTARY_DISCONNECTS', kind: 'derives' }],
    metricRefs: ['SV_CHURN_RETENTION.net_adds'], dqRules: ['Opening + movements = closing base'], dqScore: 99.6 }),
  term({ id: 'T-008', term: 'Gross Adds', domain: 'Subscriber', owner: 'K. Albright', steward: 'R. Mensah', status: 'Approved', isCde: false,
    definition: 'New subscriber connections activated in the period, including port-ins. Reactivations within 30 days are not gross adds.', formula: 'Σ GROSS_ADDS',
    synonyms: ['gross additions', 'activations', 'new lines'], related: ['T-007'],
    mappings: [{ fqn: `${G}.FCT_SUBSCRIBER_MONTHLY`, column: 'GROSS_ADDS', kind: 'defines' }],
    metricRefs: ['SV_CHURN_RETENTION.gross_adds'] }),
  term({ id: 'T-009', term: 'ARPU', domain: 'Revenue', owner: 'L. Duarte', steward: 'J. Whitfield', status: 'Approved', isCde: true,
    definition: 'Average revenue per user: monthly service revenue per postpaid subscriber. Device installments and one-off fees are excluded; roaming and overage are included.', formula: 'Σ postpaid service revenue in the month ÷ postpaid subscribers invoiced in the month',
    synonyms: ['average revenue per user', 'revenue per subscriber'], related: ['T-010', 'T-028'],
    mappings: [{ fqn: `${G}.FCT_BILLING`, column: 'SERVICE_REVENUE', kind: 'derives' }, { fqn: 'DATA_PRODUCTS.DP_SUBSCRIBER_360', column: 'ARPU_Q3', kind: 'derives' }],
    metricRefs: ['SV_SUBSCRIBER_360.postpaid_arpu'], dqRules: ['SERVICE_REVENUE ≥ 0', 'One invoice per subscriber per month'], dqScore: 99.2 }),
  term({ id: 'T-010', term: 'Service Revenue', domain: 'Revenue', owner: 'L. Duarte', steward: 'J. Whitfield', status: 'Approved', isCde: true,
    definition: 'Billed recurring and usage revenue from plans, overage and roaming, net of revenue leakage. Excludes device and equipment revenue.', formula: 'Σ SERVICE_REVENUE (= rated amount − leakage)',
    synonyms: ['billed revenue', 'recurring revenue'], related: ['T-009', 'T-017'],
    mappings: [{ fqn: `${G}.FCT_BILLING`, column: 'SERVICE_REVENUE', kind: 'defines' }, { fqn: `${S}.INVOICE`, column: 'BILLED_AMOUNT', kind: 'derives' }],
    metricRefs: ['SV_SUBSCRIBER_360.service_revenue'], dqRules: ['Reconciles to the general ledger within 0.1%'], dqScore: 99.5 }),
  term({ id: 'T-011', term: 'Data Usage', domain: 'Usage', owner: 'S. Varga', steward: 'P. Okonkwo', status: 'Approved', isCde: false,
    definition: 'Mobile data consumed by a subscriber, in gigabytes, from mediated data CDRs (domestic and roaming).', formula: 'Σ DATA_GB per subscriber per month',
    synonyms: ['data consumption', 'gb used', 'data volume'], related: ['T-026'],
    mappings: [{ fqn: `${G}.FCT_DAILY_USAGE`, column: 'DATA_GB', kind: 'defines' }, { fqn: `${S}.USAGE_EVENT`, column: 'VOLUME_MB', kind: 'derives' }],
    metricRefs: ['SV_SUBSCRIBER_360.data_gb_per_sub', 'SV_NETWORK_PERFORMANCE.data_traffic_pb'] }),
  term({ id: 'T-012', term: 'Rate Plan', domain: 'Subscriber', owner: 'Pricing (A. Ferreira)', steward: 'R. Mensah', status: 'Approved', isCde: true,
    definition: 'The commercial plan a subscriber is billed under: Unlimited Max, Unlimited Plus, Essentials 15GB and Family Share (postpaid); Prepaid Flex and Prepaid Basic; Fiber 500 and Fiber Gig (broadband).', formula: 'Mapped from CRM PLAN_CD',
    synonyms: ['plan', 'tariff', 'price plan'], related: ['T-006'],
    mappings: [{ fqn: `${G}.DIM_PLAN`, column: 'PLAN_CODE', kind: 'defines' }, { fqn: `${G}.DIM_SUBSCRIBER`, column: 'PLAN_CODE', kind: 'derives' }],
    metricRefs: [], dqRules: ['PLAN_CODE in plan catalogue'], dqScore: 100 }),
  term({ id: 'T-013', term: 'Dropped Call Rate', domain: 'Network', owner: 'S. Varga', steward: 'P. Okonkwo', status: 'Approved', isCde: true,
    definition: 'The share of established voice calls that end abnormally because of the network rather than either party hanging up.', formula: 'Σ dropped calls ÷ Σ call attempts × 100',
    synonyms: ['dcr', 'call drop rate', 'drop rate'], related: ['T-015', 'T-016'],
    mappings: [{ fqn: `${G}.FCT_NETWORK_DAILY`, column: 'DROPPED_CALLS', kind: 'derives' }, { fqn: `${G}.FCT_NETWORK_DAILY`, column: 'CALL_ATTEMPTS', kind: 'derives' }],
    metricRefs: ['SV_NETWORK_PERFORMANCE.dropped_call_rate'], dqRules: ['DROPPED_CALLS ≤ CALL_ATTEMPTS', 'Counters present for every site-day'], dqScore: 99.4 }),
  term({ id: 'T-014', term: 'Network Availability', domain: 'Network', owner: 'S. Varga', steward: 'P. Okonkwo', status: 'Approved', isCde: true,
    definition: 'The share of site-minutes in which a cell site was in service. Planned maintenance inside an agreed window is excluded.', formula: '100 − Σ downtime minutes ÷ (site-days × 1,440) × 100',
    synonyms: ['availability', 'uptime'], related: ['T-029', 'T-016'],
    mappings: [{ fqn: `${G}.FCT_NETWORK_DAILY`, column: 'DOWNTIME_MIN', kind: 'derives' }, { fqn: `${S}.NETWORK_EVENT`, column: 'OUTAGE_MIN', kind: 'derives' }],
    metricRefs: ['SV_NETWORK_PERFORMANCE.network_availability'], dqRules: ['DOWNTIME_MIN between 0 and 1,440'], dqScore: 99.6 }),
  term({ id: 'T-015', term: 'Call Setup Success Rate', domain: 'Network', owner: 'S. Varga', steward: 'P. Okonkwo', status: 'Approved', isCde: false,
    definition: 'The share of call attempts that the network set up successfully.', formula: '100 − Σ setup failures ÷ Σ call attempts × 100',
    synonyms: ['cssr', 'setup success'], related: ['T-013'],
    mappings: [{ fqn: `${G}.FCT_NETWORK_DAILY`, column: 'SETUP_FAILURES', kind: 'derives' }],
    metricRefs: ['SV_NETWORK_PERFORMANCE.call_setup_success_rate'] }),
  term({ id: 'T-016', term: 'Cell Site', domain: 'Network', owner: 'S. Varga', steward: 'P. Okonkwo', status: 'Approved', isCde: true,
    definition: 'A physical radio location (macro tower or small cell) identified by SITE_ID and assigned to one market.', formula: 'One record per SITE_ID',
    synonyms: ['site', 'tower', 'cell'], related: ['T-013', 'T-014'],
    mappings: [{ fqn: `${G}.DIM_CELL_SITE`, column: 'SITE_ID', kind: 'defines' }],
    metricRefs: [], dqRules: ['SITE_ID unique', 'Every site has a market'], dqScore: 100 }),
  term({ id: 'T-017', term: 'Revenue Leakage', domain: 'Revenue', owner: 'L. Duarte', steward: 'J. Whitfield', status: 'Approved', isCde: true,
    definition: 'Charges the rating engine computed but that never reached an invoice — for example usage rated against a closed account or a missing price plan mapping.', formula: 'Σ (rated amount − billed amount) ÷ Σ rated amount × 100',
    synonyms: ['leakage', 'unbilled usage', 'billing leakage'], related: ['T-018', 'T-010'],
    mappings: [{ fqn: `${G}.FCT_BILLING`, column: 'LEAKAGE_AMOUNT', kind: 'defines' }, { fqn: `${G}.FCT_BILLING`, column: 'RATED_AMOUNT', kind: 'derives' }],
    metricRefs: ['SV_SUBSCRIBER_360.revenue_leakage_pct', 'SV_SUBSCRIBER_360.leakage_amount'], dqRules: ['LEAKAGE_AMOUNT between 0 and RATED_AMOUNT'], dqScore: 98.1 }),
  term({ id: 'T-018', term: 'Rated Usage', domain: 'Revenue', owner: 'L. Duarte', steward: 'J. Whitfield', status: 'Approved', isCde: true,
    definition: 'The charge the rating engine computes for a subscriber’s plan and usage before invoicing; the reference amount for revenue assurance.', formula: 'Σ RATED_AMOUNT per invoice',
    synonyms: ['rated amount', 'rated charges'], related: ['T-017'],
    mappings: [{ fqn: `${G}.FCT_BILLING`, column: 'RATED_AMOUNT', kind: 'defines' }, { fqn: `${S}.INVOICE`, column: 'RATED_AMOUNT', kind: 'defines' }],
    metricRefs: [], dqRules: ['RATED_AMOUNT ≥ BILLED_AMOUNT'], dqScore: 99.0 }),
  term({ id: 'T-019', term: 'MSISDN', domain: 'Subscriber', owner: 'Privacy Office (G. Albrecht)', steward: 'T. Herrera', status: 'Approved', isCde: true,
    definition: 'The subscriber’s mobile number in E.164 format. It is customer proprietary network information (CPNI) and must be masked for every role except the data steward.', formula: 'E.164 string, one per mobile line',
    synonyms: ['mobile number', 'phone number'], related: ['T-024', 'T-001'],
    mappings: [{ fqn: `${G}.DIM_SUBSCRIBER`, column: 'MSISDN', kind: 'defines' }, { fqn: `${S}.SUBSCRIBER`, column: 'MSISDN', kind: 'defines' }],
    metricRefs: [], dqRules: ['E.164 format', 'Unique among active mobile lines'], dqScore: 99.9 }),
  term({ id: 'T-020', term: 'Churn Propensity Score', domain: 'Subscriber', owner: 'K. Albright', steward: 'R. Mensah', status: 'Draft', isCde: false,
    definition: 'Model score (0–100) estimating the likelihood a subscriber leaves in the next 90 days. Draft: model card and bias review pending.', formula: 'Gradient-boosted model over tenure, contract status, dropped calls, bill shock and care contacts',
    synonyms: ['churn propensity', 'churn risk', 'churn score'], related: ['T-004'],
    mappings: [{ fqn: `${G}.DIM_SUBSCRIBER`, column: 'CHURN_PROPENSITY', kind: 'defines' }],
    metricRefs: ['SV_SUBSCRIBER_360.avg_churn_propensity'] }),
  term({ id: 'T-021', term: 'First-Time Fix', domain: 'Field service', owner: 'M. Castellanos', steward: null, status: 'Approved', isCde: true,
    definition: 'A work order resolved on the first technician visit, with no repeat visit for the same fault within 30 days.', formula: 'Work orders with FIRST_TIME_FIX = TRUE ÷ closed work orders × 100',
    synonyms: ['first time fix', 'ftf', 'fixed first time'], related: ['T-031'],
    mappings: [{ fqn: `${S}.WORK_ORDER`, column: 'FIRST_TIME_FIX', kind: 'defines' }, { fqn: 'DATA_PRODUCTS.DP_FIELD_SERVICE_EFFICIENCY', column: 'FIRST_TIME_FIX', kind: 'defines' }],
    metricRefs: ['DP_FIELD_SERVICE_EFFICIENCY.first_time_fix_rate'], dqRules: ['Repeat visit window = 30 days'], dqScore: 92.4 }),
  term({ id: 'T-022', term: 'Plan Gross Margin', domain: 'Revenue', owner: 'L. Duarte', steward: 'J. Whitfield', status: 'Approved', isCde: true,
    definition: 'Service revenue less cost of service (network, interconnect, support) and amortised device subsidy, for a plan or subscriber.', formula: '(service revenue − cost of service − device subsidy) ÷ service revenue × 100',
    synonyms: ['gross margin', 'plan margin', 'margin'], related: ['T-023', 'T-010'],
    mappings: [{ fqn: `${G}.FCT_BILLING`, column: 'COST_OF_SERVICE', kind: 'derives' }, { fqn: `${G}.FCT_BILLING`, column: 'SERVICE_REVENUE', kind: 'derives' }, { fqn: 'DATA_PRODUCTS.DP_DEVICE_PLAN_PROFITABILITY', column: 'GROSS_MARGIN', kind: 'defines' }],
    metricRefs: ['SV_DEVICE_PLAN_PROFITABILITY.plan_gross_margin_pct', 'SV_DEVICE_PLAN_PROFITABILITY.margin_per_subscriber'], dqRules: ['COST_OF_SERVICE allocated for every invoice'], dqScore: 96.9 }),
  term({ id: 'T-023', term: 'Device Subsidy', domain: 'Revenue', owner: 'L. Duarte', steward: 'J. Whitfield', status: 'Approved', isCde: false,
    definition: 'The difference between a handset’s cost and what the subscriber pays for it, amortised monthly over the device agreement.', formula: 'Σ DEVICE_SUBSIDY per month',
    synonyms: ['handset subsidy', 'subsidy'], related: ['T-022'],
    mappings: [{ fqn: `${G}.FCT_BILLING`, column: 'DEVICE_SUBSIDY', kind: 'defines' }],
    metricRefs: ['SV_DEVICE_PLAN_PROFITABILITY.device_subsidy_per_sub'] }),
  term({ id: 'T-024', term: 'CPNI', domain: 'Privacy', owner: 'Privacy Office (G. Albrecht)', steward: 'T. Herrera', status: 'Approved', isCde: false,
    definition: 'Customer proprietary network information: what services a subscriber uses, how and when — numbers called, call times, location and usage. Access is limited and every use is logged.', formula: 'Columns tagged CPNI carry MP_MASK_CPNI',
    synonyms: ['customer proprietary network information'], related: ['T-019'],
    mappings: [{ fqn: `${G}.DIM_SUBSCRIBER`, column: 'MSISDN', kind: 'filters' }, { fqn: `${S}.USAGE_EVENT`, column: 'MSISDN', kind: 'filters' }],
    metricRefs: [] }),
  term({ id: 'T-025', term: 'Voluntary Disconnect', domain: 'Subscriber', owner: 'K. Albright', steward: 'R. Mensah', status: 'Approved', isCde: true,
    definition: 'A disconnect requested by the subscriber where the number was not ported to another carrier.', formula: "DISCONNECT_REASON = 'VOLUNTARY'",
    synonyms: ['voluntary churn', 'customer cancel'], related: ['T-004', 'T-005'],
    mappings: [{ fqn: `${G}.FCT_SUBSCRIBER_MONTHLY`, column: 'VOLUNTARY_DISCONNECTS', kind: 'defines' }, { fqn: `${S}.SUBSCRIBER_EVENT`, column: 'DISCONNECT_REASON', kind: 'defines' }],
    metricRefs: [], dqRules: ['Reason code present on every disconnect'], dqScore: 98.9 }),
  term({ id: 'T-026', term: 'Minutes of Use', domain: 'Usage', owner: 'S. Varga', steward: 'P. Okonkwo', status: 'Approved', isCde: false,
    definition: 'Voice minutes a subscriber used in the period, originating and terminating, from mediated voice CDRs.', formula: 'Σ VOICE_MIN per subscriber per month',
    synonyms: ['mou', 'voice minutes'], related: ['T-011'],
    mappings: [{ fqn: `${G}.FCT_DAILY_USAGE`, column: 'VOICE_MIN', kind: 'defines' }],
    metricRefs: ['SV_SUBSCRIBER_360.voice_min_per_sub'] }),
  term({ id: 'T-027', term: 'Autopay Enrolment', domain: 'Subscriber', owner: 'K. Albright', steward: 'R. Mensah', status: 'Approved', isCde: false,
    definition: 'The share of active subscribers who pay automatically by card or bank debit.', formula: 'Active subscribers with AUTOPAY = TRUE ÷ active subscribers',
    synonyms: ['autopay', 'auto pay', 'automatic payment'], related: ['T-002'],
    mappings: [{ fqn: `${G}.DIM_SUBSCRIBER`, column: 'AUTOPAY', kind: 'defines' }],
    metricRefs: ['SV_SUBSCRIBER_360.autopay_rate'] }),
  term({ id: 'T-028', term: 'Roaming Revenue', domain: 'Revenue', owner: 'Wholesale & Roaming (H. Lindqvist)', steward: 'J. Whitfield', status: 'Approved', isCde: false,
    definition: 'Retail revenue billed to Altair subscribers for voice, data and SMS used on partner networks abroad. Wholesale (inbound) roaming settled with partners is excluded.', formula: 'Σ ROAMING_REVENUE ÷ Σ mobile service revenue × 100 (roaming share)',
    synonyms: ['roaming', 'international roaming', 'outbound roaming'], related: ['T-010'],
    mappings: [{ fqn: `${G}.FCT_BILLING`, column: 'ROAMING_REVENUE', kind: 'defines' }, { fqn: `${G}.FCT_DAILY_USAGE`, column: 'ROAMING_MB', kind: 'derives' }],
    metricRefs: ['SV_SUBSCRIBER_360.roaming_revenue_share'] }),
  term({ id: 'T-029', term: 'Network SLA', domain: 'Network', owner: 'S. Varga', steward: 'P. Okonkwo', status: 'Approved', isCde: false,
    definition: 'The internal service level for each cell site: at least 99.9% availability in every calendar month.', formula: 'Site-month availability ≥ 99.9% (downtime ≤ 43.2 minutes in a 30-day month)',
    synonyms: ['sla', 'site sla'], related: ['T-014'],
    mappings: [{ fqn: `${G}.FCT_NETWORK_DAILY`, column: 'DOWNTIME_MIN', kind: 'filters' }],
    metricRefs: ['SV_NETWORK_PERFORMANCE.site_sla_compliance'] }),
  term({ id: 'T-030', term: 'Downlink Throughput', domain: 'Network', owner: 'S. Varga', steward: 'P. Okonkwo', status: 'Approved', isCde: false,
    definition: 'Average data speed delivered to users on a cell site, in megabits per second.', formula: 'Mean of AVG_THROUGHPUT_MBPS across site-days',
    synonyms: ['throughput', 'download speed'], related: ['T-016'],
    mappings: [{ fqn: `${G}.FCT_NETWORK_DAILY`, column: 'AVG_THROUGHPUT_MBPS', kind: 'defines' }],
    metricRefs: ['SV_NETWORK_PERFORMANCE.avg_throughput_mbps'] }),
  term({ id: 'T-031', term: 'Work Order', domain: 'Field service', owner: 'M. Castellanos', steward: 'P. Okonkwo', status: 'Approved', isCde: false,
    definition: 'A field technician job: a new home install, a broadband repair or a network site repair, from open to close.', formula: 'One record per WORK_ORDER_ID; hours to resolve = closed − opened',
    synonyms: ['job', 'truck roll', 'ticket'], related: ['T-021'],
    mappings: [{ fqn: `${S}.WORK_ORDER`, column: 'WORK_ORDER_TYPE', kind: 'defines' }, { fqn: `${G}.FCT_WORK_ORDER`, column: 'HOURS_TO_RESOLVE', kind: 'derives' }],
    metricRefs: ['DP_FIELD_SERVICE_EFFICIENCY.avg_hours_to_resolve'] }),
];
