import type { GlossaryTerm } from '../../types';

const G = 'CONFORMED_GOLD';
const term = (t: Omit<GlossaryTerm, 'related' | 'synonyms'> & Partial<Pick<GlossaryTerm, 'related' | 'synonyms'>>): GlossaryTerm => ({ related: [], synonyms: [], ...t });

export const GLOSSARY: GlossaryTerm[] = [
  term({ id: 'T-001', term: 'Customer', domain: 'Customer', owner: 'M. Reyes', steward: 'A. Patel', status: 'Approved', isCde: true,
    definition: 'A person or organisation with a service agreement for one or more premises.', formula: 'One record per CUSTOMER_ID; the current SCD2 version represents the customer today.',
    synonyms: ['account holder', 'ratepayer'], related: ['T-002', 'T-012'],
    mappings: [{ fqn: `${G}.DIM_CUSTOMER`, column: 'CUSTOMER_ID', kind: 'defines' }, { fqn: 'CURATED_SILVER.CUSTOMER', column: 'CUSTOMER_ID', kind: 'defines' }],
    metricRefs: [], dqRules: ['CUSTOMER_ID not null', 'CUSTOMER_ID unique where IS_CURRENT'], dqScore: 99.8 }),
  term({ id: 'T-002', term: 'Active Customer', domain: 'Customer', owner: 'M. Reyes', steward: 'A. Patel', status: 'Approved', isCde: true,
    definition: 'A customer whose account status is Active and who has at least one billed statement in the last 60 days.', formula: 'status = Active AND max(statement date) > as-of date − 60 days',
    synonyms: ['active account', 'live customer'], related: ['T-001', 'T-011'],
    mappings: [{ fqn: 'CURATED_SILVER.CUSTOMER', column: 'CUSTOMER_STATUS', kind: 'filters' }, { fqn: `${G}.FCT_BILLING`, column: 'DATE_KEY', kind: 'filters' }, { fqn: 'DATA_PRODUCTS.DP_CUSTOMER_360', column: 'IS_ACTIVE', kind: 'derives' }],
    metricRefs: ['SV_CUSTOMER_360.active_customers'], dqRules: ['Status in (Active, Inactive)', 'Billing recency computed daily'], dqScore: 98.9 }),
  term({ id: 'T-003', term: 'Operating Company', domain: 'Enterprise', owner: 'Corporate Finance (R. Adeyemi)', steward: 'H. Sullivan', status: 'Approved', isCde: true,
    definition: 'One of Northvale’s four regulated operating companies: Northvale Ohio, Indiana, Kentucky and Appalachia.', formula: 'Derived from service state: OH → Ohio, IN → Indiana, KY → Kentucky, WV/VA → Appalachia',
    synonyms: ['opco', 'utility', 'jurisdiction'], related: ['T-004'],
    mappings: [{ fqn: `${G}.DIM_CUSTOMER`, column: 'OPCO', kind: 'defines' }, { fqn: `${G}.DIM_CIRCUIT`, column: 'OPCO', kind: 'defines' }, { fqn: `${G}.FCT_BILLING`, column: 'OPCO', kind: 'derives' }],
    metricRefs: [], dqRules: ['OPCO in reference list'], dqScore: 100 }),
  term({ id: 'T-004', term: 'SAIDI', domain: 'Grid ops', owner: 'T. Baptiste', steward: 'H. Sullivan', status: 'Approved', isCde: true,
    definition: 'System Average Interruption Duration Index: the average outage minutes per customer served over a period.', formula: 'Sum of customer minutes interrupted ÷ customers served, excluding major event days (IEEE 1366)',
    synonyms: ['outage minutes per customer', 'average interruption duration'], related: ['T-005', 'T-006', 'T-007', 'T-008'],
    mappings: [{ fqn: `${G}.FCT_OUTAGE`, column: 'CUSTOMER_MINUTES', kind: 'derives' }, { fqn: `${G}.DIM_CIRCUIT`, column: 'CUSTOMERS_SERVED', kind: 'derives' }, { fqn: `${G}.FCT_OUTAGE`, column: 'MED_FLAG', kind: 'filters' }],
    metricRefs: ['SV_RELIABILITY.saidi_minutes'], dqRules: ['CUSTOMER_MINUTES ≥ 0', 'Event duration ≥ 5 min (sustained)', 'MED flag present for every event'], dqScore: 99.4 }),
  term({ id: 'T-005', term: 'SAIFI', domain: 'Grid ops', owner: 'T. Baptiste', steward: 'H. Sullivan', status: 'Approved', isCde: true,
    definition: 'System Average Interruption Frequency Index: how often the average customer experienced a sustained interruption.', formula: 'Sum of customers interrupted ÷ customers served, excluding major event days',
    synonyms: ['interruption frequency'], related: ['T-004', 'T-006'],
    mappings: [{ fqn: `${G}.FCT_OUTAGE`, column: 'CUSTOMERS_INTERRUPTED', kind: 'derives' }, { fqn: `${G}.DIM_CIRCUIT`, column: 'CUSTOMERS_SERVED', kind: 'derives' }],
    metricRefs: ['SV_RELIABILITY.saifi', 'SV_RELIABILITY.customers_interrupted'], dqRules: ['CUSTOMERS_INTERRUPTED ≤ CUSTOMERS_SERVED on circuit'], dqScore: 99.6 }),
  term({ id: 'T-006', term: 'CAIDI', domain: 'Grid ops', owner: 'T. Baptiste', steward: 'H. Sullivan', status: 'Approved', isCde: true,
    definition: 'Customer Average Interruption Duration Index: the average restoration time for customers who were interrupted.', formula: 'SAIDI ÷ SAIFI (equivalently customer minutes ÷ customers interrupted)',
    synonyms: ['restoration time', 'average restoration'], related: ['T-004', 'T-005'],
    mappings: [{ fqn: `${G}.FCT_OUTAGE`, column: 'CUSTOMER_MINUTES', kind: 'derives' }, { fqn: `${G}.FCT_OUTAGE`, column: 'CUSTOMERS_INTERRUPTED', kind: 'derives' }],
    metricRefs: ['SV_RELIABILITY.caidi_minutes'], dqRules: ['Derived; inherits SAIDI and SAIFI rules'], dqScore: 99.4 }),
  term({ id: 'T-007', term: 'Major Event Day', domain: 'Grid ops', owner: 'T. Baptiste', steward: 'H. Sullivan', status: 'Approved', isCde: true,
    definition: 'A day whose daily SAIDI exceeds the IEEE 1366 2.5 beta threshold. Reliability indices are normally reported excluding these days.', formula: 'Daily SAIDI > exp(α + 2.5β) over the trailing five years of daily SAIDI',
    synonyms: ['MED', 'storm day', 'major event'], related: ['T-004'],
    mappings: [{ fqn: `${G}.DIM_DATE`, column: 'IS_MAJOR_EVENT_DAY', kind: 'defines' }, { fqn: `${G}.FCT_OUTAGE`, column: 'MED_FLAG', kind: 'filters' }],
    metricRefs: [], dqRules: ['Recomputed annually', 'Flag consistent between DIM_DATE and FCT_OUTAGE'], dqScore: 100 }),
  term({ id: 'T-008', term: 'Customer Minutes Interrupted', domain: 'Grid ops', owner: 'T. Baptiste', steward: 'H. Sullivan', status: 'Approved', isCde: true,
    definition: 'Customers interrupted multiplied by the duration of the interruption, summed across events.', formula: 'Σ customers interrupted × duration (minutes)',
    synonyms: ['CMI', 'customer minutes'], related: ['T-004'],
    mappings: [{ fqn: `${G}.FCT_OUTAGE`, column: 'CUSTOMER_MINUTES', kind: 'defines' }],
    metricRefs: ['SV_RELIABILITY.customer_minutes_interrupted'], dqRules: ['Non-negative', 'Matches OMS restoration timestamps'], dqScore: 99.2 }),
  term({ id: 'T-009', term: 'Monthly Bill', domain: 'Customer / Finance', owner: 'D. Ramirez', steward: 'A. Patel', status: 'Approved', isCde: true,
    definition: 'The billing statement issued to a customer each billing cycle, and the amount billed on it (excluding past-due balance).', formula: 'BILLED_AMOUNT per statement; average monthly bill = mean billed amount per statement',
    synonyms: ['bill', 'statement', 'average bill'], related: ['T-010', 'T-021'],
    mappings: [{ fqn: `${G}.FCT_BILLING`, column: 'BILLED_AMOUNT', kind: 'defines' }, { fqn: 'CURATED_SILVER.BILLING_STATEMENT', column: 'AMOUNT_DUE_USD', kind: 'derives' }],
    metricRefs: ['SV_CUSTOMER_360.avg_monthly_bill', 'SV_BILLING_AR.bills_issued'], dqRules: ['BILLED_AMOUNT ≥ 0', 'One statement per customer per cycle'], dqScore: 99.1 }),
  term({ id: 'T-010', term: 'Arrears Balance', domain: 'Customer / Finance', owner: 'D. Ramirez', steward: 'A. Patel', status: 'Approved', isCde: true,
    definition: 'The past-due amount owed by a customer on their latest statement.', formula: 'ARREARS_AMOUNT on the most recent statement per customer',
    synonyms: ['past due', 'overdue balance', 'debt'], related: ['T-009', 'T-018'],
    mappings: [{ fqn: `${G}.FCT_BILLING`, column: 'ARREARS_AMOUNT', kind: 'defines' }],
    metricRefs: ['SV_CUSTOMER_360.arrears_balance'], dqRules: ['ARREARS_AMOUNT ≥ 0'], dqScore: 98.7 }),
  term({ id: 'T-011', term: 'Digital Adoption', domain: 'Customer', owner: 'M. Reyes', steward: 'A. Patel', status: 'Approved', isCde: false,
    definition: 'The share of active customers enrolled in paperless billing.', formula: 'Active customers with DIGITAL_ENROLLED = TRUE ÷ active customers',
    synonyms: ['paperless', 'e-bill adoption'], related: ['T-002'],
    mappings: [{ fqn: `${G}.DIM_CUSTOMER`, column: 'DIGITAL_ENROLLED', kind: 'defines' }],
    metricRefs: ['SV_CUSTOMER_360.digital_adoption_rate'] }),
  term({ id: 'T-012', term: 'Rate Class', domain: 'Customer', owner: 'Rates & Regulatory (P. Novak)', steward: 'A. Patel', status: 'Approved', isCde: true,
    definition: 'The tariff a customer is billed under: RS-1 Residential, RS-TOU Residential time-of-use, GS-1 Small commercial, GS-2 Large commercial.', formula: 'Mapped from CIS RATE_CD',
    synonyms: ['tariff', 'rate code', 'rate'], related: ['T-001'],
    mappings: [{ fqn: `${G}.DIM_CUSTOMER`, column: 'RATE_CLASS', kind: 'defines' }],
    metricRefs: [], dqRules: ['RATE_CLASS in tariff book'], dqScore: 100 }),
  term({ id: 'T-013', term: 'Read Success Rate', domain: 'Metering', owner: 'G. Hughes', steward: 'O. Chen', status: 'Approved', isCde: true,
    definition: 'The share of expected 15-minute interval reads received and validated from AMI meters.', formula: 'Valid intervals ÷ expected intervals × 100',
    synonyms: ['read rate', 'AMI read performance'], related: ['T-014'],
    mappings: [{ fqn: `${G}.FCT_DAILY_USAGE`, column: 'READ_SUCCESS_PCT', kind: 'defines' }, { fqn: 'CURATED_SILVER.METER_READ_15MIN', column: 'READ_QUALITY', kind: 'derives' }],
    metricRefs: ['SV_CUSTOMER_360.read_success_rate', 'SV_CUSTOMER_360.estimated_read_pct'], dqRules: ['0 ≤ value ≤ 100'], dqScore: 99.9 }),
  term({ id: 'T-014', term: 'Peak Demand', domain: 'Metering', owner: 'G. Hughes', steward: 'O. Chen', status: 'Approved', isCde: false,
    definition: 'The highest average kW over any 15-minute interval in a day for a premise.', formula: 'max(interval kWh × 4) per premise per day',
    synonyms: ['max demand', 'peak load'], related: ['T-013'],
    mappings: [{ fqn: `${G}.FCT_DAILY_USAGE`, column: 'PEAK_KW', kind: 'defines' }],
    metricRefs: ['SV_CUSTOMER_360.peak_kw'] }),
  term({ id: 'T-015', term: 'Spend Under Contract', domain: 'Supply chain', owner: 'S. Moreau', steward: 'L. Kowalski', status: 'Approved', isCde: true,
    definition: 'The share of purchase order spend placed against an active outline agreement or contract.', formula: 'On-contract spend ÷ total spend × 100',
    synonyms: ['contract compliance', 'on-contract spend'], related: ['T-016', 'T-023'],
    mappings: [{ fqn: `${G}.FCT_PO_SPEND`, column: 'ON_CONTRACT', kind: 'defines' }, { fqn: `${G}.FCT_PO_SPEND`, column: 'SPEND_USD', kind: 'derives' }],
    metricRefs: ['SV_PROCUREMENT.spend_under_contract_pct'], dqRules: ['ON_CONTRACT not null', 'Contract reference valid on PO date'], dqScore: 98.4 }),
  term({ id: 'T-016', term: 'Maverick Spend', domain: 'Supply chain', owner: 'S. Moreau', steward: 'L. Kowalski', status: 'Approved', isCde: true,
    definition: 'Spend placed with any supplier outside an active contract, including spot buys and emergency purchases.', formula: 'Σ spend where ON_CONTRACT = FALSE',
    synonyms: ['off-contract spend', 'rogue spend', 'leakage'], related: ['T-015'],
    mappings: [{ fqn: `${G}.FCT_PO_SPEND`, column: 'ON_CONTRACT', kind: 'filters' }, { fqn: `${G}.FCT_PO_SPEND`, column: 'SPEND_USD', kind: 'derives' }],
    metricRefs: ['SV_PROCUREMENT.maverick_spend'], dqRules: ['Inherits Spend Under Contract rules'], dqScore: 98.4 }),
  term({ id: 'T-017', term: 'Supplier OTIF', domain: 'Supply chain', owner: 'S. Moreau', steward: 'L. Kowalski', status: 'Approved', isCde: true,
    definition: 'The share of PO lines a supplier delivered on or before the promised date and in full quantity.', formula: 'Lines received on time and in full ÷ lines received × 100',
    synonyms: ['OTIF', 'on time in full', 'delivery performance'], related: ['T-022'],
    mappings: [{ fqn: `${G}.FCT_PO_SPEND`, column: 'OTIF_FLAG', kind: 'defines' }],
    metricRefs: ['SV_PROCUREMENT.otif_pct'], dqRules: ['Promised date present', 'Receipt date ≥ PO date'], dqScore: 97.9 }),
  term({ id: 'T-018', term: 'Days Sales Outstanding', domain: 'Customer / Finance', owner: 'D. Ramirez', steward: 'A. Patel', status: 'Approved', isCde: true,
    definition: 'How many days of billed revenue are tied up in receivables.', formula: '(Current billed + arrears) ÷ billed revenue in the period × days in the period',
    synonyms: ['DSO', 'collection days'], related: ['T-010', 'T-024'],
    mappings: [{ fqn: `${G}.FCT_BILLING`, column: 'BILLED_AMOUNT', kind: 'derives' }, { fqn: `${G}.FCT_BILLING`, column: 'ARREARS_AMOUNT', kind: 'derives' }, { fqn: `${G}.FCT_BILLING`, column: 'DAYS_TO_PAY', kind: 'derives' }],
    metricRefs: ['SV_BILLING_AR.dso_days'], dqRules: ['Billed > 0 in period'], dqScore: 96.8 }),
  term({ id: 'T-019', term: 'Span Overdue for Trim', domain: 'Grid ops', owner: 'J. Lindqvist', steward: null, status: 'Approved', isCde: true,
    definition: 'A vegetation span whose last trim date is older than its trim cycle (4 or 5 years).', formula: 'LAST_TRIM_DATE + CYCLE_YEARS < as-of date',
    synonyms: ['overdue span', 'trim backlog'], related: ['T-025'],
    mappings: [{ fqn: 'CURATED_SILVER.VEGETATION_SPAN', column: 'IS_OVERDUE', kind: 'defines' }, { fqn: 'DATA_PRODUCTS.DP_VEGETATION_RISK', column: 'IS_OVERDUE', kind: 'defines' }],
    metricRefs: ['DP_VEGETATION_RISK.spans_overdue_pct', 'DP_VEGETATION_RISK.trim_cycle_compliance'], dqRules: ['LAST_TRIM_DATE not in future'], dqScore: 91.2 }),
  term({ id: 'T-020', term: 'Churn Risk Score', domain: 'Customer', owner: 'M. Reyes', steward: 'A. Patel', status: 'Draft', isCde: false,
    definition: 'Model score (0–100) estimating the likelihood a commercial or residential customer leaves or switches supplier in the next 12 months. Draft: model card pending review.', formula: 'Gradient-boosted model over arrears, contacts, usage trend and tenure',
    synonyms: ['churn risk', 'attrition risk'], related: ['T-001', 'T-010'],
    mappings: [{ fqn: `${G}.DIM_CUSTOMER`, column: 'CHURN_RISK_SCORE', kind: 'defines' }],
    metricRefs: ['SV_CUSTOMER_360.avg_churn_risk'] }),
  term({ id: 'T-021', term: 'Estimated Bill', domain: 'Customer / Finance', owner: 'D. Ramirez', steward: 'A. Patel', status: 'Approved', isCde: false,
    definition: 'A bill based on an estimated rather than an actual meter read.', formula: 'IS_ESTIMATED = TRUE',
    synonyms: ['estimate'], related: ['T-009', 'T-013'],
    mappings: [{ fqn: `${G}.FCT_BILLING`, column: 'IS_ESTIMATED', kind: 'defines' }],
    metricRefs: ['SV_BILLING_AR.estimated_bill_rate'] }),
  term({ id: 'T-022', term: 'PO Cycle Time', domain: 'Supply chain', owner: 'S. Moreau', steward: 'L. Kowalski', status: 'Approved', isCde: false,
    definition: 'Days from purchase order creation to goods receipt.', formula: 'RECEIVED_DATE − PO date',
    synonyms: ['cycle time', 'lead time'], related: ['T-017'],
    mappings: [{ fqn: `${G}.FCT_PO_SPEND`, column: 'CYCLE_DAYS', kind: 'defines' }],
    metricRefs: ['SV_PROCUREMENT.po_cycle_days'] }),
  term({ id: 'T-023', term: 'Total Spend', domain: 'Supply chain', owner: 'S. Moreau', steward: 'L. Kowalski', status: 'Approved', isCde: false,
    definition: 'All purchase order spend in a period, before returns and credits.', formula: 'Σ SPEND_USD',
    synonyms: ['spend', 'purchases'], related: ['T-015', 'T-016'],
    mappings: [{ fqn: `${G}.FCT_PO_SPEND`, column: 'SPEND_USD', kind: 'defines' }],
    metricRefs: ['SV_PROCUREMENT.total_spend'] }),
  term({ id: 'T-024', term: 'Collections Rate', domain: 'Customer / Finance', owner: 'D. Ramirez', steward: 'A. Patel', status: 'Approved', isCde: true,
    definition: 'The share of billed revenue collected within 60 days of the statement date.', formula: 'Billed amount paid within 60 days ÷ billed amount × 100',
    synonyms: ['collection rate', 'cash collection'], related: ['T-018'],
    mappings: [{ fqn: `${G}.FCT_BILLING`, column: 'DAYS_TO_PAY', kind: 'filters' }, { fqn: `${G}.FCT_BILLING`, column: 'BILLED_AMOUNT', kind: 'derives' }],
    metricRefs: ['SV_BILLING_AR.collections_rate'], dqRules: ['DAYS_TO_PAY ≥ 0'], dqScore: 97.5 }),
  term({ id: 'T-025', term: 'Tree-Caused Outage', domain: 'Grid ops', owner: 'J. Lindqvist', steward: 'H. Sullivan', status: 'Approved', isCde: false,
    definition: 'A sustained outage whose confirmed cause is tree or vegetation contact with a line.', formula: "CAUSE = 'Tree contact'",
    synonyms: ['tree outage', 'vegetation outage'], related: ['T-019', 'T-004'],
    mappings: [{ fqn: `${G}.FCT_OUTAGE`, column: 'CAUSE', kind: 'filters' }],
    metricRefs: ['SV_RELIABILITY.tree_outages'] }),
  term({ id: 'T-026', term: 'Daily Consumption', domain: 'Metering', owner: 'G. Hughes', steward: 'O. Chen', status: 'Approved', isCde: false,
    definition: 'Total kWh delivered to a premise in a calendar day.', formula: 'Σ interval kWh per premise per day',
    synonyms: ['usage', 'consumption', 'load'], related: ['T-014'],
    mappings: [{ fqn: `${G}.FCT_DAILY_USAGE`, column: 'KWH', kind: 'defines' }],
    metricRefs: ['SV_CUSTOMER_360.daily_kwh'] }),
];
