// Shared-structure schemas (spec section 5): GLOSSARY, CONTEXT, DATA_PRODUCTS registry, AGENTS and GOVERNANCE
// have identical table structures in every pack; only the rows change. Semantic view, product secure view and
// agent objects are also generated here from the pack's metadata.
import type { Column, IndustryPack, LiveState, Row, SemanticView, SfObject, SensitiveClass, VerifiedQuery } from '../types';

type Core = Omit<IndustryPack, 'objects'> & { physical: SfObject[] };

const c = (name: string, type: string, comment: string, extra: Partial<Column> = {}): Column => ({
  name, type, nullable: true, comment, ...extra,
});

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;

export function semanticViewDdl(db: string, sv: SemanticView): string {
  const tables = sv.tables.map((t) => `    ${t.alias} AS ${db}.${t.fqn}\n      PRIMARY KEY (${t.pk})`).join(',\n');
  const rels = sv.relationships
    .map((r) => `    ${r.from}_to_${r.to} AS ${r.from} (${r.on}) REFERENCES ${r.to}`)
    .join(',\n');
  const facts = sv.facts.map((f) => `    ${f.name} AS ${f.expr}`).join(',\n');
  const dims = [
    ...sv.timeDimensions.map((d) => `    ${d.name} AS ${d.expr}`),
    ...sv.dimensions.map(
      (d) => `    ${d.name} AS ${d.expr}${d.synonyms.length ? `\n      WITH SYNONYMS = (${d.synonyms.map(q).join(', ')})` : ''}`,
    ),
  ].join(',\n');
  const mets = sv.metrics
    .map(
      (m) =>
        `    ${m.name} AS ${m.expr}${m.synonyms.length ? `\n      WITH SYNONYMS = (${m.synonyms.map(q).join(', ')})` : ''}\n      COMMENT = ${q(m.description)}`,
    )
    .join(',\n');
  return `CREATE OR REPLACE SEMANTIC VIEW ${db}.SEMANTIC.${sv.name}\n  TABLES (\n${tables}\n  )\n  RELATIONSHIPS (\n${rels || '    -- single table'}\n  )\n  FACTS (\n${facts}\n  )\n  DIMENSIONS (\n${dims}\n  )\n  METRICS (\n${mets}\n  )\n  COMMENT = ${q(sv.description)};`;
}

/** Verified queries including any approved through the certification "Add verified queries" fix. */
export function verifiedQueriesLive(pack: Pick<IndustryPack, 'context' | 'certificationScript' | 'products'>, live: LiveState): VerifiedQuery[] {
  const pid = pack.certificationScript.productId;
  const fail = pack.certificationScript.failures.find((f) => f.fix.kind === 'verified-queries');
  const sv = pack.products.find((p) => p.id === pid)?.semanticView;
  if (!fail || !sv || !(live.fixes[pid] ?? []).includes(fail.checkId)) return pack.context.verifiedQueries;
  const base = pack.context.verifiedQueries.length;
  return [
    ...pack.context.verifiedQueries,
    ...fail.fix.items.map((question, i) => ({
      id: `VQ-${String(base + i + 1).padStart(3, '0')}`, semanticView: sv, question,
      sql: `-- generated by Cortex Analyst, approved in Certification Studio\nSELECT ... FROM ${sv}`,
      verifiedBy: 'DATA_STEWARD', verifiedOn: '2026-10-04',
    })),
  ];
}

export function buildSharedObjects(core: Core): SfObject[] {
  const db = core.database;
  const now = '2026-09-30 05:42:11';
  const out: SfObject[] = [];
  const sensitive = core.profile.sensitiveClasses;

  // ---- SEMANTIC
  for (const sv of core.semanticViews) {
    out.push({
      schema: 'SEMANTIC', name: sv.name, layer: 'semantic', type: 'SEMANTIC VIEW', comment: sv.description,
      columns: [
        ...sv.dimensions.map((d) => c(d.name.toUpperCase(), 'DIMENSION', d.description ?? d.expr)),
        ...sv.timeDimensions.map((d) => c(d.name.toUpperCase(), 'TIME DIMENSION', d.description ?? d.expr)),
        ...sv.metrics.map((m) => c(m.name.toUpperCase(), 'METRIC', m.description, { termId: m.termId })),
      ],
      rowCount: 0, owner: 'SEMANTIC_ADMIN', lastAltered: '2026-09-18 14:03:27',
      upstream: sv.tables.map((t) => t.fqn), ddl: semanticViewDdl(db, sv),
    });
  }

  // ---- GLOSSARY
  out.push({
    schema: 'GLOSSARY', name: 'BUSINESS_TERM', layer: 'glossary', type: 'TABLE', comment: 'Approved business vocabulary and critical data elements',
    columns: [
      c('TERM_ID', 'VARCHAR(10)', 'Term identifier', { nullable: false }), c('TERM', 'VARCHAR(120)', 'Business term'),
      c('DEFINITION', 'VARCHAR(2000)', 'Approved definition'), c('DOMAIN', 'VARCHAR(40)', 'Owning domain'),
      c('OWNER', 'VARCHAR(80)', 'Business owner'), c('STEWARD', 'VARCHAR(80)', 'Data steward'),
      c('STATUS', 'VARCHAR(12)', 'Approved / Draft / Deprecated'), c('IS_CDE', 'BOOLEAN', 'Critical data element flag'),
    ],
    rowCount: core.glossary.length, owner: 'DATA_STEWARD', lastAltered: '2026-09-22 10:12:40', upstream: [],
    rows: () => core.glossary.map((t) => ({
      TERM_ID: t.id, TERM: t.term, DEFINITION: t.definition, DOMAIN: t.domain, OWNER: t.owner, STEWARD: t.steward,
      STATUS: t.status, IS_CDE: t.isCde,
    })),
  });
  const maps = core.glossary.flatMap((t) => t.mappings.map((m) => ({ TERM_ID: t.id, OBJECT_FQN: `${db}.${m.fqn}`, COLUMN_NAME: m.column, MAPPING_TYPE: m.kind })));
  out.push({
    schema: 'GLOSSARY', name: 'TERM_COLUMN_MAP', layer: 'glossary', type: 'TABLE', comment: 'Maps business terms to physical columns',
    columns: [
      c('TERM_ID', 'VARCHAR(10)', 'Term identifier'), c('OBJECT_FQN', 'VARCHAR(200)', 'Fully qualified object name'),
      c('COLUMN_NAME', 'VARCHAR(80)', 'Mapped column'), c('MAPPING_TYPE', 'VARCHAR(10)', 'defines / derives / filters'),
    ],
    rowCount: maps.length, owner: 'DATA_STEWARD', lastAltered: '2026-09-22 10:12:40', upstream: ['GLOSSARY.BUSINESS_TERM'],
    rows: () => maps,
  });
  const cdes = core.glossary.filter((t) => t.isCde);
  out.push({
    schema: 'GLOSSARY', name: 'CDE_REGISTER', layer: 'glossary', type: 'TABLE', comment: 'Critical data element register with DQ rules and latest score',
    columns: [
      c('CDE_ID', 'VARCHAR(10)', 'CDE identifier'), c('CDE_NAME', 'VARCHAR(120)', 'CDE name'), c('TERM_ID', 'VARCHAR(10)', 'Business term'),
      c('DATA_PRODUCT', 'VARCHAR(10)', 'Primary data product'), c('STEWARD', 'VARCHAR(80)', 'Accountable steward'),
      c('DQ_RULES', 'VARCHAR(500)', 'Data quality rules'), c('LAST_DQ_SCORE', 'NUMBER(5,1)', 'Latest DQ score %'),
    ],
    rowCount: cdes.length, owner: 'DATA_STEWARD', lastAltered: '2026-09-29 03:00:12', upstream: ['GLOSSARY.BUSINESS_TERM'],
    rows: () => cdes.map((t, i) => ({
      CDE_ID: `CDE-${String(i + 1).padStart(2, '0')}`, CDE_NAME: t.term, TERM_ID: t.id,
      DATA_PRODUCT: core.products.find((p) => p.kpiIds.some((k) => core.kpis.find((kk) => kk.id === k)?.termId === t.id))?.id ?? null,
      STEWARD: t.steward, DQ_RULES: (t.dqRules ?? []).join('; '), LAST_DQ_SCORE: t.dqScore ?? null,
    })),
  });

  // ---- CONTEXT
  const ctx = core.context;
  out.push({
    schema: 'CONTEXT', name: 'AGENT_INSTRUCTIONS', layer: 'context', type: 'TABLE', comment: 'Versioned agent instructions',
    columns: [c('AGENT_NAME', 'VARCHAR(80)', 'Agent'), c('INSTRUCTION_TYPE', 'VARCHAR(16)', 'persona / response / guardrail / orchestration'), c('TEXT', 'VARCHAR(2000)', 'Instruction text'), c('VERSION', 'VARCHAR(10)', 'Version')],
    rowCount: ctx.instructions.length, owner: 'AI_PLATFORM_ADMIN', lastAltered: '2026-09-20 16:45:03', upstream: [],
    rows: () => ctx.instructions.map((i) => ({ AGENT_NAME: core.agents.find((a) => a.id === i.agentId)?.objectName ?? i.agentId, INSTRUCTION_TYPE: i.type, TEXT: i.text, VERSION: i.version })),
  });
  out.push({
    schema: 'CONTEXT', name: 'BUSINESS_RULES', layer: 'context', type: 'TABLE', comment: 'Business rules tied to metrics with their source document',
    columns: [c('RULE_ID', 'VARCHAR(10)', 'Rule id'), c('DOMAIN', 'VARCHAR(40)', 'Domain'), c('RULE_TEXT', 'VARCHAR(2000)', 'Rule'), c('APPLIES_TO_METRIC', 'VARCHAR(120)', 'Metric'), c('SOURCE_DOC', 'VARCHAR(200)', 'Source document')],
    rowCount: ctx.rules.length, owner: 'DATA_STEWARD', lastAltered: '2026-09-12 09:30:00', upstream: [],
    rows: () => ctx.rules.map((r) => ({ RULE_ID: r.id, DOMAIN: r.domain, RULE_TEXT: r.text, APPLIES_TO_METRIC: r.metric, SOURCE_DOC: r.sourceDoc })),
  });
  out.push({
    schema: 'CONTEXT', name: 'VERIFIED_QUERIES', layer: 'context', type: 'TABLE', comment: 'Verified question → SQL pairs used by Cortex Analyst',
    columns: [c('VQ_ID', 'VARCHAR(10)', 'Id'), c('SEMANTIC_VIEW', 'VARCHAR(80)', 'Semantic view'), c('QUESTION', 'VARCHAR(500)', 'Question'), c('SQL_TEXT', 'VARCHAR(4000)', 'Verified SQL'), c('VERIFIED_BY', 'VARCHAR(80)', 'Verifier'), c('VERIFIED_ON', 'DATE', 'Verified on')],
    rowCount: ctx.verifiedQueries.length, owner: 'SEMANTIC_ADMIN', lastAltered: '2026-09-26 11:20:44', upstream: core.semanticViews.map((s) => `SEMANTIC.${s.name}`),
    rows: (live: LiveState) =>
      verifiedQueriesLive(core, live).map((v) => ({ VQ_ID: v.id, SEMANTIC_VIEW: v.semanticView, QUESTION: v.question, SQL_TEXT: v.sql, VERIFIED_BY: v.verifiedBy, VERIFIED_ON: v.verifiedOn })),
  });
  out.push({
    schema: 'CONTEXT', name: 'SYNONYMS', layer: 'context', type: 'TABLE', comment: 'Synonyms used to resolve user language',
    columns: [c('TERM', 'VARCHAR(120)', 'Canonical term'), c('SYNONYM', 'VARCHAR(120)', 'Synonym'), c('SCOPE', 'VARCHAR(40)', 'Scope')],
    rowCount: ctx.synonyms.length, owner: 'DATA_STEWARD', lastAltered: '2026-09-12 09:30:00', upstream: ['GLOSSARY.BUSINESS_TERM'],
    rows: () => ctx.synonyms.map((s) => ({ TERM: s.term, SYNONYM: s.synonym, SCOPE: s.scope })),
  });
  out.push({
    schema: 'CONTEXT', name: ctx.searchService, layer: 'context', type: 'CORTEX SEARCH SERVICE', comment: 'Cortex Search over policy and standards documents',
    columns: [c('DOC_ID', 'VARCHAR(10)', 'Document id'), c('TITLE', 'VARCHAR(200)', 'Title'), c('SOURCE', 'VARCHAR(200)', 'Stage path'), c('CHUNK_COUNT', 'NUMBER', 'Indexed chunks'), c('UPDATED_AT', 'TIMESTAMP_NTZ', 'Last refresh')],
    rowCount: ctx.documents.reduce((a, d) => a + d.chunkCount, 0), owner: 'AI_PLATFORM_ADMIN', lastAltered: '2026-09-28 02:10:00', upstream: ['ext:Document stage (PDF)'],
    rows: () => ctx.documents.map((d) => ({ DOC_ID: d.id, TITLE: d.title, SOURCE: d.source, CHUNK_COUNT: d.chunkCount, UPDATED_AT: d.updatedAt })),
    ddl: `CREATE OR REPLACE CORTEX SEARCH SERVICE ${db}.CONTEXT.${ctx.searchService}\n  ON CHUNK_TEXT\n  ATTRIBUTES DOC_ID, TITLE, SOURCE\n  WAREHOUSE = WH_AI_S\n  TARGET_LAG = '1 day'\n  EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'\nAS (\n  SELECT DOC_ID, TITLE, SOURCE, CHUNK_TEXT\n    FROM ${db}.CONTEXT.DOC_CHUNKS\n);`,
  });

  // ---- DATA_PRODUCTS registry
  out.push({
    schema: 'DATA_PRODUCTS', name: 'DP_REGISTRY', layer: 'product', type: 'TABLE', comment: 'Data product registry (live certification state)',
    columns: [
      c('PRODUCT_ID', 'VARCHAR(8)', 'Product id'), c('NAME', 'VARCHAR(80)', 'Name'), c('DOMAIN', 'VARCHAR(40)', 'Domain'), c('VERSION', 'VARCHAR(16)', 'Version'),
      c('STATUS', 'VARCHAR(20)', 'Certified / In certification / Draft'), c('OWNER', 'VARCHAR(80)', 'Owner'), c('STEWARD', 'VARCHAR(80)', 'Steward'),
      c('SLA', 'VARCHAR(40)', 'Freshness SLA'), c('SEMANTIC_VIEW', 'VARCHAR(80)', 'Semantic view'), c('OUTPUT_PORT', 'VARCHAR(200)', 'Output port FQN'),
    ],
    rowCount: core.products.length, owner: 'DATA_STEWARD', lastAltered: now, upstream: [],
    rows: (live) => core.products.map((p) => ({
      PRODUCT_ID: p.id, NAME: p.name, DOMAIN: p.domain, VERSION: live.productVersion[p.id] ?? p.version, STATUS: live.productStatus[p.id] ?? p.status,
      OWNER: p.owner, STEWARD: p.steward, SLA: p.sla, SEMANTIC_VIEW: p.semanticView ?? null, OUTPUT_PORT: `${db}.DATA_PRODUCTS.${p.outputPort}`,
    })),
  });
  out.push({
    schema: 'DATA_PRODUCTS', name: 'DP_CONTRACT', layer: 'product', type: 'TABLE', comment: 'Versioned data contracts (YAML)',
    columns: [c('PRODUCT_ID', 'VARCHAR(8)', 'Product id'), c('CONTRACT_YAML', 'VARCHAR(16000)', 'Contract'), c('VERSION', 'VARCHAR(16)', 'Version'), c('EFFECTIVE_FROM', 'DATE', 'Effective from')],
    rowCount: core.products.length, owner: 'DATA_STEWARD', lastAltered: now, upstream: ['DATA_PRODUCTS.DP_REGISTRY'],
    rows: (live) => core.products.map((p) => ({ PRODUCT_ID: p.id, CONTRACT_YAML: p.contractYaml.split('\n').slice(0, 3).join(' ') + ' …', VERSION: live.productVersion[p.id] ?? p.version, EFFECTIVE_FROM: p.lastCertified ?? '2026-09-01' })),
  });

  // ---- AGENTS
  for (const a of core.agents) {
    const tools = a.tools
      .map((t) => `    - name: ${t.kind}_${t.target.toLowerCase()}\n      type: ${t.kind === 'cortex_analyst' ? 'cortex_analyst_text_to_sql' : t.kind === 'cortex_search' ? 'cortex_search' : 'generic_sql'}\n      resource: ${db}.${t.kind === 'cortex_analyst' ? 'SEMANTIC' : t.kind === 'cortex_search' ? 'CONTEXT' : 'GOVERNANCE'}.${t.target}`)
      .join('\n');
    const ins = core.context.instructions.filter((i) => i.agentId === a.id);
    out.push({
      schema: 'AGENTS', name: a.objectName, layer: 'agent', type: 'AGENT', comment: a.description,
      columns: [], rowCount: 0, owner: 'AI_PLATFORM_ADMIN', lastAltered: '2026-09-24 08:15:00',
      upstream: [
        ...a.tools.filter((t) => t.kind === 'cortex_analyst').map((t) => `SEMANTIC.${t.target}`),
        ...a.tools.filter((t) => t.kind === 'cortex_search').map((t) => `CONTEXT.${t.target}`),
        ...a.productIds.map((pid) => core.products.find((p) => p.id === pid)).filter(Boolean).map((p) => `DATA_PRODUCTS.${p!.outputPort}`),
        ...(a.tools.some((t) => t.kind === 'sql') ? ['GLOSSARY.BUSINESS_TERM', 'GLOSSARY.CDE_REGISTER', 'DATA_PRODUCTS.DP_REGISTRY'] : []),
      ],
      ddl: `CREATE OR REPLACE AGENT ${db}.AGENTS.${a.objectName}\n  COMMENT = ${q(a.description)}\nFROM SPECIFICATION $$\nmodels:\n  orchestration: auto\ninstructions:\n${ins.map((i) => `  ${i.type}: ${JSON.stringify(i.text)}`).join('\n')}\ntools:\n${tools}\n$$;`,
    });
  }
  out.push({
    schema: 'AGENTS', name: 'AGENT_REGISTRY', layer: 'agent', type: 'TABLE', comment: 'Registered agents with status and evaluation score',
    columns: [c('AGENT_NAME', 'VARCHAR(80)', 'Agent'), c('DOMAIN', 'VARCHAR(40)', 'Domain'), c('STATUS', 'VARCHAR(12)', 'Production / Pilot'), c('OWNER', 'VARCHAR(80)', 'Owner'), c('PRODUCTS_USED', 'VARCHAR(200)', 'Products'), c('EVAL_SCORE', 'NUMBER(5,1)', 'Eval accuracy %'), c('LAST_EVAL', 'TIMESTAMP_NTZ', 'Last evaluated')],
    rowCount: core.agents.length, owner: 'AI_PLATFORM_ADMIN', lastAltered: '2026-09-24 08:15:00', upstream: [],
    rows: () => core.agents.map((a) => ({ AGENT_NAME: a.objectName, DOMAIN: a.domain, STATUS: a.status, OWNER: 'AI_PLATFORM_ADMIN', PRODUCTS_USED: a.productIds.join(', ') || 'Glossary, Governance, DP registry', EVAL_SCORE: a.evalAccuracy, LAST_EVAL: '2026-09-27 22:00:00' })),
  });
  out.push({
    schema: 'AGENTS', name: 'AGENT_EVAL_RESULTS', layer: 'agent', type: 'TABLE', comment: 'Agent evaluation runs',
    columns: [c('AGENT_NAME', 'VARCHAR(80)', 'Agent'), c('EVAL_SET', 'VARCHAR(40)', 'Evaluation set'), c('QUESTIONS', 'NUMBER', 'Questions'), c('CORRECT', 'NUMBER', 'Correct'), c('ACCURACY_PCT', 'NUMBER(5,1)', 'Accuracy %'), c('RUN_AT', 'TIMESTAMP_NTZ', 'Run at')],
    rowCount: core.agents.length * 3, owner: 'AI_PLATFORM_ADMIN', lastAltered: '2026-09-27 22:00:00', upstream: ['AGENTS.AGENT_REGISTRY'],
    rows: () => core.agents.flatMap((a) => [3, 2, 1].map((w, i) => {
      const acc = Math.max(70, a.evalAccuracy - w * 1.5 + (i === 2 ? 1.5 : 0));
      const correct = Math.round((a.evalQuestions * acc) / 100);
      return { AGENT_NAME: a.objectName, EVAL_SET: `${a.objectName.replace('AGT_', '').toLowerCase()}_golden_v${i + 1}`, QUESTIONS: a.evalQuestions, CORRECT: correct, ACCURACY_PCT: Math.round((correct / a.evalQuestions) * 1000) / 10, RUN_AT: `2026-09-${String(13 + i * 7).padStart(2, '0')} 22:00:00` };
    })),
  });

  // ---- GOVERNANCE
  const tagObj = (name: string, comment: string, values: string[]): SfObject => ({
    schema: 'GOVERNANCE', name, layer: 'gov', type: 'TAG', comment, columns: [c('ALLOWED_VALUES', 'VARCHAR', values.join(', '))],
    rowCount: 0, owner: 'GOVERNANCE_ADMIN', lastAltered: '2026-08-30 12:00:00', upstream: [],
    ddl: `CREATE OR REPLACE TAG ${db}.GOVERNANCE.${name}\n  ALLOWED_VALUES ${values.map(q).join(', ')}\n  COMMENT = ${q(comment)};`,
  });
  for (const s of sensitive) {
    out.push(tagObj(s, `${s} classification tag applied to sensitive columns`, ['NAME', 'EMAIL', 'ADDRESS', 'IDENTIFIER', 'OTHER']));
  }
  out.push(tagObj('CDE', 'Critical data element flag', ['TRUE']));
  out.push(tagObj('DOMAIN', 'Owning business domain', [...new Set(core.products.map((p) => p.domain.split(' /')[0]))]));
  out.push(tagObj('CERTIFICATION', 'Data product certification level', ['GOLD', 'SILVER', 'NONE']));

  const maskingNames = [...new Set(sensitive.map((s) => core.maskingPolicies[s] ?? core.maskingPolicy))];
  for (const mp of maskingNames) {
    const classes = sensitive.filter((s) => (core.maskingPolicies[s] ?? core.maskingPolicy) === mp);
    const unmaskRoles = core.personas.filter((p) => classes.every((cl: SensitiveClass) => p.unmasked.includes(cl))).map((p) => p.roleId);
    out.push({
      schema: 'GOVERNANCE', name: mp, layer: 'gov', type: 'MASKING POLICY', comment: `Masks ${classes.join(', ')} columns; unmasks for ${unmaskRoles.join(', ')} only`,
      columns: [], rowCount: 0, owner: 'GOVERNANCE_ADMIN', lastAltered: '2026-08-30 12:00:00', upstream: [],
      ddl: `CREATE OR REPLACE MASKING POLICY ${db}.GOVERNANCE.${mp}\n  AS (val VARCHAR) RETURNS VARCHAR ->\n  CASE\n    WHEN IS_ROLE_IN_SESSION(${unmaskRoles.map(q).join(') OR IS_ROLE_IN_SESSION(')}) THEN val\n    WHEN val ILIKE '%@%' THEN LEFT(val, 1) || '****@****.com'\n    ELSE '****'\n  END\n  COMMENT = 'Masks ${classes.join(', ')} for every role except the data steward';`,
    });
  }
  const filtered = core.personas.filter((p) => p.rowFilter);
  out.push({
    schema: 'GOVERNANCE', name: core.rowAccessPolicy, layer: 'gov', type: 'ROW ACCESS POLICY', comment: 'Maps role → allowed region / business unit values',
    columns: [], rowCount: 0, owner: 'GOVERNANCE_ADMIN', lastAltered: '2026-08-30 12:00:00', upstream: [],
    ddl: `CREATE OR REPLACE ROW ACCESS POLICY ${db}.GOVERNANCE.${core.rowAccessPolicy}\n  AS (scope_value VARCHAR) RETURNS BOOLEAN ->\n${filtered.map((p) => `    (IS_ROLE_IN_SESSION('${p.roleId}') AND scope_value IN (${p.rowFilter!.allowed.map(q).join(', ')}))`).join('\n    OR\n')}\n    OR NOT (${filtered.map((p) => `IS_ROLE_IN_SESSION('${p.roleId}')`).join(' OR ') || 'FALSE'})\n  COMMENT = 'Row access by role';`,
  });
  out.push({
    schema: 'GOVERNANCE', name: 'DMF_RESULTS', layer: 'gov', type: 'TABLE', comment: 'Data metric function results',
    columns: [c('OBJECT_FQN', 'VARCHAR(200)', 'Object'), c('METRIC', 'VARCHAR(30)', 'NULL_COUNT / DUPLICATE_COUNT / FRESHNESS / ROW_COUNT'), c('VALUE', 'NUMBER', 'Measured value'), c('THRESHOLD', 'VARCHAR(30)', 'Threshold'), c('STATUS', 'VARCHAR(6)', 'pass / warn / fail'), c('MEASURED_AT', 'TIMESTAMP_NTZ', 'Measured at')],
    rowCount: core.dmf.length, owner: 'GOVERNANCE_ADMIN', lastAltered: now, upstream: [],
    rows: () => core.dmf.map((d) => ({ OBJECT_FQN: `${db}.${d.fqn}`, METRIC: d.metric, VALUE: d.value, THRESHOLD: d.threshold, STATUS: d.status, MEASURED_AT: d.measuredAt })),
  });
  out.push({
    schema: 'GOVERNANCE', name: 'ACCESS_HISTORY_V', layer: 'gov', type: 'VIEW', comment: 'Access history (from ACCOUNT_USAGE.ACCESS_HISTORY)',
    columns: [c('QUERY_ID', 'VARCHAR(40)', 'Query id'), c('ROLE', 'VARCHAR(40)', 'Role'), c('OBJECT_FQN', 'VARCHAR(200)', 'Object'), c('COLUMNS', 'VARCHAR(400)', 'Columns accessed'), c('QUERY_TS', 'TIMESTAMP_NTZ', 'Query time')],
    rowCount: 4_812_330, owner: 'GOVERNANCE_ADMIN', lastAltered: now, upstream: ['ext:SNOWFLAKE.ACCOUNT_USAGE'],
    rows: () => core.accessHistory.map((h) => ({ QUERY_ID: h.queryId, ROLE: h.role, OBJECT_FQN: `${db}.${h.fqn}`, COLUMNS: h.columns, QUERY_TS: h.ts })) as Row[],
  });

  return out;
}
