import type { Agent } from '../../types';

export const AGENTS: Agent[] = [
  { id: 'AG-01', name: 'Constituent Services Assistant', objectName: 'AGT_CONSTITUENT_SERVICES', domain: 'Constituent', status: 'Production',
    description: 'Answers questions about constituents, program enrollment, renewals, 311 service requests and integrity reviews in your districts.',
    productIds: ['DP-01', 'DP-04', 'DP-05'],
    tools: [{ kind: 'cortex_analyst', target: 'SV_CONSTITUENT_360' }, { kind: 'cortex_analyst', target: 'SV_PROGRAM_INTEGRITY' }, { kind: 'cortex_search', target: 'CS_WCS_DOCS' }],
    instructionIds: ['AI-01', 'AI-02', 'AI-03', 'AI-04'], evalAccuracy: 93, evalQuestions: 50,
    scenarioIds: ['S-01', 'S-02', 'S-03', 'S-04', 'S-05'], kpiIds: ['K-01', 'K-02', 'K-03', 'K-04', 'K-05', 'K-06', 'K-07', 'K-08', 'K-22', 'K-23', 'K-24'] },
  { id: 'AG-02', name: 'Program Analyst', objectName: 'AGT_PROGRAM_ANALYST', domain: 'Program operations', status: 'Production',
    description: 'Answers questions about applications, processing timeliness, case backlog, caseload, cost per case and staffing.',
    productIds: ['DP-02', 'DP-06'],
    tools: [{ kind: 'cortex_analyst', target: 'SV_CASE_MANAGEMENT' }, { kind: 'cortex_search', target: 'CS_WCS_DOCS' }],
    instructionIds: ['AI-05', 'AI-06', 'AI-07', 'AI-08'], evalAccuracy: 95, evalQuestions: 40,
    scenarioIds: ['S-06', 'S-07', 'S-08', 'S-09'], kpiIds: ['K-09', 'K-10', 'K-11', 'K-12', 'K-13', 'K-14', 'K-15', 'K-21', 'K-25', 'K-26'] },
  { id: 'AG-03', name: 'Fraud & Integrity Copilot', objectName: 'AGT_FRAUD_INTEGRITY', domain: 'Payments & integrity', status: 'Production',
    description: 'Answers questions about benefits paid, payment accuracy, improper payments and overpayment recovery.',
    productIds: ['DP-03', 'DP-05'],
    tools: [{ kind: 'cortex_analyst', target: 'SV_BENEFIT_PAYMENTS' }, { kind: 'cortex_search', target: 'CS_WCS_DOCS' }],
    instructionIds: ['AI-09', 'AI-10', 'AI-11', 'AI-12'], evalAccuracy: 92, evalQuestions: 35,
    scenarioIds: ['S-10', 'S-11', 'S-12'], kpiIds: ['K-16', 'K-17', 'K-18', 'K-19', 'K-20', 'K-22', 'K-23', 'K-24'] },
  { id: 'AG-04', name: 'Data Steward Assistant', objectName: 'AGT_DATA_STEWARD', domain: 'Governance', status: 'Pilot',
    description: 'Finds governance gaps: CDEs without stewards, term usage and certification blockers.',
    productIds: [],
    tools: [{ kind: 'sql', target: 'GLOSSARY_GOVERNANCE_DP_REGISTRY' }],
    instructionIds: ['AI-13', 'AI-14', 'AI-15', 'AI-16'], evalAccuracy: 90, evalQuestions: 25,
    scenarioIds: ['S-13', 'S-14', 'S-15'], kpiIds: [] },
];
