import type { GlossaryTerm } from '../../types';

const G = 'CONFORMED_GOLD';
const S = 'CURATED_SILVER';
const P = 'DATA_PRODUCTS';
const term = (t: Omit<GlossaryTerm, 'related' | 'synonyms'> & Partial<Pick<GlossaryTerm, 'related' | 'synonyms'>>): GlossaryTerm => ({ related: [], synonyms: [], ...t });

export const GLOSSARY: GlossaryTerm[] = [
  term({ id: 'T-001', term: 'Constituent', domain: 'Constituent', owner: 'Constituent Services (N. Bergstrom)', steward: 'O. Fitzgerald', status: 'Approved', isCde: true,
    definition: 'A resident or household member with a record in the county case management system, whether or not they currently receive a service.', formula: 'One record per CONSTITUENT_ID; the current SCD2 version represents the constituent today.',
    synonyms: ['resident', 'client', 'person served'], related: ['T-002', 'T-003'],
    mappings: [{ fqn: `${G}.DIM_CONSTITUENT`, column: 'CONSTITUENT_ID', kind: 'defines' }, { fqn: `${S}.CONSTITUENT`, column: 'CONSTITUENT_ID', kind: 'defines' }],
    metricRefs: [], dqRules: ['CONSTITUENT_ID not null', 'CONSTITUENT_ID unique where IS_CURRENT'], dqScore: 99.7 }),
  term({ id: 'T-002', term: 'Active Constituent', domain: 'Constituent', owner: 'Constituent Services (N. Bergstrom)', steward: 'O. Fitzgerald', status: 'Approved', isCde: true,
    definition: 'A constituent whose status is Active, who has at least one open program case, and who has had a contact (application, renewal, payment or visit) in the last 12 months.', formula: 'status = Active AND open cases ≥ 1 AND last contact > as-of date − 365 days',
    synonyms: ['active client', 'active resident', 'people served'], related: ['T-001', 'T-005', 'T-027'],
    mappings: [{ fqn: `${S}.CONSTITUENT`, column: 'CONSTITUENT_STATUS', kind: 'filters' }, { fqn: `${G}.FCT_CASE`, column: 'CASE_STATUS', kind: 'filters' }, { fqn: `${P}.DP_CONSTITUENT_360`, column: 'IS_ACTIVE', kind: 'derives' }],
    metricRefs: ['SV_CONSTITUENT_360.active_constituents'], dqRules: ['Status in (Active, Inactive)', 'Last contact refreshed daily'], dqScore: 98.8 }),
  term({ id: 'T-003', term: 'Service District', domain: 'Enterprise', owner: 'County Administrator’s Office (P. Lindgren)', steward: 'O. Fitzgerald', status: 'Approved', isCde: true,
    definition: 'One of the county’s four service districts — North, Central, South and Riverside — that own offices, caseworkers and constituents.', formula: 'Mapped from DIST_CD: ND → North District, CD → Central District, SD → South District, RD → Riverside District',
    synonyms: ['district', 'service area', 'region'], related: ['T-012'],
    mappings: [{ fqn: `${G}.DIM_OFFICE`, column: 'DISTRICT', kind: 'defines' }, { fqn: `${G}.DIM_CONSTITUENT`, column: 'DISTRICT', kind: 'defines' }, { fqn: `${G}.FCT_CASE`, column: 'DISTRICT', kind: 'derives' }],
    metricRefs: [], dqRules: ['DISTRICT in reference list'], dqScore: 100 }),
  term({ id: 'T-004', term: 'Benefit Program', domain: 'Programs', owner: 'Program Policy (M. Achebe)', steward: 'S. Brandt', status: 'Approved', isCde: true,
    definition: 'A county-administered benefit: Food Assistance, Cash Assistance, Medical Assistance, Child Care Subsidy or Energy Assistance.', formula: 'PROGRAM_CODE in (FA, CA, MA, CCS, EA)',
    synonyms: ['program', 'benefit'], related: ['T-005', 'T-007'],
    mappings: [{ fqn: `${G}.DIM_PROGRAM`, column: 'PROGRAM_CODE', kind: 'defines' }, { fqn: `${G}.DIM_PROGRAM`, column: 'PROGRAM_NAME', kind: 'defines' }],
    metricRefs: [], dqRules: ['PROGRAM_CODE in reference list'], dqScore: 100 }),
  term({ id: 'T-005', term: 'Case', domain: 'Case management', owner: 'Human Services Operations (L. Ortega)', steward: 'S. Brandt', status: 'Approved', isCde: true,
    definition: 'A constituent’s enrollment in one benefit program, managed by an assigned caseworker from opening to closure.', formula: 'One row per CASE_ID; open when CASE_STATUS = Open',
    synonyms: ['program case', 'enrollment'], related: ['T-004', 'T-006', 'T-012'],
    mappings: [{ fqn: `${G}.FCT_CASE`, column: 'CASE_ID', kind: 'defines' }, { fqn: `${G}.FCT_CASE`, column: 'CASE_STATUS', kind: 'defines' }, { fqn: `${S}.CASE_RECORD`, column: 'CASE_ID', kind: 'defines' }],
    metricRefs: ['SV_CASE_MANAGEMENT.open_cases'], dqRules: ['CASE_ID unique', 'Closed date ≥ opened date'], dqScore: 99.5 }),
  term({ id: 'T-006', term: 'Case Backlog', domain: 'Case management', owner: 'Human Services Operations (L. Ortega)', steward: 'S. Brandt', status: 'Approved', isCde: true,
    definition: 'Open cases with an application, renewal or reported change awaiting a caseworker decision at the end of the period.', formula: "count of open cases where PENDING_ACTION <> 'NONE'",
    synonyms: ['backlog', 'pending work', 'work queue'], related: ['T-005', 'T-012'],
    mappings: [{ fqn: `${G}.FCT_CASE`, column: 'PENDING_ACTION', kind: 'defines' }, { fqn: `${S}.CASE_RECORD`, column: 'PENDING_ACTION', kind: 'derives' }],
    metricRefs: ['SV_CASE_MANAGEMENT.case_backlog'], dqRules: ['PENDING_ACTION in (NONE, APPLICATION, RENEWAL, CHANGE)', 'PENDING_SINCE present when pending'], dqScore: 98.6 }),
  term({ id: 'T-007', term: 'Benefit Application', domain: 'Eligibility', owner: 'Eligibility Services (R. Okonkwo)', steward: 'K. Yamamoto', status: 'Approved', isCde: true,
    definition: 'A request for a benefit program submitted by or for a constituent, from receipt through the eligibility decision.', formula: 'One row per APPLICATION_ID',
    synonyms: ['application', 'benefit applications', 'claim'], related: ['T-008', 'T-009', 'T-011'],
    mappings: [{ fqn: `${G}.FCT_APPLICATION`, column: 'APPLICATION_ID', kind: 'defines' }, { fqn: `${S}.BENEFIT_APPLICATION`, column: 'APPLICATION_ID', kind: 'defines' }],
    metricRefs: ['SV_CASE_MANAGEMENT.applications_received'], dqRules: ['APPLICATION_ID unique', 'RECEIVED_DATE not null'], dqScore: 99.6 }),
  term({ id: 'T-008', term: 'Complete Application', domain: 'Eligibility', owner: 'Eligibility Services (R. Okonkwo)', steward: 'K. Yamamoto', status: 'Approved', isCde: true,
    definition: 'An application for which every required verification (identity, income, residency, household) has been received; the processing clock starts on this date.', formula: 'COMPLETE_DATE = date the last required verification was received',
    synonyms: ['completed application', 'complete date'], related: ['T-007', 'T-009'],
    mappings: [{ fqn: `${G}.FCT_APPLICATION`, column: 'COMPLETE_DATE', kind: 'defines' }, { fqn: `${S}.BENEFIT_APPLICATION`, column: 'COMPLETE_DATE', kind: 'derives' }],
    metricRefs: [], dqRules: ['COMPLETE_DATE ≥ RECEIVED_DATE', 'Null only while verifications are outstanding'], dqScore: 97.9 }),
  term({ id: 'T-009', term: 'Processing Days', domain: 'Eligibility', owner: 'Eligibility Services (R. Okonkwo)', steward: 'K. Yamamoto', status: 'Approved', isCde: true,
    definition: 'The number of business days from a complete application to the eligibility decision. Weekends and county holidays are not counted, and days spent waiting for the applicant’s documents are not counted.', formula: 'Business days in (COMPLETE_DATE, DECISION_DATE]; an application exceeds the standard when processing days > 30',
    synonyms: ['processing time', 'days to decide', 'processing standard', '30-day processing standard'], related: ['T-008', 'T-010', 'T-007'],
    mappings: [{ fqn: `${G}.FCT_APPLICATION`, column: 'PROCESSING_BUSINESS_DAYS', kind: 'defines' }, { fqn: `${G}.FCT_APPLICATION`, column: 'COMPLETE_DATE', kind: 'derives' }, { fqn: `${G}.DIM_DATE`, column: 'IS_BUSINESS_DAY', kind: 'filters' }],
    metricRefs: ['SV_CASE_MANAGEMENT.applications_over_standard', 'SV_CASE_MANAGEMENT.avg_processing_days'], dqRules: ['PROCESSING_BUSINESS_DAYS ≥ 0', 'Present for every decided application', 'Holiday calendar refreshed each January'], dqScore: 99.2 }),
  term({ id: 'T-010', term: 'Timely Processing Rate', domain: 'Eligibility', owner: 'Eligibility Services (R. Okonkwo)', steward: 'K. Yamamoto', status: 'Approved', isCde: true,
    definition: 'The share of decided applications whose processing days are within the 30-business-day standard.', formula: 'Applications with processing days ≤ 30 ÷ applications decided × 100',
    synonyms: ['timeliness', 'on-time processing'], related: ['T-009'],
    mappings: [{ fqn: `${G}.FCT_APPLICATION`, column: 'WITHIN_STANDARD', kind: 'defines' }, { fqn: `${G}.DIM_PROGRAM`, column: 'PROCESSING_STANDARD_DAYS', kind: 'filters' }],
    metricRefs: ['SV_CASE_MANAGEMENT.timely_processing_rate'], dqRules: ['Derived from PROCESSING_BUSINESS_DAYS'], dqScore: 99.2 }),
  term({ id: 'T-011', term: 'Approval Rate', domain: 'Eligibility', owner: 'Eligibility Services (R. Okonkwo)', steward: 'K. Yamamoto', status: 'Approved', isCde: false,
    definition: 'Approved applications as a share of applications approved or denied; withdrawn applications are excluded.', formula: 'Approved ÷ (Approved + Denied) × 100',
    synonyms: ['grant rate'], related: ['T-007'],
    mappings: [{ fqn: `${G}.FCT_APPLICATION`, column: 'DECISION', kind: 'defines' }],
    metricRefs: ['SV_CASE_MANAGEMENT.approval_rate'] }),
  term({ id: 'T-012', term: 'Caseload', domain: 'Case management', owner: 'Human Services Operations (L. Ortega)', steward: 'S. Brandt', status: 'Approved', isCde: false,
    definition: 'Open cases per filled caseworker position.', formula: 'Open cases ÷ filled caseworker positions',
    synonyms: ['cases per worker', 'workload'], related: ['T-005', 'T-024'],
    mappings: [{ fqn: `${G}.DIM_OFFICE`, column: 'CASEWORKERS', kind: 'derives' }, { fqn: `${G}.FCT_CASE`, column: 'CASEWORKER_ID', kind: 'derives' }],
    metricRefs: ['SV_CASE_MANAGEMENT.avg_caseload'] }),
  term({ id: 'T-013', term: 'Benefit Payment', domain: 'Payments', owner: 'Finance – Benefit Disbursement (A. Kowalczyk)', steward: 'J. Alvarez', status: 'Approved', isCde: true,
    definition: 'A benefit amount issued on a case for a benefit month, by EBT, direct deposit or provider disbursement.', formula: 'One row per PAYMENT_ID; PAYMENT_AMOUNT as issued',
    synonyms: ['payment', 'issuance', 'benefits paid'], related: ['T-014', 'T-015'],
    mappings: [{ fqn: `${G}.FCT_PAYMENT`, column: 'PAYMENT_AMOUNT', kind: 'defines' }, { fqn: `${S}.BENEFIT_PAYMENT`, column: 'PAYMENT_AMOUNT', kind: 'derives' }],
    metricRefs: ['SV_BENEFIT_PAYMENTS.total_benefits_paid', 'SV_BENEFIT_PAYMENTS.payments_issued'], dqRules: ['PAYMENT_AMOUNT > 0', 'One payment per case per benefit month'], dqScore: 99.4 }),
  term({ id: 'T-014', term: 'Payment Accuracy', domain: 'Payments', owner: 'Finance – Benefit Disbursement (A. Kowalczyk)', steward: 'J. Alvarez', status: 'Approved', isCde: true,
    definition: 'The share of benefit payments issued in the correct amount to an eligible recipient, as determined by quality-control review.', formula: 'Payments without an improper finding ÷ payments issued × 100',
    synonyms: ['accuracy rate', 'payment accuracy rate'], related: ['T-015', 'T-013'],
    mappings: [{ fqn: `${G}.FCT_PAYMENT`, column: 'IS_IMPROPER', kind: 'filters' }],
    metricRefs: ['SV_BENEFIT_PAYMENTS.payment_accuracy_rate'], dqRules: ['IS_IMPROPER not null after QC sampling'], dqScore: 98.1 }),
  term({ id: 'T-015', term: 'Improper Payment', domain: 'Payments', owner: 'Finance – Benefit Disbursement (A. Kowalczyk)', steward: 'J. Alvarez', status: 'Approved', isCde: true,
    definition: 'A payment that should not have been made or was made in the wrong amount — overpayments and underpayments both count.', formula: 'Improper payment rate = Σ IMPROPER_AMOUNT ÷ Σ PAYMENT_AMOUNT × 100',
    synonyms: ['payment error', 'improper payments'], related: ['T-014', 'T-021'],
    mappings: [{ fqn: `${G}.FCT_PAYMENT`, column: 'IS_IMPROPER', kind: 'defines' }, { fqn: `${G}.FCT_PAYMENT`, column: 'IMPROPER_AMOUNT', kind: 'defines' }],
    metricRefs: ['SV_BENEFIT_PAYMENTS.improper_payment_rate', 'SV_BENEFIT_PAYMENTS.improper_payment_amount'], dqRules: ['IMPROPER_AMOUNT ≤ PAYMENT_AMOUNT', 'ERROR_TYPE present when improper'], dqScore: 97.8 }),
  term({ id: 'T-016', term: 'On-time Payment', domain: 'Payments', owner: 'Finance – Benefit Disbursement (A. Kowalczyk)', steward: 'J. Alvarez', status: 'Approved', isCde: false,
    definition: 'A payment issued on or before its scheduled issuance date.', formula: 'ISSUED_ON_TIME = TRUE',
    synonyms: ['timely payment'], related: ['T-013'],
    mappings: [{ fqn: `${G}.FCT_PAYMENT`, column: 'ISSUED_ON_TIME', kind: 'defines' }],
    metricRefs: ['SV_BENEFIT_PAYMENTS.on_time_payment_rate'] }),
  term({ id: 'T-017', term: 'Service Request (311)', domain: 'Constituent', owner: '311 Contact Center (D. Harrow)', steward: 'O. Fitzgerald', status: 'Approved', isCde: true,
    definition: 'A non-emergency request or report from a resident logged through 311 by phone, mobile app, web or walk-in.', formula: 'One row per SR_ID; duplicates merged into the parent request',
    synonyms: ['311 request', 'service request', 'ticket'], related: ['T-018', 'T-019'],
    mappings: [{ fqn: `${G}.FCT_SERVICE_REQUEST`, column: 'SR_ID', kind: 'defines' }, { fqn: `${S}.SERVICE_REQUEST`, column: 'SR_ID', kind: 'defines' }],
    metricRefs: ['SV_CONSTITUENT_360.service_requests', 'SV_CONSTITUENT_360.reopen_rate'], dqRules: ['SR_ID unique', 'REQUEST_TYPE in standard list'], dqScore: 99.0 }),
  term({ id: 'T-018', term: '311 Resolution Time', domain: 'Constituent', owner: '311 Contact Center (D. Harrow)', steward: 'O. Fitzgerald', status: 'Approved', isCde: true,
    definition: 'Calendar days from the creation of a 311 request to its closure; on-time when closed within the SLA for its request type.', formula: 'CLOSED_TS − CREATED_TS in days; on time when ≤ type SLA',
    synonyms: ['resolution time', 'time to close', '311 turnaround'], related: ['T-017'],
    mappings: [{ fqn: `${G}.FCT_SERVICE_REQUEST`, column: 'RESOLUTION_DAYS', kind: 'defines' }, { fqn: `${G}.FCT_SERVICE_REQUEST`, column: 'WITHIN_SLA', kind: 'derives' }],
    metricRefs: ['SV_CONSTITUENT_360.avg_resolution_days', 'SV_CONSTITUENT_360.on_time_resolution_rate'], dqRules: ['CLOSED_TS ≥ CREATED_TS'], dqScore: 98.9 }),
  term({ id: 'T-019', term: 'Constituent Satisfaction', domain: 'Constituent', owner: '311 Contact Center (D. Harrow)', steward: 'O. Fitzgerald', status: 'Draft', isCde: false,
    definition: 'The share of post-closure 311 survey responses scoring 4 or 5 on a five-point scale. Draft: the survey method and response weighting are under review.', formula: 'Responses with score ≥ 4 ÷ responses × 100',
    synonyms: ['csat', 'satisfaction', 'resident satisfaction'], related: ['T-017'],
    mappings: [{ fqn: `${G}.FCT_SERVICE_REQUEST`, column: 'SURVEY_SCORE', kind: 'defines' }],
    metricRefs: ['SV_CONSTITUENT_360.constituent_satisfaction'] }),
  term({ id: 'T-020', term: 'Integrity Flag', domain: 'Program integrity', owner: 'Program Integrity Unit (V. Szabo)', steward: 'J. Alvarez', status: 'Approved', isCde: true,
    definition: 'A data-match or referral finding that places a paying case under program integrity review (open review or referred for investigation).', formula: "Flagged for review when FLAG_STATUS in ('Open review', 'Referred')",
    synonyms: ['integrity review', 'fraud flag', 'flagged case'], related: ['T-021', 'T-015'],
    mappings: [{ fqn: `${G}.FCT_PAYMENT`, column: 'INTEGRITY_FLAG', kind: 'defines' }, { fqn: `${G}.FCT_PAYMENT`, column: 'FLAG_STATUS', kind: 'filters' }, { fqn: `${P}.DP_PROGRAM_INTEGRITY`, column: 'FLAG_STATUS', kind: 'derives' }],
    metricRefs: ['SV_PROGRAM_INTEGRITY.cases_flagged', 'SV_PROGRAM_INTEGRITY.integrity_flag_rate'], dqRules: ['FLAG_REASON present when flagged', 'Status in reference list'], dqScore: 96.4 }),
  term({ id: 'T-021', term: 'Overpayment Recovery', domain: 'Program integrity', owner: 'Program Integrity Unit (V. Szabo)', steward: 'J. Alvarez', status: 'Approved', isCde: true,
    definition: 'Amounts recovered against overpayments established on a case, by repayment, benefit offset or tax intercept.', formula: 'Recovery rate = Σ RECOVERED_AMOUNT ÷ Σ OVERPAYMENT_AMOUNT × 100',
    synonyms: ['recovery rate', 'overpayment collections'], related: ['T-020', 'T-015'],
    mappings: [{ fqn: `${G}.FCT_PAYMENT`, column: 'OVERPAYMENT_AMOUNT', kind: 'derives' }, { fqn: `${G}.FCT_PAYMENT`, column: 'RECOVERED_AMOUNT', kind: 'derives' }],
    metricRefs: ['SV_PROGRAM_INTEGRITY.recovery_rate', 'SV_PROGRAM_INTEGRITY.overpayments_established'], dqRules: ['RECOVERED_AMOUNT ≤ OVERPAYMENT_AMOUNT'], dqScore: 95.9 }),
  term({ id: 'T-022', term: 'Cost per Case', domain: 'Finance', owner: 'Budget Office (E. Marchetti)', steward: null, status: 'Approved', isCde: true,
    definition: 'Administrative expenditure over the trailing twelve months divided by open cases at the end of the period.', formula: 'Σ ACTUAL_AMOUNT (administrative departments, trailing 12 months) ÷ open cases',
    synonyms: ['administrative cost per case', 'unit cost'], related: ['T-005', 'T-023'],
    mappings: [{ fqn: `${G}.FCT_BUDGET`, column: 'ACTUAL_AMOUNT', kind: 'derives' }, { fqn: `${G}.FCT_BUDGET`, column: 'IS_ADMINISTRATIVE', kind: 'filters' }, { fqn: `${P}.DP_WORKFORCE_BUDGET`, column: 'COST_PER_CASE', kind: 'defines' }],
    metricRefs: ['DP_WORKFORCE_BUDGET.cost_per_case'], dqRules: ['Open cases > 0', 'Administrative flag on every cost centre'], dqScore: 90.6 }),
  term({ id: 'T-023', term: 'Budget Execution', domain: 'Finance', owner: 'Budget Office (E. Marchetti)', steward: 'J. Alvarez', status: 'Approved', isCde: false,
    definition: 'Actual expenditure as a share of the adopted budget for the same months.', formula: 'Σ ACTUAL_AMOUNT ÷ Σ BUDGET_AMOUNT × 100',
    synonyms: ['spend vs budget', 'budget utilisation'], related: ['T-022'],
    mappings: [{ fqn: `${G}.FCT_BUDGET`, column: 'BUDGET_AMOUNT', kind: 'defines' }, { fqn: `${P}.DP_WORKFORCE_BUDGET`, column: 'ACTUAL_AMOUNT', kind: 'derives' }],
    metricRefs: ['DP_WORKFORCE_BUDGET.budget_execution_pct'] }),
  term({ id: 'T-024', term: 'Caseworker Vacancy Rate', domain: 'Finance', owner: 'Human Resources (T. Nakamura)', steward: 'S. Brandt', status: 'Approved', isCde: false,
    definition: 'Authorised caseworker positions that are unfilled, as a share of authorised positions, at month end.', formula: '(FTE_BUDGETED − FTE_FILLED) ÷ FTE_BUDGETED × 100, Eligibility Services and Case Management',
    synonyms: ['vacancy rate', 'vacancies'], related: ['T-012'],
    mappings: [{ fqn: `${G}.FCT_BUDGET`, column: 'FTE_FILLED', kind: 'derives' }, { fqn: `${P}.DP_WORKFORCE_BUDGET`, column: 'VACANCY_PCT', kind: 'defines' }],
    metricRefs: ['DP_WORKFORCE_BUDGET.vacancy_pct'] }),
  term({ id: 'T-025', term: 'Digital Self-Service', domain: 'Constituent', owner: 'Constituent Services (N. Bergstrom)', steward: 'O. Fitzgerald', status: 'Approved', isCde: false,
    definition: 'Applications submitted online by the constituent, as a share of all applications received.', formula: "Applications with CHANNEL = 'Online' ÷ applications × 100",
    synonyms: ['online applications', 'digital channel'], related: ['T-007'],
    mappings: [{ fqn: `${G}.FCT_APPLICATION`, column: 'CHANNEL', kind: 'defines' }, { fqn: `${G}.FCT_SERVICE_REQUEST`, column: 'CHANNEL', kind: 'derives' }],
    metricRefs: ['SV_CONSTITUENT_360.digital_self_service_rate'] }),
  term({ id: 'T-026', term: 'Government Identifier', domain: 'Governance', owner: 'Records & Privacy Office (H. Mbeki)', steward: 'O. Fitzgerald', status: 'Approved', isCde: false,
    definition: 'A government-issued personal identifier captured at intake for identity and data matching. Classified GOV_ID: masked for every role except the data steward.', formula: 'Tagged GOV_ID; MP_MASK_GOV_ID attached',
    synonyms: ['gov id', 'government id', 'national identifier'], related: ['T-001', 'T-020'],
    mappings: [{ fqn: `${G}.DIM_CONSTITUENT`, column: 'GOV_ID', kind: 'defines' }, { fqn: `${G}.FCT_PAYMENT`, column: 'CASE_GOV_ID', kind: 'derives' }, { fqn: `${S}.CONSTITUENT`, column: 'GOV_ID', kind: 'defines' }],
    metricRefs: [] }),
  term({ id: 'T-027', term: 'Multi-program Enrollment', domain: 'Constituent', owner: 'Constituent Services (N. Bergstrom)', steward: 'O. Fitzgerald', status: 'Approved', isCde: false,
    definition: 'An active constituent enrolled in two or more benefit programs at the same time.', formula: 'Open program cases ≥ 2',
    synonyms: ['more than one program', 'multiple programs'], related: ['T-002', 'T-005'],
    mappings: [{ fqn: `${P}.DP_CONSTITUENT_360`, column: 'PROGRAMS_ENROLLED', kind: 'defines' }],
    metricRefs: ['SV_CONSTITUENT_360.multi_program_rate'] }),
];
