import type { GlossaryTerm } from '../../types';

const G = 'CONFORMED_GOLD';
const term = (t: Omit<GlossaryTerm, 'related' | 'synonyms'> & Partial<Pick<GlossaryTerm, 'related' | 'synonyms'>>): GlossaryTerm => ({ related: [], synonyms: [], ...t });

export const GLOSSARY: GlossaryTerm[] = [
  term({ id: 'T-001', term: 'Policyholder', domain: 'Policyholder', owner: 'C. Whitaker', steward: 'H. Quansah', status: 'Approved', isCde: true,
    definition: 'The person or organisation named as the insured on one or more Sentinel Mutual policies.', formula: 'One record per POLICYHOLDER_ID; the current SCD2 version of each policy represents the policyholder today.',
    synonyms: ['named insured', 'insured', 'member'], related: ['T-002', 'T-016'],
    mappings: [{ fqn: `${G}.DIM_POLICY`, column: 'POLICYHOLDER_ID', kind: 'defines' }, { fqn: 'CURATED_SILVER.POLICY', column: 'POLICYHOLDER_ID', kind: 'defines' }, { fqn: 'DATA_PRODUCTS.DP_POLICYHOLDER_360', column: 'TENURE_YEARS', kind: 'derives' }],
    metricRefs: ['SV_POLICYHOLDER_360.avg_tenure_years'], dqRules: ['POLICYHOLDER_ID not null', 'One current version per policy'], dqScore: 99.7 }),
  term({ id: 'T-002', term: 'Policy in Force', domain: 'Policyholder', owner: 'C. Whitaker', steward: 'H. Quansah', status: 'Approved', isCde: true,
    definition: 'A policy whose status is In force, whose current term has started on or before the as-of date, and which has not lapsed or been cancelled.', formula: "POLICY_STATUS = 'In force' AND TERM_EFFECTIVE_DATE <= as-of date",
    synonyms: ['PIF', 'in-force policy', 'active policy'], related: ['T-001', 'T-016'],
    mappings: [{ fqn: 'CURATED_SILVER.POLICY', column: 'POLICY_STATUS', kind: 'filters' }, { fqn: `${G}.DIM_POLICY`, column: 'POLICY_STATUS', kind: 'filters' }, { fqn: 'DATA_PRODUCTS.DP_POLICYHOLDER_360', column: 'IS_IN_FORCE', kind: 'derives' }],
    metricRefs: ['SV_POLICYHOLDER_360.policies_in_force'], dqRules: ['Status in (In force, Lapsed, Cancelled)', 'Term effective date not in future for In force'], dqScore: 99.4 }),
  term({ id: 'T-003', term: 'Region', domain: 'Enterprise', owner: 'Corporate Finance (N. Feld)', steward: 'H. Quansah', status: 'Approved', isCde: true,
    definition: 'One of Sentinel Mutual’s four state groups used for management reporting and access control: Northeast, Midwest, South and West.', formula: 'Derived from the risk state: NY/PA/MA/NJ → Northeast, OH/IL/MI/WI → Midwest, TX/FL/GA/NC → South, CA/AZ/WA/CO → West',
    synonyms: ['state group', 'territory'], related: ['T-004'],
    mappings: [{ fqn: `${G}.DIM_POLICY`, column: 'REGION', kind: 'defines' }, { fqn: `${G}.FCT_CLAIM`, column: 'REGION', kind: 'derives' }, { fqn: `${G}.FCT_PREMIUM`, column: 'REGION', kind: 'derives' }],
    metricRefs: [], dqRules: ['REGION in reference list', 'State maps to exactly one region'], dqScore: 100 }),
  term({ id: 'T-004', term: 'Line of Business', domain: 'Underwriting', owner: 'K. Ashford', steward: 'R. Mendes', status: 'Approved', isCde: true,
    definition: 'The insurance product family a policy or claim belongs to: Personal Auto, Homeowners, Commercial Auto, Commercial Property, General Liability and Workers’ Compensation.', formula: 'Mapped from the policy administration LOB code; each line maps to one Annual Statement line',
    synonyms: ['LOB', 'product line', 'line'], related: ['T-008'],
    mappings: [{ fqn: `${G}.DIM_LINE_OF_BUSINESS`, column: 'LINE_OF_BUSINESS', kind: 'defines' }, { fqn: `${G}.FCT_CLAIM`, column: 'LINE_CODE', kind: 'derives' }],
    metricRefs: [], dqRules: ['LINE_CODE in reference list'], dqScore: 100 }),
  term({ id: 'T-005', term: 'Earned Premium', domain: 'Finance', owner: 'Finance (N. Feld)', steward: 'P. Lindgren', status: 'Approved', isCde: true,
    definition: 'The portion of written premium that corresponds to coverage already provided in the period. It is the denominator of every loss ratio.', formula: 'Term premium ÷ 12 for each month the policy is in force (pro rata, monthly)',
    synonyms: ['EP', 'earned'], related: ['T-006', 'T-008'],
    mappings: [{ fqn: `${G}.FCT_PREMIUM`, column: 'EARNED_PREMIUM', kind: 'defines' }],
    metricRefs: ['SV_POLICYHOLDER_360.earned_premium', 'SV_CLAIMS_EXPERIENCE.earned_premium'], dqRules: ['EARNED_PREMIUM ≥ 0', 'Σ earned over a term = term premium'], dqScore: 99.6 }),
  term({ id: 'T-006', term: 'Written Premium', domain: 'Finance', owner: 'Finance (N. Feld)', steward: 'P. Lindgren', status: 'Approved', isCde: true,
    definition: 'Premium on policies and renewals whose term starts in the period, recognised in full at term start.', formula: 'Σ term premium where term effective date is in the period',
    synonyms: ['GWP', 'DWP', 'written'], related: ['T-005', 'T-018'],
    mappings: [{ fqn: `${G}.FCT_PREMIUM`, column: 'WRITTEN_PREMIUM', kind: 'defines' }, { fqn: `${G}.DIM_POLICY`, column: 'ANNUAL_PREMIUM', kind: 'derives' }],
    metricRefs: ['SV_POLICYHOLDER_360.written_premium', 'SV_POLICYHOLDER_360.premium_growth_pct', 'SV_POLICYHOLDER_360.avg_premium_per_policy'], dqRules: ['WRITTEN_PREMIUM ≥ 0', 'Matches billing system term premium'], dqScore: 99.2 }),
  term({ id: 'T-007', term: 'Incurred Loss', domain: 'Claims', owner: 'L. Brennan', steward: 'H. Quansah', status: 'Approved', isCde: true,
    definition: 'Paid losses plus outstanding case reserves on a claim, excluding loss adjustment expense.', formula: 'PAID_LOSS + CASE_RESERVE',
    synonyms: ['incurred', 'losses incurred'], related: ['T-008', 'T-019', 'T-027'],
    mappings: [{ fqn: `${G}.FCT_CLAIM`, column: 'INCURRED_LOSS', kind: 'defines' }, { fqn: `${G}.FCT_CLAIM`, column: 'CASE_RESERVE', kind: 'derives' }],
    metricRefs: ['SV_CLAIMS_EXPERIENCE.incurred_losses'], dqRules: ['INCURRED_LOSS = PAID_LOSS + CASE_RESERVE', 'INCURRED_LOSS ≥ 0'], dqScore: 99.1 }),
  term({ id: 'T-008', term: 'Loss Ratio', domain: 'Underwriting', owner: 'K. Ashford', steward: 'R. Mendes', status: 'Approved', isCde: true,
    definition: 'Incurred losses on claims with a loss date in the period divided by premium earned in the same period. Always on earned premium; the ex-cat loss ratio excludes claims on the cat-code list.', formula: 'Σ incurred loss ÷ Σ earned premium × 100 (ex-cat: claims with a CAT_CODE removed from the numerator)',
    synonyms: ['LR', 'ex-cat loss ratio', 'underlying loss ratio'], related: ['T-005', 'T-007', 'T-009', 'T-010'],
    mappings: [{ fqn: `${G}.FCT_CLAIM`, column: 'INCURRED_LOSS', kind: 'derives' }, { fqn: `${G}.FCT_PREMIUM`, column: 'EARNED_PREMIUM', kind: 'derives' }, { fqn: `${G}.FCT_CLAIM`, column: 'CAT_CODE', kind: 'filters' }],
    metricRefs: ['SV_CLAIMS_EXPERIENCE.loss_ratio_ex_cat', 'SV_CLAIMS_EXPERIENCE.loss_ratio'], dqRules: ['Earned premium > 0 in period', 'CAT_CODE validated against the cat-code list'], dqScore: 99.0 }),
  term({ id: 'T-009', term: 'Catastrophe Claim', domain: 'Claims', owner: 'L. Brennan', steward: 'H. Quansah', status: 'Approved', isCde: true,
    definition: 'A claim whose loss arises from an event on Sentinel Mutual’s cat-code list (a declared catastrophe event with a code, peril, dates and affected states).', formula: 'CAT_CODE IS NOT NULL and present in DIM_CAT_EVENT',
    synonyms: ['cat claim', 'cat loss', 'catastrophe loss'], related: ['T-008', 'T-021'],
    mappings: [{ fqn: 'CURATED_SILVER.CAT_EVENT', column: 'CAT_CODE', kind: 'defines' }, { fqn: `${G}.DIM_CAT_EVENT`, column: 'CAT_CODE', kind: 'defines' }, { fqn: `${G}.FCT_CLAIM`, column: 'CAT_CODE', kind: 'filters' }],
    metricRefs: ['SV_CLAIMS_EXPERIENCE.cat_loss_ratio'], dqRules: ['Loss date within event window', 'Loss state in affected states'], dqScore: 98.6 }),
  term({ id: 'T-010', term: 'Combined Ratio', domain: 'Underwriting', owner: 'K. Ashford', steward: 'R. Mendes', status: 'Approved', isCde: true,
    definition: 'The loss ratio plus the LAE ratio plus the underwriting expense ratio. Below 100% means an underwriting profit.', formula: '(incurred loss + LAE + underwriting expense) ÷ earned premium × 100',
    synonyms: ['COR', 'underwriting ratio'], related: ['T-008', 'T-011', 'T-024'],
    mappings: [{ fqn: `${G}.FCT_CLAIM`, column: 'INCURRED_LOSS', kind: 'derives' }, { fqn: `${G}.FCT_CLAIM`, column: 'LAE_AMOUNT', kind: 'derives' }, { fqn: `${G}.FCT_PREMIUM`, column: 'UW_EXPENSE', kind: 'derives' }],
    metricRefs: ['SV_CLAIMS_EXPERIENCE.combined_ratio'], dqRules: ['Inherits Loss Ratio, LAE and Expense Ratio rules'], dqScore: 98.9 }),
  term({ id: 'T-011', term: 'Loss Adjustment Expense', domain: 'Claims', owner: 'L. Brennan', steward: 'H. Quansah', status: 'Approved', isCde: true,
    definition: 'The cost of investigating, adjusting and settling claims (adjusters, legal, independent appraisers), reported separately from losses.', formula: 'Σ expense payments on the claim',
    synonyms: ['LAE', 'claim expense', 'ALAE'], related: ['T-010'],
    mappings: [{ fqn: `${G}.FCT_CLAIM`, column: 'LAE_AMOUNT', kind: 'defines' }],
    metricRefs: ['SV_CLAIMS_EXPERIENCE.lae_ratio'], dqRules: ['LAE_AMOUNT ≥ 0'], dqScore: 98.8 }),
  term({ id: 'T-012', term: 'Claim Severity', domain: 'Claims', owner: 'L. Brennan', steward: 'H. Quansah', status: 'Approved', isCde: false,
    definition: 'The average incurred loss per claim for claims with a loss date in the period. LAE is excluded.', formula: 'Σ incurred loss ÷ number of claims',
    synonyms: ['severity', 'average claim cost'], related: ['T-007', 'T-025'],
    mappings: [{ fqn: `${G}.FCT_CLAIM`, column: 'INCURRED_LOSS', kind: 'derives' }],
    metricRefs: ['SV_CLAIMS_EXPERIENCE.avg_severity'] }),
  term({ id: 'T-013', term: 'Claims Cycle Time', domain: 'Claims', owner: 'L. Brennan', steward: 'H. Quansah', status: 'Approved', isCde: false,
    definition: 'Days from first notice of loss (FNOL) to claim closure, measured on claims closed in the period.', formula: 'CLOSE_DATE − REPORT_DATE',
    synonyms: ['cycle time', 'days to close'], related: ['T-014'],
    mappings: [{ fqn: `${G}.FCT_CLAIM`, column: 'CYCLE_DAYS', kind: 'defines' }],
    metricRefs: ['SV_CLAIMS_EXPERIENCE.avg_cycle_days'] }),
  term({ id: 'T-014', term: 'Open Claim', domain: 'Claims', owner: 'L. Brennan', steward: 'H. Quansah', status: 'Approved', isCde: true,
    definition: 'A claim with status Open or Reopened that still carries a case reserve above zero. Claims that are fully paid and only awaiting a subrogation recovery are not open.', formula: "CLAIM_STATUS IN ('Open', 'Reopened') AND CASE_RESERVE > 0",
    synonyms: ['pending claim', 'open inventory'], related: ['T-013', 'T-019'],
    mappings: [{ fqn: `${G}.FCT_CLAIM`, column: 'CLAIM_STATUS', kind: 'filters' }, { fqn: `${G}.FCT_CLAIM`, column: 'CASE_RESERVE', kind: 'filters' }, { fqn: 'DATA_PRODUCTS.DP_CLAIMS_EXPERIENCE', column: 'IS_OPEN', kind: 'derives' }],
    metricRefs: ['SV_CLAIMS_EXPERIENCE.open_claims'], dqRules: ['Status in (Open, Closed, Reopened)', 'Closed claims carry no case reserve'], dqScore: 99.3 }),
  term({ id: 'T-015', term: 'Subrogation Recovery', domain: 'Claims', owner: 'L. Brennan', steward: 'H. Quansah', status: 'Approved', isCde: true,
    definition: 'Money recovered from a responsible third party (or their insurer) after Sentinel Mutual has paid a claim. The recovery rate compares recoveries with paid losses on subrogation-eligible claims.', formula: 'Σ subrogation recovered ÷ Σ paid loss on eligible claims closed in the period × 100',
    synonyms: ['subro', 'recovery'], related: ['T-027'],
    mappings: [{ fqn: `${G}.FCT_CLAIM`, column: 'SUBRO_RECOVERED', kind: 'defines' }],
    metricRefs: ['SV_CLAIMS_EXPERIENCE.subrogation_recovery_rate'], dqRules: ['SUBRO_RECOVERED ≤ PAID_LOSS', 'Recovery dated after payment'], dqScore: 97.8 }),
  term({ id: 'T-016', term: 'Policy Retention', domain: 'Policyholder', owner: 'C. Whitaker', steward: 'H. Quansah', status: 'Approved', isCde: true,
    definition: 'The share of policies reaching a renewal date in the period that renewed. Mid-term cancellations are not in the denominator.', formula: 'Policies renewed ÷ policies due for renewal × 100',
    synonyms: ['retention', 'renewal rate', 'persistency'], related: ['T-002'],
    mappings: [{ fqn: `${G}.DIM_POLICY`, column: 'RENEWED_FLAG', kind: 'defines' }],
    metricRefs: ['SV_POLICYHOLDER_360.policy_retention_rate'], dqRules: ['RENEWED_FLAG set only when a renewal date has passed'], dqScore: 98.9 }),
  term({ id: 'T-017', term: 'Quote-to-Bind Ratio', domain: 'Distribution', owner: 'J. Castellano', steward: 'R. Mendes', status: 'Approved', isCde: true,
    definition: 'The share of quoted submissions that were bound into a policy. Submissions declined before a quote are excluded.', formula: 'Bound submissions ÷ quoted submissions × 100 (by quote date)',
    synonyms: ['bind rate', 'hit ratio', 'conversion rate'], related: ['T-018', 'T-028'],
    mappings: [{ fqn: `${G}.FCT_SUBMISSION`, column: 'IS_BOUND', kind: 'defines' }, { fqn: 'DATA_PRODUCTS.DP_DISTRIBUTION_PERFORMANCE', column: 'IS_BOUND', kind: 'derives' }],
    metricRefs: ['SV_DISTRIBUTION.quote_to_bind_ratio', 'SV_DISTRIBUTION.policies_bound'], dqRules: ['Bound implies quoted', 'Bind date ≥ quote date'], dqScore: 98.5 }),
  term({ id: 'T-018', term: 'New Business Premium', domain: 'Distribution', owner: 'J. Castellano', steward: 'R. Mendes', status: 'Approved', isCde: false,
    definition: 'Written premium on policies bound from new submissions in the period. Renewals, rewrites of existing business and reinstatements are excluded.', formula: "Σ BOUND_PREMIUM where SUBMISSION_TYPE = 'New business'",
    synonyms: ['NB premium', 'new premium'], related: ['T-006', 'T-017'],
    mappings: [{ fqn: `${G}.FCT_SUBMISSION`, column: 'BOUND_PREMIUM', kind: 'derives' }, { fqn: `${G}.FCT_SUBMISSION`, column: 'SUBMISSION_TYPE', kind: 'filters' }],
    metricRefs: ['SV_DISTRIBUTION.new_business_premium'] }),
  term({ id: 'T-019', term: 'Case Reserve', domain: 'Reserving', owner: 'Actuarial (S. Varga)', steward: 'P. Lindgren', status: 'Approved', isCde: true,
    definition: 'The adjuster’s estimate of the amount still to be paid on an open claim, reported at each month-end valuation.', formula: 'Incurred estimate − paid to date, on open claims at the valuation date',
    synonyms: ['case reserves', 'outstanding reserve', 'case OS'], related: ['T-007', 'T-014', 'T-020'],
    mappings: [{ fqn: `${G}.FCT_RESERVE`, column: 'CASE_RESERVE', kind: 'defines' }, { fqn: `${G}.FCT_CLAIM`, column: 'CASE_RESERVE', kind: 'derives' }],
    metricRefs: ['SV_LOSS_RESERVES.case_reserve_balance', 'SV_LOSS_RESERVES.avg_case_reserve', 'SV_LOSS_RESERVES.total_loss_reserves'], dqRules: ['CASE_RESERVE ≥ 0', 'Zero on closed claims'], dqScore: 98.2 }),
  term({ id: 'T-020', term: 'IBNR Reserve', domain: 'Reserving', owner: 'Actuarial (S. Varga)', steward: 'P. Lindgren', status: 'Approved', isCde: true,
    definition: 'Incurred but not reported: the reserve for losses that have happened but have not yet been reported, plus development on known claims. Set by line by the reserving committee.', formula: 'IBNR factor by line × trailing 12-month earned premium, allocated to open claims pro rata to case reserve',
    synonyms: ['IBNR', 'bulk reserve'], related: ['T-019'],
    mappings: [{ fqn: `${G}.FCT_RESERVE`, column: 'IBNR_ALLOCATED', kind: 'defines' }, { fqn: `${G}.DIM_LINE_OF_BUSINESS`, column: 'IBNR_FACTOR', kind: 'derives' }],
    metricRefs: ['SV_LOSS_RESERVES.ibnr_reserve'], dqRules: ['Σ allocated = committee IBNR by line', 'Factors approved quarterly'], dqScore: 96.9 }),
  term({ id: 'T-021', term: 'Total Insured Value', domain: 'Catastrophe risk', owner: 'E. Moravec', steward: null, status: 'Approved', isCde: true,
    definition: 'The total value insured at a property risk location (building, contents and business interruption), used to measure catastrophe exposure by zone.', formula: 'Building + contents + time element limits per location; zone concentration = TIV in hurricane and wildfire zones ÷ total property TIV',
    synonyms: ['TIV', 'insured value', 'exposure'], related: ['T-009'],
    mappings: [{ fqn: `${G}.DIM_POLICY`, column: 'TOTAL_INSURED_VALUE', kind: 'defines' }, { fqn: 'DATA_PRODUCTS.DP_CATASTROPHE_EXPOSURE', column: 'TOTAL_INSURED_VALUE', kind: 'defines' }],
    metricRefs: ['DP_CATASTROPHE_EXPOSURE.tiv_in_cat_zones', 'DP_CATASTROPHE_EXPOSURE.cat_zone_concentration_pct'], dqRules: ['TIV > 0 for property lines', 'Geocoded to a cat zone'], dqScore: 90.4 }),
  term({ id: 'T-022', term: 'Producer', domain: 'Distribution', owner: 'J. Castellano', steward: 'R. Mendes', status: 'Approved', isCde: false,
    definition: 'An appointed agency, broker or the direct digital channel that submits business to Sentinel Mutual.', formula: 'One record per AGENCY_ID',
    synonyms: ['agency', 'agent', 'broker'], related: ['T-017'],
    mappings: [{ fqn: `${G}.DIM_PRODUCER`, column: 'AGENCY_ID', kind: 'defines' }],
    metricRefs: ['SV_DISTRIBUTION.submissions_quoted'] }),
  term({ id: 'T-023', term: 'Billing Delinquency', domain: 'Finance', owner: 'Finance (N. Feld)', steward: 'P. Lindgren', status: 'Approved', isCde: false,
    definition: 'An invoice that is more than 30 days past due at month end.', formula: 'Invoices with DAYS_PAST_DUE > 30 ÷ invoices billed in the month × 100',
    synonyms: ['delinquency', 'past due'], related: ['T-006'],
    mappings: [{ fqn: `${G}.FCT_PREMIUM`, column: 'DAYS_PAST_DUE', kind: 'defines' }],
    metricRefs: ['SV_POLICYHOLDER_360.billing_delinquency_rate'] }),
  term({ id: 'T-024', term: 'Expense Ratio', domain: 'Finance', owner: 'Finance (N. Feld)', steward: 'P. Lindgren', status: 'Approved', isCde: false,
    definition: 'Commissions and other underwriting expenses as a share of earned premium.', formula: 'Σ underwriting expense ÷ Σ earned premium × 100',
    synonyms: ['UW expense ratio'], related: ['T-010'],
    mappings: [{ fqn: `${G}.FCT_PREMIUM`, column: 'UW_EXPENSE', kind: 'defines' }],
    metricRefs: ['SV_CLAIMS_EXPERIENCE.expense_ratio'] }),
  term({ id: 'T-025', term: 'Claim Frequency', domain: 'Claims', owner: 'L. Brennan', steward: 'H. Quansah', status: 'Approved', isCde: false,
    definition: 'The number of claims per 100 policies in force for a year.', formula: 'Claims ÷ (policy-months ÷ 12) × 100',
    synonyms: ['frequency', 'claim rate'], related: ['T-012'],
    mappings: [{ fqn: `${G}.FCT_CLAIM`, column: 'CLAIM_KEY', kind: 'derives' }, { fqn: `${G}.FCT_PREMIUM`, column: 'POLICY_KEY', kind: 'derives' }],
    metricRefs: ['SV_CLAIMS_EXPERIENCE.claim_frequency'] }),
  term({ id: 'T-026', term: 'Fraud Propensity Score', domain: 'Claims', owner: 'Special Investigations (A. Rourke)', steward: 'H. Quansah', status: 'Draft', isCde: false,
    definition: 'Model score (0–100) estimating the likelihood that a claim warrants referral to special investigations. Draft: model card and fairness review pending.', formula: 'Gradient-boosted model over report lag, claim history, injury type and provider patterns',
    synonyms: ['fraud score', 'SIU score'], related: ['T-014'],
    mappings: [{ fqn: `${G}.FCT_CLAIM`, column: 'FRAUD_SCORE', kind: 'defines' }],
    metricRefs: [] }),
  term({ id: 'T-027', term: 'Paid Loss', domain: 'Claims', owner: 'L. Brennan', steward: 'H. Quansah', status: 'Approved', isCde: false,
    definition: 'Loss payments made to claimants or vendors, before subrogation recoveries and excluding LAE.', formula: "Σ AMOUNT_USD where TXN_TYPE = 'Loss payment'",
    synonyms: ['paid', 'payments', 'claim payments'], related: ['T-007', 'T-015'],
    mappings: [{ fqn: `${G}.FCT_CLAIM`, column: 'PAID_LOSS', kind: 'defines' }, { fqn: `${G}.FCT_CLAIM_TRANSACTION`, column: 'AMOUNT_USD', kind: 'derives' }],
    metricRefs: ['SV_CLAIMS_EXPERIENCE.paid_losses'] }),
  term({ id: 'T-028', term: 'Quote Turnaround Time', domain: 'Distribution', owner: 'J. Castellano', steward: 'R. Mendes', status: 'Approved', isCde: false,
    definition: 'Days from receiving a complete submission to issuing a quote.', formula: 'QUOTE_DATE − RECEIVED_DATE (fractional days)',
    synonyms: ['speed to quote', 'time to quote'], related: ['T-017'],
    mappings: [{ fqn: `${G}.FCT_SUBMISSION`, column: 'TURNAROUND_DAYS', kind: 'defines' }],
    metricRefs: ['SV_DISTRIBUTION.quote_turnaround_days'] }),
];
