import type { GlossaryTerm } from '../../types';

const G = 'CONFORMED_GOLD';
const term = (t: Omit<GlossaryTerm, 'related' | 'synonyms'> & Partial<Pick<GlossaryTerm, 'related' | 'synonyms'>>): GlossaryTerm => ({ related: [], synonyms: [], ...t });

export const GLOSSARY: GlossaryTerm[] = [
  term({ id: 'T-001', term: 'Loyalty Member', domain: 'Customer', owner: 'Customer Insights (R. Okonkwo)', steward: 'L. Ferraro', status: 'Approved', isCde: true,
    definition: 'A person enrolled in the Harbor Club loyalty programme, identified by a member number used in stores and online.', formula: 'One record per MEMBER_ID; the current SCD2 version represents the member today.',
    synonyms: ['member', 'harbor club member', 'loyalty customer'], related: ['T-002', 'T-026'],
    mappings: [{ fqn: `${G}.DIM_CUSTOMER`, column: 'MEMBER_ID', kind: 'defines' }, { fqn: 'CURATED_SILVER.LOYALTY_MEMBER', column: 'MEMBER_ID', kind: 'defines' }],
    metricRefs: [], dqRules: ['MEMBER_ID not null', 'MEMBER_ID unique where IS_CURRENT'], dqScore: 99.7 }),
  term({ id: 'T-002', term: 'Active Member', domain: 'Customer', owner: 'Customer Insights (R. Okonkwo)', steward: 'L. Ferraro', status: 'Approved', isCde: true,
    definition: 'A loyalty member whose account status is Active and who has made at least one purchase, in store or online, in the last 12 months.', formula: "MEMBER_STATUS = 'Active' AND LAST_PURCHASE_DATE > as-of date − 365 days",
    synonyms: ['active loyalty member', 'active customer', 'engaged member'], related: ['T-001', 'T-027'],
    mappings: [{ fqn: 'CURATED_SILVER.LOYALTY_MEMBER', column: 'MEMBER_STATUS', kind: 'filters' }, { fqn: `${G}.DIM_CUSTOMER`, column: 'LAST_PURCHASE_DATE', kind: 'filters' }, { fqn: 'DATA_PRODUCTS.DP_CUSTOMER_LOYALTY_360', column: 'IS_ACTIVE', kind: 'derives' }],
    metricRefs: ['SV_CUSTOMER_LOYALTY.active_members'], dqRules: ['Status in (Active, Closed)', 'LAST_PURCHASE_DATE not in future'], dqScore: 99.1 }),
  term({ id: 'T-003', term: 'Store Region', domain: 'Enterprise', owner: 'Store Operations (K. Lindgren)', steward: 'M. Haddad', status: 'Approved', isCde: true,
    definition: 'One of Harbor & Pine’s four store regions: Northeast, Mid-Atlantic, Midwest and West. E-commerce sales and members take the region of their attributed or home store.', formula: 'From the store master region code: NE → Northeast, MID → Mid-Atlantic, MW → Midwest, WST → West',
    synonyms: ['region', 'territory', 'market'], related: ['T-005'],
    mappings: [{ fqn: `${G}.DIM_STORE`, column: 'REGION', kind: 'defines' }, { fqn: `${G}.FCT_SALES`, column: 'REGION', kind: 'derives' }, { fqn: `${G}.DIM_CUSTOMER`, column: 'HOME_REGION', kind: 'derives' }],
    metricRefs: [], dqRules: ['REGION in reference list'], dqScore: 100 }),
  term({ id: 'T-004', term: 'Comparable Store Sales', domain: 'Sales', owner: 'Finance – FP&A (J. Whitaker)', steward: 'M. Haddad', status: 'Approved', isCde: true,
    definition: 'Growth in net sales for comparable stores only, against the same weekday-aligned days last year. A comparable store has been open 13 or more full months; stores closed for a remodel are excluded. Includes e-commerce sales attributed to those stores.', formula: '(TY net sales of comp stores ÷ LY net sales of the same stores on the same weekday 364 days earlier) − 1',
    synonyms: ['comp sales', 'comps', 'comparable sales', 'like for like sales', 'same store sales'], related: ['T-005', 'T-006', 'T-018'],
    mappings: [{ fqn: `${G}.FCT_SALES`, column: 'NET_SALES_USD', kind: 'derives' }, { fqn: `${G}.FCT_SALES`, column: 'IS_COMP_STORE', kind: 'filters' }, { fqn: `${G}.DIM_DATE`, column: 'SAME_DAY_LAST_YEAR', kind: 'derives' }],
    metricRefs: ['SV_STORE_SALES.comp_sales_pct'], dqRules: ['LY row exists for every comp store-day', 'IS_COMP_STORE recomputed monthly'], dqScore: 99.3 }),
  term({ id: 'T-005', term: 'Comparable Store', domain: 'Sales', owner: 'Finance – FP&A (J. Whitaker)', steward: 'M. Haddad', status: 'Approved', isCde: true,
    definition: 'A store open 13 or more full months before the start of the month being reported, and not closed for a remodel in that month or the same month last year.', formula: 'OPEN_DATE ≤ month start − 13 months AND no remodel closure overlapping the month or the prior-year month',
    synonyms: ['comp store', 'mature store', 'like for like store'], related: ['T-004'],
    mappings: [{ fqn: `${G}.DIM_STORE`, column: 'OPEN_DATE', kind: 'derives' }, { fqn: `${G}.DIM_STORE`, column: 'IS_COMP_STORE', kind: 'defines' }, { fqn: `${G}.FCT_SALES`, column: 'IS_COMP_STORE', kind: 'defines' }],
    metricRefs: [], dqRules: ['OPEN_DATE not null', 'Remodel window END ≥ START'], dqScore: 100 }),
  term({ id: 'T-006', term: 'Net Sales', domain: 'Sales', owner: 'Finance – FP&A (J. Whitaker)', steward: 'M. Haddad', status: 'Approved', isCde: true,
    definition: 'Sales after discounts and returns, excluding sales tax and gift card sales.', formula: 'Gross sales − discounts − returns',
    synonyms: ['revenue', 'turnover'], related: ['T-004', 'T-028'],
    mappings: [{ fqn: `${G}.FCT_SALES`, column: 'NET_SALES_USD', kind: 'defines' }, { fqn: 'CURATED_SILVER.POS_TRANSACTION', column: 'NET_AMOUNT_USD', kind: 'derives' }],
    metricRefs: ['SV_STORE_SALES.net_sales'], dqRules: ['NET = GROSS − DISCOUNT − RETURNS', 'Reconciles to the general ledger daily'], dqScore: 99.6 }),
  term({ id: 'T-007', term: 'Basket Size', domain: 'Sales', owner: 'Store Operations (K. Lindgren)', steward: 'M. Haddad', status: 'Approved', isCde: true,
    definition: 'Average net sales per sales transaction (average transaction value).', formula: 'Net sales ÷ sales transactions (returns-only transactions excluded)',
    synonyms: ['average transaction value', 'ATV', 'average basket'], related: ['T-008', 'T-006'],
    mappings: [{ fqn: `${G}.FCT_SALES`, column: 'TRANSACTIONS', kind: 'derives' }, { fqn: `${G}.FCT_SALES`, column: 'NET_SALES_USD', kind: 'derives' }],
    metricRefs: ['SV_STORE_SALES.basket_size', 'SV_STORE_SALES.transactions'], dqRules: ['TRANSACTIONS > 0 for open store-days'], dqScore: 99.2 }),
  term({ id: 'T-008', term: 'Units per Transaction', domain: 'Sales', owner: 'Store Operations (K. Lindgren)', steward: 'M. Haddad', status: 'Approved', isCde: false,
    definition: 'Average number of units in a sales transaction.', formula: 'Units sold ÷ sales transactions',
    synonyms: ['UPT', 'items per basket'], related: ['T-007'],
    mappings: [{ fqn: `${G}.FCT_SALES`, column: 'UNITS', kind: 'defines' }],
    metricRefs: ['SV_STORE_SALES.units_per_transaction'] }),
  term({ id: 'T-009', term: 'Loyalty Share of Sales', domain: 'Customer', owner: 'Customer Insights (R. Okonkwo)', steward: 'L. Ferraro', status: 'Approved', isCde: true,
    definition: 'The share of net sales where a Harbor Club member was identified: scanned at the till or signed in online.', formula: 'Loyalty-identified net sales ÷ net sales × 100',
    synonyms: ['loyalty share', 'member share of sales', 'loyalty penetration'], related: ['T-001', 'T-006'],
    mappings: [{ fqn: `${G}.FCT_SALES`, column: 'LOYALTY_SALES_USD', kind: 'defines' }, { fqn: `${G}.FCT_SALES`, column: 'NET_SALES_USD', kind: 'derives' }],
    metricRefs: ['SV_CUSTOMER_LOYALTY.loyalty_share_pct'], dqRules: ['LOYALTY_SALES ≤ NET_SALES'], dqScore: 98.8 }),
  term({ id: 'T-010', term: 'Sell-Through', domain: 'Merchandising', owner: 'Merchandise Planning (A. Brennan)', steward: 'P. Castellanos', status: 'Approved', isCde: true,
    definition: 'The share of available units sold in a period, where available means units on hand at the start of the period plus units received during it.', formula: 'Units sold ÷ (opening on-hand units + units received) × 100',
    synonyms: ['sell through', 'sell-thru', 'sell through rate'], related: ['T-013', 'T-011'],
    mappings: [{ fqn: `${G}.FCT_INVENTORY`, column: 'UNITS_SOLD', kind: 'derives' }, { fqn: `${G}.FCT_INVENTORY`, column: 'BEGIN_ON_HAND_UNITS', kind: 'derives' }, { fqn: `${G}.FCT_INVENTORY`, column: 'UNITS_RECEIVED', kind: 'derives' }],
    metricRefs: ['SV_SUPPLY_CHAIN.sell_through_pct'], dqRules: ['UNITS_SOLD ≤ BEGIN_ON_HAND + RECEIVED'], dqScore: 98.6 }),
  term({ id: 'T-011', term: 'Inventory Turns', domain: 'Merchandising', owner: 'Merchandise Planning (A. Brennan)', steward: 'P. Castellanos', status: 'Approved', isCde: true,
    definition: 'How many times average inventory is sold through in a year.', formula: 'Annualised cost of goods sold (13 weeks × 4) ÷ average weekly inventory at cost',
    synonyms: ['turns', 'stock turn', 'inventory turnover'], related: ['T-010', 'T-029'],
    mappings: [{ fqn: `${G}.FCT_INVENTORY`, column: 'COGS_USD', kind: 'derives' }, { fqn: `${G}.FCT_INVENTORY`, column: 'ON_HAND_COST_USD', kind: 'derives' }],
    metricRefs: ['SV_SUPPLY_CHAIN.inventory_turns'], dqRules: ['COGS ≥ 0', 'ON_HAND_COST ≥ 0'], dqScore: 98.9 }),
  term({ id: 'T-012', term: 'Out-of-Stock', domain: 'Merchandising', owner: 'Merchandise Planning (A. Brennan)', steward: 'P. Castellanos', status: 'Approved', isCde: true,
    definition: 'A store-SKU that is ranged on the planogram but has zero units on hand at the weekly snapshot. The out-of-stock rate is the share of ranged store-SKUs that are out of stock.', formula: 'SKUs out of stock ÷ SKUs ranged × 100, at the Sunday snapshot',
    synonyms: ['OOS', 'stockout', 'out of stock rate'], related: ['T-013'],
    mappings: [{ fqn: `${G}.FCT_INVENTORY`, column: 'SKUS_OUT_OF_STOCK', kind: 'defines' }, { fqn: `${G}.FCT_INVENTORY`, column: 'SKUS_RANGED', kind: 'derives' }, { fqn: 'CURATED_SILVER.STORE_INVENTORY', column: 'SKUS_OUT_OF_STOCK', kind: 'derives' }],
    metricRefs: ['SV_SUPPLY_CHAIN.oos_rate_pct'], dqRules: ['SKUS_OUT_OF_STOCK ≤ SKUS_RANGED', 'Snapshot taken every Sunday 23:00'], dqScore: 99.0 }),
  term({ id: 'T-013', term: 'Weeks of Supply', domain: 'Merchandising', owner: 'Merchandise Planning (A. Brennan)', steward: 'P. Castellanos', status: 'Approved', isCde: false,
    definition: 'How many weeks current stock lasts at the recent rate of sale.', formula: 'On-hand units ÷ average weekly units sold over the last 4 weeks',
    synonyms: ['WOS', 'weeks of cover', 'cover'], related: ['T-010', 'T-012'],
    mappings: [{ fqn: `${G}.FCT_INVENTORY`, column: 'ON_HAND_UNITS', kind: 'defines' }],
    metricRefs: ['SV_SUPPLY_CHAIN.weeks_of_supply'] }),
  term({ id: 'T-014', term: 'Supplier OTIF', domain: 'Supply chain', owner: 'Supply Chain (D. Mensah)', steward: 'P. Castellanos', status: 'Approved', isCde: true,
    definition: 'The share of purchase order lines a supplier delivered to the DC on or before the requested delivery date and with at least 98% of the ordered units.', formula: 'Lines on time and in full ÷ lines received × 100',
    synonyms: ['OTIF', 'on time in full', 'vendor delivery'], related: ['T-015', 'T-016'],
    mappings: [{ fqn: `${G}.FCT_SUPPLIER_DELIVERY`, column: 'OTIF_FLAG', kind: 'defines' }],
    metricRefs: ['SV_SUPPLY_CHAIN.otif_pct'], dqRules: ['Requested date present', 'Receipt date ≥ PO date'], dqScore: 98.1 }),
  term({ id: 'T-015', term: 'Fill Rate', domain: 'Supply chain', owner: 'Supply Chain (D. Mensah)', steward: 'P. Castellanos', status: 'Approved', isCde: true,
    definition: 'The share of ordered units that suppliers actually delivered.', formula: 'Units received ÷ units ordered × 100',
    synonyms: ['unit fill rate', 'fill'], related: ['T-014'],
    mappings: [{ fqn: `${G}.FCT_SUPPLIER_DELIVERY`, column: 'RECEIVED_UNITS', kind: 'defines' }, { fqn: `${G}.FCT_SUPPLIER_DELIVERY`, column: 'ORDERED_UNITS', kind: 'derives' }],
    metricRefs: ['SV_SUPPLY_CHAIN.fill_rate_pct'], dqRules: ['RECEIVED_UNITS ≤ ORDERED_UNITS × 1.05'], dqScore: 98.7 }),
  term({ id: 'T-016', term: 'Supplier Lead Time', domain: 'Supply chain', owner: 'Supply Chain (D. Mensah)', steward: 'P. Castellanos', status: 'Approved', isCde: false,
    definition: 'Days from purchase order creation to receipt at the distribution center.', formula: 'RECEIVED_DATE − PO date',
    synonyms: ['lead time', 'replenishment lead time'], related: ['T-014'],
    mappings: [{ fqn: `${G}.FCT_SUPPLIER_DELIVERY`, column: 'LEAD_TIME_DAYS', kind: 'defines' }],
    metricRefs: ['SV_SUPPLY_CHAIN.avg_lead_time_days'] }),
  term({ id: 'T-017', term: 'ASN Accuracy', domain: 'Supply chain', owner: 'Supply Chain (D. Mensah)', steward: 'P. Castellanos', status: 'Approved', isCde: false,
    definition: 'The share of PO lines whose EDI 856 advance ship notice matched what was physically received.', formula: 'Lines with matching ASN ÷ lines received × 100',
    synonyms: ['ship notice accuracy', 'ASN match rate'], related: ['T-014'],
    mappings: [{ fqn: `${G}.FCT_SUPPLIER_DELIVERY`, column: 'ASN_ACCURATE', kind: 'defines' }, { fqn: 'CURATED_SILVER.SUPPLIER_PO_LINE', column: 'ASN_MATCHED', kind: 'derives' }],
    metricRefs: ['SV_SUPPLY_CHAIN.asn_accuracy_pct'] }),
  term({ id: 'T-018', term: 'Promotion', domain: 'Merchandising', owner: 'Marketing & Promotions (S. Adeyemi)', steward: 'L. Ferraro', status: 'Approved', isCde: true,
    definition: 'A planned, time-bound price or loyalty offer on the promotion calendar, running in one or more store regions and channels.', formula: 'One record per PROMO_ID with start and end dates and regions',
    synonyms: ['promo', 'event', 'campaign', 'offer'], related: ['T-019', 'T-020', 'T-004'],
    mappings: [{ fqn: `${G}.DIM_PROMOTION`, column: 'PROMO_ID', kind: 'defines' }, { fqn: `${G}.FCT_SALES`, column: 'PROMO_KEY', kind: 'derives' }, { fqn: `${G}.FCT_PROMO_SALES`, column: 'PROMO_KEY', kind: 'derives' }],
    metricRefs: [], dqRules: ['No overlapping promotions in a region', 'END_DATE ≥ START_DATE'], dqScore: 99.5 }),
  term({ id: 'T-019', term: 'Promotional Lift', domain: 'Merchandising', owner: 'Marketing & Promotions (S. Adeyemi)', steward: 'L. Ferraro', status: 'Approved', isCde: true,
    definition: 'How much promoted-item sales exceeded the modelled baseline (the sales expected without the promotion).', formula: '(Promoted net sales − baseline sales) ÷ baseline sales × 100',
    synonyms: ['uplift', 'promo lift', 'incremental sales %'], related: ['T-018', 'T-020'],
    mappings: [{ fqn: `${G}.FCT_PROMO_SALES`, column: 'BASELINE_SALES_USD', kind: 'derives' }, { fqn: `${G}.FCT_PROMO_SALES`, column: 'NET_SALES_USD', kind: 'derives' }],
    metricRefs: ['SV_PROMO_EFFECTIVENESS.promo_lift_pct'], dqRules: ['BASELINE_SALES > 0', 'Baseline model refreshed weekly'], dqScore: 96.4 }),
  term({ id: 'T-020', term: 'Promotion ROI', domain: 'Merchandising', owner: 'Marketing & Promotions (S. Adeyemi)', steward: 'L. Ferraro', status: 'Approved', isCde: true,
    definition: 'Incremental gross margin earned per dollar of promotion cost funded by Harbor & Pine (discount net of vendor funding).', formula: 'Σ incremental margin ÷ Σ promotion cost',
    synonyms: ['promo ROI', 'return on promotion'], related: ['T-019'],
    mappings: [{ fqn: `${G}.FCT_PROMO_SALES`, column: 'INCREMENTAL_MARGIN_USD', kind: 'derives' }, { fqn: `${G}.FCT_PROMO_SALES`, column: 'PROMO_COST_USD', kind: 'derives' }],
    metricRefs: ['SV_PROMO_EFFECTIVENESS.promo_roi', 'SV_PROMO_EFFECTIVENESS.promo_cost', 'SV_PROMO_EFFECTIVENESS.incremental_margin'], dqRules: ['PROMO_COST ≥ 0', 'Vendor funding reconciled monthly'], dqScore: 95.8 }),
  term({ id: 'T-021', term: 'Redemption Rate', domain: 'Merchandising', owner: 'Marketing & Promotions (S. Adeyemi)', steward: 'L. Ferraro', status: 'Approved', isCde: false,
    definition: 'The share of offers issued (coupons, app offers, member emails) that were redeemed.', formula: 'Redemptions ÷ offers issued × 100',
    synonyms: ['take rate', 'coupon redemption'], related: ['T-018'],
    mappings: [{ fqn: `${G}.DIM_PROMOTION`, column: 'OFFERS_ISSUED', kind: 'derives' }],
    metricRefs: ['SV_PROMO_EFFECTIVENESS.redemption_rate_pct'] }),
  term({ id: 'T-022', term: 'Return Rate', domain: 'Store operations', owner: 'Store Operations (K. Lindgren)', steward: 'M. Haddad', status: 'Approved', isCde: true,
    definition: 'Returned sales as a share of gross sales, for returns accepted within the policy window.', formula: 'Returns $ ÷ gross sales $ × 100',
    synonyms: ['returns rate', 'return %'], related: ['T-023', 'T-006'],
    mappings: [{ fqn: `${G}.FCT_SALES`, column: 'RETURNS_USD', kind: 'defines' }, { fqn: `${G}.FCT_SALES`, column: 'GROSS_SALES_USD', kind: 'derives' }, { fqn: 'CURATED_SILVER.RETURN_TXN', column: 'RETURN_AMOUNT_USD', kind: 'derives' }],
    metricRefs: ['DP_RETURNS_FRAUD.return_rate_pct'], dqRules: ['RETURNS ≥ 0'], dqScore: 97.2 }),
  term({ id: 'T-023', term: 'Suspicious Return', domain: 'Store operations', owner: 'Loss Prevention (V. Novak)', steward: null, status: 'Approved', isCde: true,
    definition: 'A return flagged for loss-prevention review: no receipt and over $250, or the same member making more than five returns in 30 days.', formula: '(NOT HAS_RECEIPT AND amount > 250) OR member returns in 30 days > 5',
    synonyms: ['fraud flag', 'suspect return', 'return fraud'], related: ['T-022'],
    mappings: [{ fqn: 'CURATED_SILVER.RETURN_TXN', column: 'IS_SUSPICIOUS', kind: 'defines' }, { fqn: 'DATA_PRODUCTS.DP_RETURNS_FRAUD', column: 'IS_SUSPICIOUS', kind: 'defines' }],
    metricRefs: ['DP_RETURNS_FRAUD.suspicious_return_pct'], dqRules: ['Flag recomputed nightly', 'SUSPICIOUS_REASON present when flagged'], dqScore: 90.4 }),
  term({ id: 'T-024', term: 'Predicted Customer Lifetime Value', domain: 'Customer', owner: 'Customer Insights (R. Okonkwo)', steward: 'L. Ferraro', status: 'Draft', isCde: false,
    definition: 'Model estimate of a member’s net spend over the next three years. Draft: the model card and holdout validation are still in review.', formula: 'Gradient-boosted model over recency, frequency, spend, tier and channel mix',
    synonyms: ['CLV', 'lifetime value', 'LTV'], related: ['T-001', 'T-030'],
    mappings: [{ fqn: `${G}.DIM_CUSTOMER`, column: 'PREDICTED_CLV_USD', kind: 'defines' }],
    metricRefs: ['SV_CUSTOMER_LOYALTY.avg_predicted_clv'] }),
  term({ id: 'T-025', term: 'E-commerce Share', domain: 'Sales', owner: 'Digital Commerce (N. Iwata)', steward: 'M. Haddad', status: 'Approved', isCde: false,
    definition: 'The share of net sales from web and app orders, attributed to the fulfilling or pickup store.', formula: "Net sales where CHANNEL = 'E-commerce' ÷ net sales × 100",
    synonyms: ['online share', 'digital share', 'ecom penetration'], related: ['T-006'],
    mappings: [{ fqn: `${G}.FCT_SALES`, column: 'CHANNEL', kind: 'filters' }],
    metricRefs: ['SV_STORE_SALES.ecommerce_share_pct'] }),
  term({ id: 'T-026', term: 'Repeat Purchase Rate', domain: 'Customer', owner: 'Customer Insights (R. Okonkwo)', steward: 'L. Ferraro', status: 'Approved', isCde: false,
    definition: 'The share of active members who made purchases on two or more different days in the last 12 months.', formula: 'Active members with PURCHASES_12M ≥ 2 ÷ active members × 100',
    synonyms: ['repeat rate', 'retention rate'], related: ['T-002'],
    mappings: [{ fqn: `${G}.DIM_CUSTOMER`, column: 'PURCHASES_12M', kind: 'defines' }],
    metricRefs: ['SV_CUSTOMER_LOYALTY.repeat_purchase_rate'] }),
  term({ id: 'T-027', term: 'Omnichannel Member', domain: 'Customer', owner: 'Customer Insights (R. Okonkwo)', steward: 'L. Ferraro', status: 'Approved', isCde: false,
    definition: 'An active member who bought both in a store and online in the last 12 months.', formula: 'Store purchase AND online purchase in the trailing 12 months',
    synonyms: ['omnichannel shopper', 'cross-channel member'], related: ['T-002'],
    mappings: [{ fqn: `${G}.DIM_CUSTOMER`, column: 'IS_OMNICHANNEL', kind: 'defines' }, { fqn: 'DATA_PRODUCTS.DP_CUSTOMER_LOYALTY_360', column: 'IS_OMNICHANNEL', kind: 'derives' }],
    metricRefs: ['SV_CUSTOMER_LOYALTY.omnichannel_share_pct'] }),
  term({ id: 'T-028', term: 'Discount Rate', domain: 'Sales', owner: 'Finance – FP&A (J. Whitaker)', steward: 'M. Haddad', status: 'Approved', isCde: false,
    definition: 'Promotional and markdown discounts as a share of gross sales.', formula: 'Discounts ÷ gross sales × 100',
    synonyms: ['promotional depth', 'markdown rate'], related: ['T-006', 'T-018'],
    mappings: [{ fqn: `${G}.FCT_SALES`, column: 'DISCOUNT_USD', kind: 'defines' }],
    metricRefs: ['SV_STORE_SALES.discount_rate_pct'] }),
  term({ id: 'T-029', term: 'Inventory at Cost', domain: 'Merchandising', owner: 'Merchandise Planning (A. Brennan)', steward: 'P. Castellanos', status: 'Approved', isCde: false,
    definition: 'Units on hand valued at weighted average unit cost.', formula: 'Σ on-hand units × unit cost',
    synonyms: ['inventory value', 'stock value'], related: ['T-011'],
    mappings: [{ fqn: `${G}.FCT_INVENTORY`, column: 'ON_HAND_COST_USD', kind: 'defines' }],
    metricRefs: ['SV_SUPPLY_CHAIN.inventory_cost'] }),
  term({ id: 'T-030', term: 'Member Annual Spend', domain: 'Customer', owner: 'Customer Insights (R. Okonkwo)', steward: 'L. Ferraro', status: 'Approved', isCde: false,
    definition: 'Net spend by a member across stores and online in the trailing 12 months.', formula: 'Σ net sales identified to the member, trailing 12 months',
    synonyms: ['spend per member', 'member value'], related: ['T-001', 'T-024'],
    mappings: [{ fqn: `${G}.DIM_CUSTOMER`, column: 'SPEND_12M_USD', kind: 'defines' }],
    metricRefs: ['SV_CUSTOMER_LOYALTY.avg_spend_per_member'] }),
  term({ id: 'T-031', term: 'Purchase Order Spend', domain: 'Supply chain', owner: 'Supply Chain (D. Mensah)', steward: 'P. Castellanos', status: 'Approved', isCde: false,
    definition: 'Cost of merchandise received against purchase orders in a period.', formula: 'Σ received line cost',
    synonyms: ['PO spend', 'purchases', 'buy'], related: ['T-014'],
    mappings: [{ fqn: `${G}.FCT_SUPPLIER_DELIVERY`, column: 'COST_USD', kind: 'defines' }],
    metricRefs: ['SV_SUPPLY_CHAIN.po_spend'] }),
];
